PalasoUIWindowsForms/SIL/SILAboutBox.cs
Using UTC helps so that we get the same date regardless of the
user's time zone setting.
Change-Id: Ia0a555a417895eaccff55dc76c9e6407d7f4e0a9
=> Use UTC to calculate built-on date in about dialog (BL-492)

Palaso.Tests/IO/FileUtilsTests.cs, Palaso.Tests/IO/TempFileTests.cs, Palaso.Tests/Palaso.Tests.csproj, Palaso.Tests/SetupFixture.cs, Palaso/IO/FileUtils.cs, Palaso/IO/TempFile.cs, Palaso/Reporting/ConsoleErrorReporter.cs
Allow to call ReplaceFileWithUserInteractionIfNeeded() if the destination file doesn't exist.
Also two additional changes/fixes that I noticed while debugging this issue.
=> Fix file replace

Palaso.Media/ShortSoundFieldControl.cs
For instance in FLEx, if the user wants to use a sound file that is already in the AudioVisual directory, we should just use it, not copy it to some new (and obscure) name and use the copy.
=> LT-15375 Don't copy sound file if it's in the right place already

PalasoUIWindowsForms.GeckoFxWebBrowserAdapter/WebThumbnailViewer.cs, PalasoUIWindowsForms/ImageGallery/ImageUtilities.cs
It seems to be an out-of-memory problem. Displaying thumbnails instead of the full-size image fixes the problem.
=> BL-907: Art of reading image chooser crashing

SIL.Archiving/SIL.Archiving.csproj
The Archiving dll was referencing a specific L10NSharp found in a packages subfolder which makes me think it was using NuGet (or intending to). However the build on TeamCity doesn't seem to be updating this to the latest which causes a runtime problem for FLEx since the signature of a method was updated.
=> Modify hint path for L10nSharp in the Archiving assembly

PalasoUIWindowsForms/ImageToolbox/ArtOfReadingChooser.cs
After applying the text, the size of the text
box causes the instructions to be truncated.
The code change adjusts the size leaving more
than enough vertical space to contain the
string, even if it is resized.
=> BL-966 AoR instructions are truncated

PalasoUIWindowsForms/WritingSystems/WSFontControl.cs
As opposed to Disabled which affects the labels
=> Allow WSFontControl to be set to ReadOnly (PG-94)

PalasoUIWindowsForms/ImageToolbox/ImageToolboxControl.cs, PalasoUIWindowsForms/ImageToolbox/PalasoImage.cs
In BL-1001(bloom) we found that we were actually corrupting someone's original tiff file. Now that we are using taglibsharp instead of the "industry standard" exiftool (which wasn't unicode safe), we realize that it's just too risk to let taglib sharp touch people's original files.
=> Stop saving metadata back into the original file

Palaso/Code/Guard.cs, PalasoUIWindowsForms/ImageToolbox/PalasoImage.cs
Also changed the name of the parameter so that this doesn't happen to anyone else. Having "assertion" be something that is supposed to be "false" is just too dissonant. Also added an even clearer option to Guard, "AssertThat" which takes a true-is-expected argument.
=> Fix polarity bug in SaveUpdateMetadataIfItMakeSense

PalasoUIWindowsForms/UniqueToken/UniqueToken.cs
The cause of the bug is that while waiting, AcquireToken was calling AcquireTokenQuietly().  AcquireTokenQuietly() first checks the static s_fileLock is null and throws if it is not. But it isn't null, it just hasn't been acquired yet. So this fix, instead of delegating to AcquireTokenQuietly(), just takes the existing static lock and tells it to try and acquire.
=> Fix #176 AcquireToken fails if token isn't immediately available

SIL.Archiving.Tests/RampArchivingDlgViewModelTests.cs
Some tests have the "RampRequired" category. This change
checks if RAMP is installed. If not automatically ignores
the tests that require RAMP.
Change-Id: Iddc2835e129fbc600cc01c4bdb799671ef8cbe45
=> Ignore tests if RAMP is not installed

PalasoUIWindowsForms/ClearShare/WinFormsUI/MetadataDisplayControl.cs, PalasoUIWindowsForms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs, PalasoUIWindowsForms/ImageToolbox/ImageToolboxDialog.cs
* new larger license images require a fixed size and zoom to fit in a small space
* also fixed a couple of misspellings (variable name and localization comment)
* removed unused usings in ImageToolboxDialog
=> BL-1045 Fixed MetadataDisplayControl license image

Palaso.Tests/IO/PathUtilitiesTests.cs, Palaso.Tests/Palaso.Tests.csproj, Palaso.Tests/PlatformUtilities/PlatformTests.cs, Palaso/IO/FileLocator.cs, Palaso/IO/PathUtilities.cs, Palaso/PlatformUtilities/Platform.cs
* Add Platform.IsMac and Platform.IsUnix (and Unit Tests)
* Change Platform.IsLinux to return true for ONLY Linux (this should
have been Platform.IsUnix)
* Change implementation that used Platform.IsLinux to use
Platform.IsUnix (not used in chorus, wesay, or fieldworks)
* Change calls to stat to use correct flags for Mac and Linux
* NUnit 2.6.2 added MacOsX to PlatformAttribute's supported
platforms, however Mono doesn't return MacOsX for
Environment.OSVersion.Platform so the NUnit implementation
doesn't work (https://github.com/nunit/nunit/issues/515).
Therefore UnitTests that run only on Mac have to use a
compile-time conditional.
See Palaso.Tests/PlatformUtilities/PlatformTests.cs for
how system-specific conditionals are defined.
=> Change platform-specific properties to support Mac

Palaso.Tests/WritingSystems/IWritingSystemRepositoryTests.cs, Palaso/WritingSystems/IWritingSystemRepository.cs, Palaso/WritingSystems/WritingSystemRepositoryBase.cs, PalasoUIWindowsForms.Tests/Keyboarding/WindowsKeyboardControllerTests.cs, PalasoUIWindowsForms/Keyboarding/Interfaces/IWindowsLanguageProfileSink.cs, PalasoUIWindowsForms/Keyboarding/InternalInterfaces/IKeyboardAdaptor.cs, PalasoUIWindowsForms/Keyboarding/KeyboardController.cs, PalasoUIWindowsForms/Keyboarding/Linux/CommonBaseAdaptor.cs, PalasoUIWindowsForms/Keyboarding/Linux/IbusKeyboardAdaptor.cs, PalasoUIWindowsForms/Keyboarding/Linux/XkbKeyboardAdaptor.cs, PalasoUIWindowsForms/Keyboarding/Windows/KeymanKeyboardAdaptor.cs, PalasoUIWindowsForms/Keyboarding/Windows/MsTsfInterfaces.cs, PalasoUIWindowsForms/Keyboarding/Windows/WinKeyboardAdaptor.cs, PalasoUIWindowsForms/PalasoUIWindowsForms.csproj, TestApps/TestAppKeyboard/KeyboardForm.Designer.cs, TestApps/TestAppKeyboard/KeyboardForm.cs, TestApps/TestAppKeyboard/KeyboardForm.resx
Implement more reliable way of notifying client about input method change.
Depending on the Windows messages doesn't work reliably when input
methods like Keyman or IMEs come into play. These input methods don't
necessarily have a unique language identifier which makes it impossible to
detect the correct input method that is currenlty active.
This change implements notification of input method changes the TSF way
and thus works reliably even with input methods. For older Windows
versions we fall back to Windows messages.
Thanks to Marc Durdin for the analysis of the problem.
=> Keyman 9: Improve input method change detection (LT-15826)

Palaso.MSBuildTasks/Palaso.BuildTasks.csproj, Palaso.MSBuildTasks/UnixName.cs
During the mono build, we need to know whether the platform is
Mac (Darwin) or Linux.  $(OS) is set to Unix for these platforms.
=> Add UnixName BuildTask

PalasoUIWindowsForms/Keyboarding/KeyboardController.cs, PalasoUIWindowsForms/Keyboarding/KeyboardDescription.cs, PalasoUIWindowsForms/Keyboarding/Windows/WinKeyboardAdaptor.cs, TestApps/TestAppKeyboard/KeyboardForm.cs
When a user's machine is messed up so that we can't find a keyboard
we shouldn't crash.
=>  Don't crash if we don't find a keyboard (LT-15498)

Palaso.Tests/CommandLineProcessing/CommandLineRunnerTests.cs, Palaso.Tests/Palaso.Tests.csproj
- move to correct location and namespace
- add tests for timeout
- enable test that is working on Linux
- add comment why the other existing test fails on Linux
=> Some refactoring of CommandLineRunnerTests

SIL.WritingSystems/LdmlDataMapper.cs
This follows the same pattern as the other quotation-marks elements.
=> Remove quotationContinue and alternateQuotationContinue before processing

PalasoUIWindowsForms/Keyboarding/Windows/WinKeyboardAdaptor.cs
When a user opens the Keyman configuration dialog from the Keyboard tab
of the WS properties dialog and changes the language associated with a
Keyman keyboard we used to crash (LT-16172). This fix is similar the the
one for LT-15333 only that we get a different exception in this case.
=> Don't crash when language associated with Keyman keyboard changes

Palaso.Tests/WritingSystems/EthnologueLookupTests.cs, Palaso/WritingSystems/EthnologueLookup.cs, PalasoUIWindowsForms.Tests/PalasoUIWindowsForms.Tests.csproj, PalasoUIWindowsForms.Tests/WritingSystems/LookupIsoControlTests.cs
* searching for 'ak' crashed because comparing
'ak' vs 'akq' and
'akq' vs 'ak'
both returned -1; an inconsistency
=> BL-1141 Fix IComparer in EthnologueLookup so searching doesn't crash

PalasoUIWindowsForms/PalasoUIWindowsForms.csproj, PalasoUIWindowsForms/Reporting/MemoryManagement.cs
* Add copyright notice
* Remove unused usings
* Exclude the Microsoft.VisualBasic.Devices using on Linux because
Mono aggressively pursues every using at runtime and has problems
if it can't find them, even if the code doesn't need them. Excluding
avoids the need for every Linux package using palaso to have access
to it.
=> Exclude Microsoft.VisualBasic.Devices on Linux

build/Palaso.proj
These tests, marked "ByHand," are failing most of the time on Team City.
=> Skip ByHand tests on Team City

PalasoUIWindowsForms/PortableSettingsProvider/GridSettings.cs
Grid sort column and order were already being stored, but we weren't applying them again.
=> In GridSettings.InitializeGrid, apply sort column and order (PG-185)

PalasoUIWindowsForms/Widgets/BitmapButton.cs
This fixes https://jira.sil.org/browse/BL-1212 "Clicking text editing
buttons in the toolbar should not remove focus from the text box, nor
leave the focus on the button".
=> Prevent BitmapButton from being selected when clicked

Palaso/WritingSystems/LdmlDataMapper.cs
To prevent overwriting of an existing LDML file with an empty one in the event event of a failed write, make a backup first and put it back if the write fails.
=> Prevent overwriting an existing LDML file with an empty one

PalasoUIWindowsForms/ImageToolbox/ImageToolboxControl.Designer.cs, PalasoUIWindowsForms/ImageToolbox/ImageToolboxControl.cs
Note that setting ImageInfo.Disposed causes ImageInfo.Dispose() to return
immediately without freeing its resources.  Dispose() sets Disposed
when it is finished freeing everything.
=> Fix a memory leak in ImageToolboxControl

Palaso.Tests/IO/PathUtilitiesTests.cs, Palaso/IO/PathUtilities.cs
Windows explorer fails to open/select files that have composed characters, as happens in Thai. This commit instead uses a windows shell function that does it correctly.
=> Make SelectFileInExplorer handle file with composed characters

Palaso.TestUtilities/FluentAssertXml.cs, SIL.WritingSystems.Tests/LdmlDataMapperTests.cs, SIL.WritingSystems/LdmlDataMapper.cs
Fixed punctuation patterns not getting removed before writing out LDML files which created duplicate entries and made it impossible to remove punctuation patterns.
=> Fixed punctuation patterns not getting removed before writing out LDML files

PalasoUIWindowsForms.TestApp/TestAppForm.Designer.cs, PalasoUIWindowsForms.TestApp/TestAppForm.cs
After closing the WS setup dialog we shouldn't shutdown the
keyboard controller until we exit the app. Otherwise automatic
keyboard switching will stop working when the WS setup dialog is
opened anew.
NOTE: when running the test app on Trusty you'll have to manually
copy the icu.net.dlls for ICU52 from TC - the build currently copies
the ICU48 dlls which cause an immediate crash trying to open the
ws setup dialog.
Change-Id: Ib325f464841695c17aa7593dc080f12d9b0e3d07
=> [Keyboarding] Fix keyboard switching in WS setup dialog in test app

SIL.Windows.Forms.DblBundle/ProjectsListBase.Designer.cs, SIL.Windows.Forms.DblBundle/ProjectsListBase.cs
…e sorting of the list doesn't cause a spurious selection.
=> Fixed ProjectsListBase so that if no project is selected, changing the sorting of the list doesn't cause a spurious selection.

SIL.Windows.Forms/app.config
When PalasoUIWindowsForms was changed to SIL.Windows.Forms,
the dllmap entries were removed from the app.config.  At least
the entries for libgtk and libgdk are needed for WeSay packages
for Linux to build.  Why were these removed?
=> Re-add previous dllmaps

PalasoUIWindowsForms/SettingProtection/SettingProtectionDialog.cs, PalasoUIWindowsForms/SettingProtection/SettingsProtection.cs
Added CoreProductName to SettingsProtectionSingleton so the
Application.ProductName can be overridden. The specific example that
prompted this change is Bloom, where the Application.ProductName for
is 'BloomAlpha' for alpha releases and 'BloomBeta' for beta releases,
but we wish to display just 'Bloom' to the user in the
SettingsProtectionDialog.
=> BL-2415: Use ProductName setting from config file, if present

Palaso.Tests/reporting/ErrorReportTests.cs, Palaso/Reporting/ErrorReport.cs
On Linux this change adds the currently running desktop environment (Unity, gnome shell etc) to the error report.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/263)
=> Add desktop environment to error report

Palaso.Tests/PlatformUtilities/PlatformTests.cs, Palaso.Tests/reporting/ErrorReportTests.cs, Palaso/PlatformUtilities/Platform.cs, Palaso/Reporting/ErrorReport.cs, PalasoUIWindowsForms.TestApp/TestAppForm.cs
- Platform.DesktopEnvironment returns the name of the desktop
environment, e.g. xfce or unity
- Platform.DesktopEnvironmentInfoString returns more info based on
the environment varibles set, e.g. "xfce (xubuntu)"
- Display the current desktop environment as title in the test app
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/265)
=> Add properties to get desktop environment to Platform class

Palaso.Tests/PlatformUtilities/PlatformTests.cs, Palaso/PlatformUtilities/Platform.cs, PalasoUIWindowsForms/Keyboarding/KeyboardController.cs
When run from a terminal without being attached to an X-server
the environment variables for the desktop environment are not set.
In this case we shouldn't crash but simply return an empty string.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/271)
=> Fix Platform.DesktopEnvironment property

PalasoUIWindowsForms/Keyboarding/Linux/CombinedIbusKeyboardSwitchingAdaptor.cs
When using the IPA KMFL keyboard we get a commit from IBus after
every character. At least on Wasta 14 this causes a keyboard
activation. The previous code that didn't check if the keyboard
was already set causes the IPA keyboard to lose its context thus
preventing the IPA keyboard from working properly. This change
removes the override of IBusKeyboardAlreadySet() method and uses
the base implementation instead.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/272)
=> Don't set ibus keyboard again when it's already set (LT-16179)

PalasoUIWindowsForms/ImageGallery/ArtOfReadingImageCollection.cs, PalasoUIWindowsForms/ImageToolbox/AcquireImageControl.cs, PalasoUIWindowsForms/ImageToolbox/ArtOfReadingChooser.cs, PalasoUIWindowsForms/ImageToolbox/ImageToolboxControl.cs, PalasoUIWindowsForms/ImageToolbox/ImageToolboxDialog.cs
This does not change the GUI at all, and does not require a change to calling ImageToolboxDialog if you're happy with English lookup or don't have access to the new Art of Reading multilingual index.  It does provide a way to pass in the language code of the language you'd like to use for image searches in Art of Reading.
=> Add multilingual search index to ArtOfReadingImageCollection

PalasoUIWindowsForms/Keyboarding/Linux/IbusKeyboardSwitchingAdaptor.cs
When using the keyboarding code in FW HandleGotFocus got called
twice because of some specific requirements of FW on Linux. This
change checks the control.Focus state and returns if this doesn't
tell us that we have focus.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/275)
=> Don't execute IbusKeyboardSwitchingAdaptor.HandleGotFocus twice

PalasoUIWindowsForms/Keyboarding/Linux/XkbKeyboardRetrievingAdaptor.cs
On Wasta 14 without the parens we returned "keyboard" as arguments
which broke the keyboard setup link.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/282)
=> Fix problem with keyboard setup link in Wasta 14

Palaso/IO/FileLock/SimpleFileLock.cs
Add new method to create a SimpleFileLock from a file path. This allows applications to specify where the lock file will be created.
=> Allow creation of a file lock from a file path

PalasoUIWindowsForms.TestApp/TestAppForm.cs, PalasoUIWindowsForms/Keyboarding/KeyboardController.cs, PalasoUIWindowsForms/Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs, PalasoUIWindowsForms/Keyboarding/Linux/KeyboardRetrievingHelper.cs, PalasoUIWindowsForms/Keyboarding/Linux/UnityIbusKeyboardRetrievingAdaptor.cs, PalasoUIWindowsForms/Keyboarding/Linux/UnityKeyboardRetrievingHelper.cs, PalasoUIWindowsForms/Keyboarding/Types/Unmanaged.cs
Add the keyboard adaptors in use as well as the IBus version to
the properties of the ErrorReport dialog so that we get this
information if the user submits an error report.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/284)
=> Add keyboard adaptor information to ErrorReport properties

Palaso/Reporting/ErrorReport.cs
Using Dictionary<string,string> instead of StringDictionary
preserves the case of the dictionary keys which makes them easier
to read in an error report.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/286)
=> Use Dictionary<string,string> for ErrorReport properties

PalasoUIWindowsForms.GeckoFxWebBrowserAdapter/WebThumbnailViewer.cs, PalasoUIWindowsForms.TestApp/TestAppForm.Designer.cs, PalasoUIWindowsForms.TestApp/TestAppForm.cs
Hiding the viewer during search prevents a momentary black screen on first query (and only the first).
The related Bloom issue: https://silbloom.myjetbrains.com/youtrack/issue/BL-2729
=> Fix a momentary black box artifact when querying  Art Of Reading

Palaso/Progress/Progress.cs, PalasoUIWindowsForms/Progress/LabelProgress.cs, PalasoUIWindowsForms/Progress/LogBox.cs, PalasoUIWindowsForms/Progress/SimpleStatusProgress.cs, PalasoUIWindowsForms/Progress/TextBoxProgress.cs, PalasoUIWindowsForms/Reporting/WinFormsErrorReporter.cs
Use Safe String Formatting when formatting unknown strings
=> API: Remove public string-formatting methods from Progress

Palaso/Reporting/ErrorReport.cs, TestApps/ReportingTest/Program.cs
* Uses the version information from a network api when Windows
reports that it is "Windows 8"
* This will allow applications to report useful version information
on versions of windows which are released after the application is built.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/295)
=> Retrieve Windows version information from a different api

PalasoUIWindowsForms.Tests/ImageToolbox/PalasoImageTests.cs, PalasoUIWindowsForms/ClearShare/MetaData.cs, PalasoUIWindowsForms/ImageToolbox/PalasoImage.cs
See commit messages for more info.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/299)
=> Fix PalasoImage tests and preserve b&w color depth of PNGs

PalasoUIWindowsForms.Tests/ImageToolbox/PalasoImageTests.cs, PalasoUIWindowsForms/ImageToolbox/PalasoImage.cs
Also make the new throw-instead-of-Assert behavior opt-in and introduce an exception class just for it. It would now be possible to throw even in non-DEBUG builds, if desired. Otherwise, the behavior is now the same as it was for years, prior to my recent commit.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/301)
=> Add label for debugging PalasoImage & make unit tests dispose properly

SIL.WritingSystems.Tests/Migration/GlobalWritingSystemRepositoryMigratorTests.cs, SIL.WritingSystems/LdmlDataMapper.cs, SIL.WritingSystems/SIL.WritingSystems.csproj
If an existing writing system definition is reused when loading an LDML file, we want to make sure that any properties that are not set during reading are reset to their defaults, otherwise we can run into issues.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/310)
=> Reset writing system properties when reading an LDML file

SIL.Lexicon/ProjectLexiconSettingsWritingSystemDataMapper.cs, SIL.Lexicon/UserLexiconSettingsWritingSystemDataMapper.cs, SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs, SIL.WritingSystems.Tests/SIL.WritingSystems.Tests.csproj, SIL.WritingSystems.Tests/TestLdmlInFolderWritingSystemRepository.cs, SIL.WritingSystems.Tests/TestWritingSystemCustomDataMapper.cs, SIL.WritingSystems/ILocalWritingSystemRepository.cs, SIL.WritingSystems/LdmlInFolderWritingSystemRepository.cs, SIL.WritingSystems/LocalWritingSystemRepositoryBase.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/312)
=> Fix bug where app-specific WS settings can get lost when replacing local WSs with newer global WSs

SIL.Windows.Forms/ImageGallery/ThumbnailViewer.cs, SIL.Windows.Forms/ImageToolbox/ArtOfReadingChooser.cs
Wasn't sure why doing a search button click when loading keeps the background from turning black. It turned out what was needed was a Clear() of the thumbnailviewer. Still not sure why, though.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/311)
=> BL-2901 fix background of AOR search which turned black

SIL.Archiving/Generic/ArchivingFileSystem.cs, SIL.Core.Tests/CommandLineProcessing/CommandLineRunnerTests.cs, SIL.Core.Tests/UsbDrive/UsbDeviceInfoTests.cs, SIL.Media.Tests/AudioRecorderTests.cs, SIL.Media.Tests/FFmpegRunnerTests.cs, SIL.Media.Tests/MediaInfoTests.cs, SIL.Media/MediaInfo.cs, SIL.Windows.Forms.Keyboarding.Tests/WinKeyboardAdaptorTests.cs, SIL.WritingSystems/Sldr.cs
Fix (or explicitly ignore) several tests that failed on my machine, mostly on Linux.
Also fix Sldr.GetAvailableLanguageTags() which failed when using a non-US culture, and MediaInfo channel info on Trusty which comes with a different ffmpeg version that produces a slightly different output.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/306)
=> Fix failing tests

SIL.Windows.Forms/ImageToolbox/ArtOfReadingChooser.cs
The link label was overlapping the message text above it at times.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/316)
=> Fix the position of download link label in empty AOR display

SIL.Windows.Forms.WritingSystems.Tests/LanguageLookupModelTests.cs, SIL.Windows.Forms.WritingSystems.Tests/SIL.Windows.Forms.WritingSystems.Tests.csproj, SIL.Windows.Forms.WritingSystems/LanguageLookupControl.Designer.cs, SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs, SIL.Windows.Forms.WritingSystems/LanguageLookupControl.resx, SIL.Windows.Forms.WritingSystems/LanguageLookupDialog.cs, SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs, SIL.Windows.Forms.WritingSystems/WritingSystemSetupView.cs
* add "Show all dialects" checkbox to dialog
* filter out all languages with regions specified if not checked
* closes #315
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/317)
=> Filter out dialects from LanguageLookupDialog by default

SIL.Core.Tests/IO/FileLock/SimpleFileLockTests.cs, SIL.Core.Tests/SIL.Core.Tests.csproj, SIL.Core/IO/FileLock/FileLockContent.cs, SIL.Core/IO/FileLock/FileSys/LockIO.cs, SIL.Core/SIL.Core.csproj, SIL.Core/packages.config
* generate lock file contents using JSON.NET instead of object serialization
* add unit tests for SimpleFileLock
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/322)
=> Update SimpleFileLock to generate lock files that can be read by older versions of Palaso

PalasoUIWindowsForms/Keyboarding/Windows/WinKeyboardAdaptor.cs
Under some circumstances ActiveKeyboard can't detect the currently
active keyboard and used to return null which caused a crash. Now
we return KeyboardDescriptionZero instead.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/324)
=> [v2.6] Fix crash from getting active keyboard

SIL.Windows.Forms.WritingSystems/LanguageLookupDialog.Designer.cs
The code that normally determines whether it is enabled is only executed when the language control registers a change, but initially _languageLookupControl.HaveSufficientInformation is false because that control does not have anything set.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/323)
=> Made OK button on LanguageLookupDialog disabled by default

SIL.DictionaryServices.Tests/LexEntryRepositoryCachingTests.cs, SIL.DictionaryServices.Tests/LexEntryRepositoryTests.cs, SIL.DictionaryServices.Tests/Processors/MergeHomographsTests.cs, SIL.DictionaryServices.Tests/Properties/AssemblyInfo.cs, SIL.Lexicon.Tests/ProjectLexiconSettingsWritingSystemDataMapperTests.cs, SIL.Lexicon.Tests/Properties/AssemblyInfo.cs, SIL.Lexicon.Tests/UserLexiconSettingsWritingSystemDataMapperTests.cs, SIL.Lift.Tests/Options/WritingSystemsInOptionsListFileHelperTests.cs, SIL.Lift.Tests/Properties/AssemblyInfo.cs, SIL.Lift.Tests/WritingSystemsInLiftFileHelperTests.cs, SIL.TestUtilities/OfflineSldrAttribute.cs, SIL.Windows.Forms.WritingSystems.Tests/LanguageLookupModelTests.cs, SIL.WritingSystems.Tests/SldrTests.cs
* offline mode is enabled only once for a fixture or assembly
* added OfflineSldrAttribute to every assembly that might access SLDR
* removed redundant OfflineSldrAttribute from test fixtures
* fixed online SLDR tests so that SLDR is reset to offline mode
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/328)
=> Update OfflineSldrAttribute so that it doesn't enable offline mode on every test

SIL.Windows.Forms.Keyboarding/KeyboardController.cs, SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs
Under some circumstances ActiveKeyboard can't detect the currently
active keyboard and used to return null which caused a crash. Now
we return KeyboardController.NullKeyboard instead.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/325)
=> Fix crash from getting active keyboard

SIL.Core/ObjectModel/ObservableDictionary.cs, SIL.Core/ObjectModel/ObservableHashSet.cs, SIL.Core/ObjectModel/ObservableObject.cs, SIL.Core/ObjectModel/ReadOnlyObservableCollection.cs, SIL.Core/ObjectModel/ReadOnlyObservableList.cs
Although the event handlers are checked for null before being called, this is not thread-safe. If another thread removed the last event handler in between the check and the call, a NullReferenceException could still happen.
Note: the ?. operator in C# 6.0 will make this commit obsolete. See https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6#null-conditional-operators (especially the last paragraph giving the `PropertyChanged?.Invoke(this, args);` example) for more details.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/337)
=> Protect against event handlers being null

build/NuGet.targets
This change adds the ability to restore packages without having
a solution. This is not needed for libpalaso, but `NuGet.targets`
serves as a template for other projects where this is useful
to have.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/333)
=> Improve NuGet.targets

SIL.Windows.Forms.Tests/ImageToolbox/ImageToolboxTests.cs, SIL.Windows.Forms/ClearShare/MetaData.cs, SIL.Windows.Forms/ImageToolbox/PalasoImage.cs
Image metadata can contain an Orientation field which
indicates how it needs to be flipped and/or rotated to
look right. The image library was ignoring this, which
caused images to look wrong in the toolbox, and was not
copying the metadata to new image files, which caused
them to look wrong elsewhere.
This patch fixes both these problems, though fixing
the first made it unnecessary to fix the second at least
to solve THIS issue.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/340)
=> BL-2966 Make image library handle image orientation

SIL.Core.Tests/UsbDrive/UsbDeviceInfoTests.cs, SIL.Core/CoreSetup.cs, SIL.Core/SIL.Core.csproj, SIL.Core/UsbDrive/Linux/UDisks.cs, SIL.Core/UsbDrive/Linux/UsbDriveInfoUDisks2.cs, SIL.Core/UsbDrive/UsbDriveInfo.cs
This is needed on new systems (such as Ubuntu 16.04) that have
udisks2 but not udisks.
This change is based on a change from MarkS that he made on the
libpalaso-2.6 branch (https://github.com/sillsdev/libpalaso/pull/338).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/341)
=> Use udisks2 if available

SIL.Windows.Forms/AppColorPalette/AppColorPaletteExtender.cs, SIL.Windows.Forms/SIL.Windows.Forms.csproj
Added an extender to enable applications to use custom color palettes and have the default color scheme apply in Designer.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/346)
=> App color palette extender

SIL.Windows.Forms.Keyboarding.Tests/XkbKeyboardAdapterTests.cs, SIL.Windows.Forms.Keyboarding/Linux/XkbKeyboardRetrievingAdaptor.cs
This crash happened during a data migration (to 7000069) in FW. We
should fail gracefully if the keyboard id is not in the expected
format.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/332)
=> Fix a crash with corrupt keyboard id

build/NuGet.targets
- use https to get packages where possible
- specify package sources when restoring packages
In case getting packages fails with a certificate error you might
have to run `mozroots --import --sync` first to import the root
certificates into mono.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/342)
=> Improve NuGet package restore

SIL.Core/Code/Detect.cs
We don't need a List here when we're never storing more than a single object. Use a HashSet instead for O(1) lookup.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/336)
=> Improve performance of Detect.Reentry

SIL.Windows.Forms/ClearShare/ClearShareResources.Designer.cs
This was accidentally missed when the namespaces in libpalaso were changed from Palaso... to SIL...
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/350)
=> Fixed namespace used to create ResourceManager for ClearShareResource

PalasoUIWindowsForms/Keyboarding/Linux/CombinedIbusKeyboardSwitchingAdaptor.cs
This fixes https://jira.sil.org/browse/LT-17012.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/353)
=> Prevent hang during keyboard switching on Wasta Linux

SIL.Core/Reporting/ErrorReport.cs, SIL.Core/Settings/CrossPlatformSettingsProvider.cs, SIL.Windows.Forms.Tests/SettingsProviderTests.cs
Previously, if the user.config file was corrupt, it would try to put up a UI. However the client may trigger this before UI is even possible. This was killing Bloom silently. This PR adds some unit tests around these situations, verifying that it can self-heal. It also copies corrupt files to ".bad" for debugging purposes. Finally, it adds an optional method a client can use to safely check and heal the settings before UI is possible (Bloom will use this).
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/356)
=> Improve handling of empty or corrupt user.config file

SIL.Core.Tests/Threading/GlobalMutexTests.cs, SIL.Core/Threading/GlobalMutex.cs, SIL.TestUtilities/OfflineSldr.cs, SIL.WritingSystems.Tests/SldrTests.cs, SIL.WritingSystems/Sldr.cs, TestApps/SIL.Windows.Forms.TestApp/Program.cs
The static Sldr class uses a global mutex to synchronize access to the SLDR cache folder. Unfortunately, this mutex was not being disposed of properly. In order to fix this issue, I added Initialize() and Cleanup() methods to the Sldr class that must be called by any applications that use the writing systems classes.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/357)
=> Properly dispose the SLDR cache mutex

SIL.Core.Tests/IO/TempFileForSafeWritingTests.cs, SIL.Core.Tests/SIL.Core.Tests.csproj, SIL.Core/IO/TempFileForSafeWriting.cs
Underlying problem is that File.Replace(), fails on JAARS network drives, so this has a fall-back to do the same thing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/370)
=> Fix BL-3222 TempFileForSafeWriting  fails on JAARS network drives

SIL.Windows.Forms.GeckoBrowserAdapter/WebThumbnailViewer.cs
This removes the no longer needed fix for BL-907 (out of memory
crashes).  Relatively recent updates to Geckofx29 and Geckofx45
fixed the major memory leaks on Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/383)
=> Fix the very slow Linux ArtOfReading chooser (BL-3659)

SIL.TestUtilities/FluentAssertXml.cs
* Add an option to skip printing the xml to the console
for tests which are working with very large files
* Add the option for an informative message to help
debugging assert failures
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/390)
=> Improve failure message options in FluentAssert

SIL.Core/Code/RetryUtility.cs, SIL.Core/IO/RobustFile.cs, SIL.Core/IO/RobustIO.cs, SIL.Core/SIL.Core.csproj
I'm making the assumption that no other code is using this yet besides Bloom.
I will fix Bloom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/393)
=> Move RetryUtility from SIL.Retry to SIL.Code

SIL.Core.Tests/IO/FileUtilsTests.cs
Forgot to move the unit tests when I moved the StripFilePrefix
from Flexbridge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/401)
=> Add unit tests for FileUtils.StripFilePrefix

Palaso.MSBuildTasks/Palaso.BuildTasks.csproj, Palaso.MSBuildTasks/UnitTestTasks/NUnit.cs, Palaso.MSBuildTasks/UnitTestTasks/NUnit3.cs
The new NUnit3 task has two new properties: `UseNUnit3Xml` to use the
native XML format of NUnit 3.0 (default to NUnit 2.x format), and
`NoColor` to display console output without color (defaults to `false`,
i.e. will display colors).
This change also changes the parameter separator character that gets
passed to NUnit 2.x to "--" instead of using '/' or '-' depending on
the platform. This seems to work on both Windows and Linux at least
with NUnit 2.8.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/405)
=> Add new NUnit3 build task

SIL.Core.Tests/IO/PathUtilitiesTests.cs, SIL.Core/IO/PathUtilities.cs
This method checks that the path contains a subdirectory named
'subdir' instead of checking that path contains the string
'subdir'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/407)
=> Add new PathUtilities.PathContainsDirectory() method

SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs
I'm not sure if it was an oversight or not, but it looks like the constructor of CultureInfo throws the exception, not the properties. This was found in Paratext.
Also removed comment referring to a website that no longer exists.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/410)
=> Fixed CultureNotFoundException caused by some old versions of Keyman

SIL.Core.Tests/IO/TempFileTests.cs, SIL.Core/IO/TempFile.cs
This is useful for Bloom and other programs whose users may want
to ensure that temporary files retain the same permissions as as
current files when shared over the network.
(See http://issues.bloomlibrary.org/youtrack/issue/BL-3954.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/415)
=> Add TempFile.InFolderOf method

DistFiles/Palaso.en.tmx, SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs, SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorDialog.cs, SIL.Windows.Forms/FileSystem/ConfirmRecycleDialog.cs, SIL.Windows.Forms/FileSystem/ConfirmRecycleDialog.designer.cs, SIL.Windows.Forms/ImageToolbox/ArtOfReadingChooser.cs, SIL.Windows.Forms/UniqueToken/UniqueToken.cs
Part of the localization cleanup work.
TMX is generated from XLIFF 2.0 file. Hard coded source strings are matched with TMX where minor changes were needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/413)
=> Update English TMX and source string to match.

.gitignore, SIL.Windows.Forms/SIL.Windows.Forms.csproj
Our mono*-sil packages come with gtk-sharp 2.12. I had problems
compiling when the references pointed to 2.4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/416)
=> Change referenced versions of gtk assemblies

SIL.Windows.Forms.Tests/ClearShare/CreativeCommonsLicenseTests.cs, SIL.Windows.Forms/ClearShare/CreativeCommonsLicense.cs
Also specify what we think a version number should look like, regardless of locale. Sorry, kinda two-in-one here, but both version related.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/417)
=> If the IGO option is chosen for a CC license, use version number "3.0"

SIL.Core/Reporting/Logger.cs
Do not attempt to treat the message as a format string if no args are supplied. Report the problem if the format is attempted and fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/418)
=> Made WriteMinorEvent more robust

SIL.WritingSystems.Tests/GlobalWritingSystemRepositoryTests.cs, SIL.WritingSystems/GlobalWritingSystemRepository.cs
A bad .ldml file was stopping the global repository from initializing. The bad file was most likely caused by a system crash since it was all nulls.
Changed code to catch XmlException's that occur when reading the .ldml file and to rename the file to be a .ldml.bad file (thought renaming was betting than deleting in case the file was needed for investigation).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/422)
=> PTX-49759 prevent corrupted .ldml file in global repository from stopping initialization

SIL.WritingSystems/CharacterSetDefinition.cs, SIL.WritingSystems/LdmlDataMapper.cs
The cross reference callers and verse segments need to be ordered sequences, so I changed the CharacterSetDefinition code to treat these the same way as it was already treating footnote callers.
Main change is to replace the hard coded check for "footnotes" to a new boolean IsSequenceType property.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/437)
=> PTX-50439 character sets for crossrefs and versesegments need to be to reated same as footnotes since order needs to be preserved

SIL.Core.Tests/IO/DirectoryUtilitiesTests.cs, SIL.Core/IO/DirectoryUtilities.cs, SIL.Core/IO/RobustIO.cs, SIL.TestUtilities/TestUtilities.cs
Also make the TestUtilities equivalent do the same, and make the RobustIO version notice if DeleteDirectoryRobust fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/435)
=> Make DeleteDirectoryRobust mow down readonly files, by default

SIL.Windows.Forms/ClearShare/CreativeCommonsLicense.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/443)
=> Handle creative commons urls with missing version number (BL-4108)

Palaso.DictionaryServices.Tests/Lift/LiftWriterTests.cs, Palaso.DictionaryServices/Lift/LiftWriter.cs, Palaso.Tests/Xml/CanonicalXmlSettingsTests.cs, Palaso/Text/MultiTextBase.cs, Palaso/Xml/CanonicalXmlSettings.cs
The previous code assumed that all line endings are written as \r\n. However that was not the case when the data that we wrote contained line endings. This change forces line ending normalization so that line endings always end up as \r\n even when in the data we write. That helps with FW and LfMerge S/R where the ParserParameters contain line endings which will otherwise introduce a difference between Windows and Linux.
This change also allows to pass a `NewLineHandling` parameter when calling `CreateXmlWriterSettings`. Passing `NewLineHandling.None` will keep the previous behavior and is needed for Lift where one test expects that the line endings stay as they are.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Normalize line endings when writing XML files

SIL.Windows.Forms.Tests/ClearShare/CreativeCommonsLicenseTests.cs, SIL.Windows.Forms.Tests/ClearShare/MetadataEditorControlTests.cs, SIL.Windows.Forms/ClearShare/CreativeCommonsLicense.cs
* setting IGO changes license version to 3.0
* unsetting IGO should give us back the default
version (currently 4.0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/447)
=> BL-4184 Fix IGO license unset (on Bloom3.7)

SIL.WritingSystems/Sldr.cs
I noticed that the SIL.WritingSystems test GetLdmlFile_LanguageTagWithSuppressedScript_DownloadsFile started failing on local builds (it isn't run on teamcity). I couldn't see anything that I'd done that broke it so I dug deeper. 
If the language tag that you ask for the ldml file for has a suppressed script or region then Sldr::GetLdmlFile will notice that the webResponse is a redirect so it generates a new request and tries again. The current codes assumes that the redirection URL is the same form as the original request.
https://staging.scriptsource.org/ldml/TAG?...
but now it is 
https://staging.scriptsource.org/cms_staging/scripts/module.php?module_id=ldml_server&ws_id=TAG?...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> SLDR redirect changed recently

build/buildupdate.mono.sh, build/buildupdate.win.sh
the buildupdate files are currently out of sync with teamcity which uses a tagged build of l10sharp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/449)
=> libpalaso-2.6: update buildupdate - tagged l10n

LanguageData/NewLanguageIndex.cs, SIL.WritingSystems.Tests/LanguageLookupTests.cs, SIL.WritingSystems/Resources/LanguageDataIndex.txt
The  previous work did not sufficiently exclude gax, gaz and hae.
This code completely excludes a list of specified language codes.
It also excludes alternative names in specified regions, and uses the L name specified in ethnologue rather than the first name in the iana subtag.
The tests are updated to make sure the codes really aren't there
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/452)
=> Completely exclude specific language codes, and alternative names from specific regions

SIL.Windows.Forms.Tests/ClearShare/MetadataTests.cs, SIL.Windows.Forms/ClearShare/MetaData.cs
The code can now handle strings like
"Copyright, SIL International 2009."
or
"Copyright SIL Papua New Guinea 1996"
as well as what it could handle before.  This fixes a couple of Bloom
related issues: http://issues.bloomlibrary.org/youtrack/issue/BL-3552
and http://issues.bloomlibrary.org/youtrack/issue/BL-4254.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/456)
=> Enhance copyright string parsing methods

SIL.WritingSystems.Tests/LdmlDataMapperTests.cs, SIL.WritingSystems/LanguageSubtag.cs, SIL.WritingSystems/RegionSubtag.cs, SIL.WritingSystems/ScriptSubtag.cs, SIL.WritingSystems/StandardSubtags.cs, SIL.WritingSystems/Subtag.cs, SIL.WritingSystems/VariantSubtag.cs
move IsDeprecated property to SubTag to allow filtering of regions, scripts and variants
This is a revised pull request with 2 changes requested by Eberhard. Tried just amending previous one, but something went wrong in the process.
The deprecated flag was already being set from tag data, but it was only being saved on the LanguageSubTag. This change makes the setting available on all subtags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/459)
=> PTX-48214 move IsDeprecated property to SubTag

SIL.Windows.Forms/ClearShare/MetaData.cs
Removes duplication in MetaData.GetSummaryParagraph()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/461)
=> BL-4243 Don't show license url again if embedded in description

SIL.Windows.Forms.Tests/ClearShare/MetadataTests.cs, SIL.Windows.Forms/ClearShare/CreativeCommonsLicense.cs, SIL.Windows.Forms/ClearShare/MetaData.cs
Moves license to *after* the copyright. Creative Commons licenses now also emit the optional extra rights statement, if present.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/462)
=> Tweak MinimalCredits() output, always include rights statement

SIL.Windows.Forms/Progress/LogBox.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/465)
=> Fixed bug in LogBox.SetFont that was keeping it from setting the new font chosen by the user.

Palaso/IO/DirectoryUtilities.cs
- pass `true` to File.Copy so that existant files get overwritten
- don't hide exceptions for subdirectories but do as the method
name promises and throw the exception
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/470)
=> Fix two issues with copying directories

SIL.DblBundle/Text/TextBundle.cs
This is an attempt to prevent occasional spurious test failures, like this:
Test(s) failed. System.UnauthorizedAccessException : Access to the path 'C:\ProgramData\FCBH-SIL\Glyssen\ach-CM\test~~ProjectTeststmp7320\Test Bundle Publication Audio\versification.vrs' is denied.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/473)
=> Made copying of versification file more robust

SIL.Archiving/ArchivingDlg.Designer.cs, SIL.Archiving/ArchivingDlg.cs, SIL.Archiving/IMDI/IMDIArchivingDlg.cs, SIL.Archiving/IMDI/IMDIArchivingDlgViewModel.cs, SIL.Archiving/IMDI/IMDIPackage.cs
the package creation begins.
Fixed the logic for changing the destination folder for an IMDI archive so that it takes effect immediately and not the NEXT time the data is archived.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/481)
=> Added code to disable/hide controls that are no longer relevant once

BuildTaskTests/Palaso.BuildTask.Tests.Helper/Palaso.BuildTask.Tests.Helper.csproj, BuildTaskTests/UnitTestTasks/NUnitTests.cs
It appears that the Palaso.BuildTask.Tests.Helper was moved but test
not updated to allow it to work after the move. This corrects the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/483)
=> Update Build tests to fix after restructuring

SIL.Core.Tests/Text/MultiTextBase.Tests.cs
* Fix a test that will fail in mono4-sil because attribute
order from a serializer is not guaranteed
* Delete commented out tests
* Re-introduce part of the functionality of a test that
was commented out
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/497)
=> Improve MultiTextBase test stability and coverage

DistFiles/Palaso.en.tmx, DistFiles/Palaso.es.tmx, DistFiles/Palaso.fr.tmx, SIL.Windows.Forms/FlexibleMessageBox.cs, SIL.Windows.Forms/SIL.Windows.Forms.csproj, TestApps/SIL.Windows.Forms.TestApp/TestAppForm.Designer.cs, TestApps/SIL.Windows.Forms.TestApp/TestAppForm.cs
I got this from http://www.codeproject.com/Articles/601900/FlexibleMessageBox (and made a few changes to support better localization and overriding of the LinkClicked handler).
Some of the benefits of this over the standard .Net MessageBox are:
* It can be resized and the content is correctly word-wrapped
* It tries to auto-size the width to show the longest text row
* It never exceeds the current desktop working area
* It displays a vertical scrollbar when needed
* It supports (auto-detected) hyperlinks in text
* It allows copying of messages to clipboard
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/494)
=> Added a FlexibleMessageBox

SIL.DictionaryServices/Lift/LiftWriter.cs
_constructionStack is #if DEBUG, so all of its references must be also.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/517)
=> Fix the broken Release build of libpalaso

SIL.Windows.Forms.Keyboarding/KeyboardController.cs, SIL.Windows.Forms.WritingSystems.Tests/WritingSystemSetupPMTests.cs
* Investigation into failing tests revealed some dead code in the WS tests
* Added improved error messages when a keyboard isn't found
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/500)
=> Improve error reporting from KeyboardController and remove unneeded code in WSTests

SIL.Scripture.Tests/ScrVersTests.cs, SIL.Scripture/BookSet.cs, SIL.Scripture/ScrVers.cs, SIL.Scripture/Versification.cs, SIL.Windows.Forms/ReflectionHelper.cs
These changes are needed to change Paratext to using the code moved to **SIL.Scripture**.
Because the original implementation of custom versifications was very Paratext-specific, it was removed when the code was moved to **SIL.Scripture**. This work is to re-do the custom versifications in a way that it can be inside **SIL.Scripture**, but while still maintaining the functionality needed by Paratext.
Also added some helper methods from Paratext to **SIL.Scritpure** (in **BookSet**).
Also some code cleanup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/524)
=> Re-added support for custom versifications (was removed when originally moved from Paratext)

SIL.Core/Reflection/ReflectionHelper.cs, SIL.Core/SIL.Core.csproj, SIL.Scripture.Tests/SIL.Scripture.Tests.csproj, SIL.Scripture.Tests/ScrVersTests.cs, SIL.Windows.Forms/AppColorPalette/AppColorPaletteExtender.cs, SIL.Windows.Forms/SIL.Windows.Forms.csproj
Moved **ReflectionHelper** to **SIL.Core** so it doesn't depend on **System.Windows.Forms** (and it makes more sense there).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/526)
=> Moved ReflectionHelper to SIL.Core so it doesn't depend on System.Windows.Forms

ExtractCopyright.Tests/ExtractCopyright.Tests.csproj, ExtractCopyright/ExtractCopyright.csproj
I am adding x64 and x86 build items to the .csproj files as I did to the other projects during the common sprint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/531)
=> Add other platforms to ExtractCopyright projects

SIL.Media.Tests/AudioRecorderTests.cs, SIL.Media/AlsaAudio/AudioAlsaSession.cs, SIL.Media/AudioIrrKlangSession.cs, SIL.Media/AudioNullSession.cs, SIL.Media/ISimpleAudioSession.cs, SIL.Media/ShortSoundFieldControl.cs, SIL.Media/SoundFieldControl.cs
make disposable
use IFileFactory to avoid locking file
Allow Thread.Sleep() logic to work.
Create test for longer sound playing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/532)
=> Fix broken implementation of irrKLang

Palaso.MSBuildTasks/Palaso.BuildTasks.csproj, Palaso.MSBuildTasks/Properties/AssemblyInfo.cs
The acknowledgment can be safely removed because it will never be read regardless
=> Remove superflous reference to SIL.Core in Palaso.BuildTasks

SIL.Core.Tests/PlatformUtilities/PlatformTests.cs, SIL.Core.Tests/SIL.Core.Tests.csproj, SIL.Core/PlatformUtilities/Platform.cs, TestApps/ReportingTest/Reporting.TestApp.csproj, TestApps/SIL.Windows.Forms.TestApp/TestAppForm.cs
The new property returns the version of the currently running Mono (e.g. 5.0.1.1 (2017-02/5077205 Thu May 25 09:16:53 UTC 2017)), or the empty string when run on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/538)
=> Add Platform.MonoVersion property

SIL.Scripture.Tests/ScrVersTests.cs, SIL.Scripture/ScrVers.cs, SIL.Scripture/Versification.cs
Fixed not all versifications being returned by the VersificationTables method (i.e. no built-in versifications were ever being included).
Fixed built-in versifications not being cached so a new one was created each time. This resulted in significantly increased memory usage and decreased performance (because a deep-compare was then necessary).
Fixed a versification named a number (e.g. "30") throwing an exception (caused by **Enum.TryParse** accepting the string representation of a number as a valid value)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/546)
=> Fixed a few bugs found in the Versification.Table class

SIL.Archiving.Tests/RampArchivingDlgViewModelTests.cs, SIL.Archiving/RampArchivingDlgViewModel.cs, environ
At least locally on my machine this resolved most of the "Could not set X locale modifiers" that we
often see on TC. I still get one error from an Archiving test, but that doesn't get run on TC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/554)
=> Work around "Could not set X locale modifiers" error

SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj, SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs
With this change it's no longer necessary to copy the Keyman* files
on Linux. Previously they were required to use KeyboardController
on Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/555)
=> [Linux] Fix dependency on Keyman* files

SIL.Core/Xml/XmlUtils.cs, build/Palaso.proj
The preferred way is to use `SetAttribute` which deals with both
setting an attribute and replacing an existing one.
`AppendAttribute` always appended the attribute to the end of
the collection (and the collection removed an already existing one
with the same name). `SetAttribute` will keep an existing attribute
and just change its value, thus keeping the order of attributes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/550)
=> [API] Mark XmlUtils.AppendAttribute as obsolete

SIL.WritingSystems.Tests/LdmlDataMapperTests.cs, SIL.WritingSystems/LdmlDataMapper.cs
Paratext got errors when trying to update an existing ldml file when the existing file was invalid because the content was not actually written to disk.
Added a try/catch block so invalid existing content will be ignored.
Added a Flush call to the writer to hopefully force the written data to disk and prevent this problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/553)
=> PTX-51943 ignore content of bad existing ldml file when writing new file

SIL.Core/Reporting/ExceptionHelper.cs
This is extremely helpful in making a precise try...catch if the error cannot be reproduced but needs to be suppressed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/561)
=> Report exact class of exception in crash reports

Palaso.DictionaryServices.Tests/Model/LexEntryTests.cs, Palaso.DictionaryServices/Model/LexEntry.cs
these 2 parts of LexEntry currently return stuff for the definition, hard coded. This allows you to pass in a bool to specify what the meaning field is (true: definition, false: gloss)
used by WeSay GatherWordsBySemanticDomains
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/559)
=> changes to allow gloss meaning field in WeSay

SIL.Core/Xml/XmlUtils.cs
Renamed GetManditoryAttributeValue() to GetMandatoryAttributeValue().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/557)
=> [API] Fix typo in method name and obsolete old spelling

Palaso.Lift.Tests/Parsing/ParserTests.cs, Palaso.Lift/Parsing/LiftMultiText.cs
WS-451 this causes WeSay to fail to load a project and exit
fix makes alternative an empty string instead of null text object
TryGetValue only fails if there is no text in the <span> or <text>
alternative = new LiftString(); creates a LiftString with Text = null
so alternative.Text.Length throws an exception
Also adds a test to comfirm that empty spans pass parsing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/564)
=> empty spans in empty text cause parsing to fail

SIL.Windows.Forms.Tests/ImageToolbox/ImageGallery/ImageCollectionTests.cs, SIL.Windows.Forms.Tests/ImageToolbox/ImageGallery/ImageIndexLayoutTests.cs, SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageIndexReader.cs, SIL.Windows.Forms/SIL.Windows.Forms.csproj
When you export a cell in Excel that has items separated by a comma, it sticks quotes around it. We want to ignore those quotes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/567)
=> Cope with excel-exported csv cells in image index

SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageCollection.cs, SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageCollectionManager.cs
Previously, a failure would make the whole image gallery fail. With this, it will still load other indexes and keep as many of the bad index lines as it was able to parse before failing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/568)
=> Handle a problem loading an image index gracefully

LanguageData.Tests/GetAndCheckSourcesTests.cs, LanguageData/GetAndCheckSources.cs
The failure is caused by www.ethnologue.com's relatively recent
paranoia about Denial Of Service attacks.  The Mono WebClient code
cannot cope with the defense mechanism.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/569)
=> Exclude a test that always fails on Linux

LanguageData.Tests/GetAndCheckSourcesTests.cs, LanguageData/GetAndCheckSources.cs
www.ethnologue.com's has apparently moved their data files recently
(like today?).  These new URLs (as reported by wget) seem to work okay.
The older URLs were failing on Linux but working on Windows earlier.
This also restores the test that was excluded earlier today.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/570)
=> Fix a test that started failing on Linux

SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageGalleryControl.cs, SIL.Windows.Forms/app.config
... because app.config doesn't get used by the clients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/571)
=> Make new collection list via code instead of app.config

SIL.Windows.Forms.Tests/Progress/LogBox/LogBoxTests.cs
Building libpalaso for Linux on the master branch has been hanging on this test.  It seems to pass okay for Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/574)
=> Disable a test hanging on TeamCity for Linux

Palaso.Tests/IO/FileUtilsTests.cs, Palaso.Tests/reporting/ErrorReportTests.cs, Palaso/IO/FileUtils.cs
enable some windows specific tests that were disabled because
Platform should be "Win" not "Windows"
add to StripFilePrefix tests to check windows path handling
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/573)
=> allows StripFilePrefix to handle windows paths

SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs
* Handled Index was outside the bounds of the array
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/575)
=> Fix LT-18647: Restoring (Maba) project leads to crash

Palaso.MSBuildTasks/GenerateReleaseArtifacts.cs
By setting Release=false we won't stamp the markdown file and will
set the stability flag in the changelog to UNRELEASED.
Also allow empty lines in markdown file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/577)
=>  Allow to create release artifacts for pre-release

SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageCollectionManager.cs
This was messing up build agents. Oh, the shame...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/581)
=> Don't show error  ui during unit tests

Palaso.DictionaryServices.Tests/Lift/LiftRepositoryTests.cs, Palaso.DictionaryServices/Lift/LiftDataMapper.cs, Palaso.DictionaryServices/LiftLexEntryRepository.cs, Palaso.Lift/LiftDataMapper.cs
this allows WeSay to choose whether to copy glosses or not
depending on which is the meaning field
part of the fix for WS-465
If you use LiftDataMapper you will now need to call Init() on it after constructing it.
As far as I can tell (ie from some quick project searches on github) the only other thing apart from WeSay that uses it is Solid, which I can fix once this gets to master. I don't know if PT uses it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/579)
=> separate init of LiftDataMapper from constructor

SIL.Core.Tests/IO/RobustFileTests.cs, SIL.Core/IO/RobustFile.cs
See https://issues.bloomlibrary.org/youtrack/issue/BL-5191 for an
example of this actually happening.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/588)
=> Fix RobustFile.Copy to handle empty files without crashing

SIL.Windows.Forms.Keyboarding.Tests/WindowsKeyboardControllerTests.cs, SIL.Windows.Forms.Keyboarding/KeyboardController.cs
* Uninstalling Keyman updating your linux distro
or other yet undiscovered things could result in ldml
files containing unusable keyboard adapters. Don't crash.
* Set most Windows IME tests to be ignored if the system is
not configured to run them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/591)
=> Do not crash if no compatible adapters are found

SIL.DictionaryServices/Model/LexEntry.cs
I missed an API that needed to be put in with the earlier changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/595)
=> missed GetToolTipText()

LanguageData/GetAndCheckSources.cs
This fixes some test failures that are happening today.  The
downloaded data contained one line in the middle consisting of
a single tab character.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/599)
=> Make code more robust in handling downloaded data

Palaso.TestUtilities/Palaso.TestUtilities.csproj, Palaso.TestUtilities/Providers/ReproducibleDateTimeProvider.cs, Palaso.TestUtilities/Providers/ReproducibleGuidProvider.cs, Palaso/Palaso.csproj, Palaso/Providers/BaseProvider.cs, Palaso/Providers/DateTimeProvider.cs, Palaso/Providers/GuidProvider.cs
Together with `ReproducibleDateTimeProvider` and `ReproducibleGuidProvider` this helps in testing by allowing to get specific date/time or GUID in the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/602)
=> Add GuidProvider and DateTimeProvider

SIL.Windows.Forms/Progress/LogBox.cs
See https://issues.bloomlibrary.org/youtrack/issue/BL-5619.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/613)
=> Prevent crash when saving to clipboard (on Windows)

SIL.Windows.Forms/ImageToolbox/OpenFileDialogWithViews.cs, SIL.Windows.Forms/SIL.Windows.Forms.csproj, SIL.Windows.Forms/packages.config
This uses the GTK dialog on Linux/Mono while still using the normal
.Net dialog on Windows.  Both Paratext and FieldWorks have switched
to doing this in their code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/614)
=> Change OpenFileDialogWithViews to use DialogAdapters

Palaso.Tests/Palaso.Tests.csproj, Palaso.Tests/UsbDrive/Linux/UDiskDeviceTests.cs, Palaso.Tests/UsbDrive/Linux/UDisksTests.cs, Palaso.Tests/packages.config, PalasoUIWindowsForms/PalasoUIWindowsForms.csproj
Non-strongname builds on Linux only work when we add a reference to
NDesk.DBus to Palaso.Tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/615)
=> Fix Linux non-strongname builds

SIL.WritingSystems.Tests/LdmlContentForTests.cs, SIL.WritingSystems.Tests/Migration/LdmlInFolderWritingSystemRepositoryMigratorTests.cs, SIL.WritingSystems/DefinitionBase.cs, SIL.WritingSystems/LdmlDataMapper.cs, SIL.WritingSystems/Migration/WritingSystemsLdmlV2To3Migration/LdmlVersion2MigrationStrategy.cs
* standard collation isn't saved to .ldml so re-populate it on
the load if there is no collations present
* handful of code cleanup changes
* Make number element for migrated ldml2 files match the
ldml .dtd order
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/616)
=> Fix WritingSystem to always have a DefaultCollation

SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageCollection.cs, SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageCollectionManager.cs
The information for handling this perhaps should be in the index file, but
even that would require code changes.  It is probably best not to force
users around the world into another 300MB download.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/619)
=> Fix Art Of Reading Search to handle country subdirectories.

SIL.Windows.Forms/ImageToolbox/OpenFileDialogWithViews.cs, SIL.Windows.Forms/SIL.Windows.Forms.csproj, SIL.Windows.Forms/packages.config
This reverts commit 236a4c5109f909ee4de93db99a62bcdd4391f44b.
This is being reverted for the moment because Bloom 4.0 does not want this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/621)
=> Revert "Change OpenFileDialogWithViews to use DialogAdapters"

SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorDialog.cs, SIL.Windows.Forms/Miscellaneous/FormUsingPortableClipboard.cs, SIL.Windows.Forms/Miscellaneous/PortableClipboard.cs, SIL.Windows.Forms/SIL.Windows.Forms.csproj
Subclassing Form reduces the duplication of boilerplate code.
I encountered some strange problems which may reflect bugs in Mono, with box.SelectionStart + box.SelectionLength pointing past the end of the text, resulting in an exception being thrown.  So I also added code to check that situation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/630)
=> Tweak using PortableClipboard for dialog textboxes

SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardSwitchingAdapter.cs
* Don't crash if a client tries to use a keyman
keyboard that is not associated with a language
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/632)
=> Guard against null values

SIL.BuildTasks/UnitTestTasks/TestTask.cs
"The standard error stream is the default destination for
error messages and other diagnostic warnings."
By default log the message as it is most likely a warning.
If the stderr message includes error, crash or fail then log it as an
error and investigate. Change this if it is too broad.
This addresses [issue 635](https://github.com/sillsdev/libpalaso/issues/635)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/636)
=> Log stderr as message by default in unit tests

SIL.Core/PlatformUtilities/Platform.cs, SIL.Core/SIL.Core.csproj, SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj, SIL.Windows.Forms.Keyboarding/packages.config, SIL.Windows.Forms/SIL.Windows.Forms.csproj, SIL.WritingSystems/SIL.WritingSystems.csproj
This fixes an issue with the Platform class not working properly because it was using the "RuntimeInformation" API. When targeting .NET Framework, "RuntimeInformation" is hardcoded to always return Windows for the current platform.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/650)
=> Remove dependency on System.Runtime.InteropServices.RuntimeInformation

SIL.Core/PlatformUtilities/Platform.cs
Fixes my stupid typo on Platform.IsLinux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/655)
=> Fix Platform.IsLinux on .NET Standard

SIL.Archiving.Tests/IMDI30Tests.cs, SIL.Archiving/IMDI/Schema/IMDI_3_0.cs
Angle brackets around <Unknown> were preventing the use of the item from the controlled vocabulary
Card: https://trello.com/c/9eUfILJG
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/646)
=> St382 reports blank Genre correctly by removing angle brackets

DistFiles/Palaso.en.tmx, SIL.Windows.Forms/ImageToolbox/AcquireImageControl.cs, SIL.Windows.Forms/ImageToolbox/OpenFileDialogWithViews.cs, SIL.Windows.Forms/SIL.Windows.Forms.csproj, SIL.Windows.Forms/packages.config
This is targeted initially at libpalaso-4.0.  It will need to be merged to master after we're all happy with it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/660)
=> Use GTK file dialogs for image chooser dialog on Linux

SIL.Windows.Forms.WritingSystems/LanguageLookupControl.Designer.cs, SIL.Windows.Forms.WritingSystems/LanguageLookupDialog.cs
Also a Linux fix to make it look more like Windows.
See https://silbloom.myjetbrains.com/youtrack/issue/BL-5753 for screenshots before and after this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/666)
=> Tweak layout of LanguageLookupControl for localizations

SIL.Media/AlsaAudio/AlsaAudioDevice.cs
Short reads are not an error, just a reality at times.  (I should have realized this when I wrote the code a few years ago.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/671)
=> Handle Linux sound recording better

SIL.Windows.Forms.WritingSystems/LanguageLookupControl.Designer.cs
This recenters it vertically on the textbox control next to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/679)
=> Adjust checkbox location in language lookup control

SIL.Windows.Forms/ImageToolbox/AcquireImageControl.cs
This may look like a hack, but it's the only solution I've come up with after looking at this for probably more than two days total.  And it works in my testing...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/681)
=> Tweak SWF image tool use of GTK file chooser on Linux

SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageGalleryControl.Designer.cs, SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageGalleryControl.cs
This occurs in the Art of Reading image chooser control.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/684)
=> Use "Bahasa Indonesia" for the language name, not "Indonesia"

SIL.Windows.Forms.Scripture/VerseControl.Designer.cs, SIL.Windows.Forms.Scripture/VerseControl.cs, SIL.Windows.Forms.Tests/SuperToolTip/SuperToolTipTestForm.Designer.cs, SIL.Windows.Forms.WritingSystems/WSFontControl.Designer.cs, SIL.Windows.Forms.WritingSystems/WSTree/WritingSystemTreeView.Designer.cs, SIL.Windows.Forms/FlexibleMessageBox.cs, SIL.Windows.Forms/FolderBrowserControl/FolderBrowserControl.cs, SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageGalleryControl.Designer.cs, SIL.Windows.Forms/Miscellaneous/UserRegistrationDialog.Designer.cs, SIL.Windows.Forms/Progress/ProgressDialog.cs, SIL.Windows.Forms/Reporting/ProblemNotificationDialog.Designer.cs
This creates greater consistency since VS now uses "Segoe UI" as its
default font, and the majority of controls in libpalaso already use it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/690)
=> Replace "Microsoft Sans Serif" with "Segoe UI"

SIL.BuildTasks/UnitTestTasks/TestTask.cs
Some GDK warnings contain the word 'failure' and therefore were
reported as errors previously.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/691)
=> Report GDK warnings as warnings

Palaso.Tests/IO/FileLocatorTests.cs, Palaso/IO/FileLocator.cs, SIL.Archiving/ArchivingPrograms.cs
RAMP installs in /opt/RAMP/ramp. LocateInProgramFiles() previously
didn't check subdirectories when running on Linux and so didn't find
RAMP even when installed. This change optionally checks in subdirectories.
This kind of changes API (or at least behavior) on Linux, but this
probably doesn't have noticeable effects for most projects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/698)
=> [linux] Fix location detection for RAMP (LT-16894)

SIL.Windows.Forms.WritingSystems/LanguageLookupControl.Designer.cs, SIL.Windows.Forms.WritingSystems/ScriptsAndVariantsDialog.Designer.cs, SIL.Windows.Forms.WritingSystems/ScriptsAndVariantsDialog.cs
The default Mono layout of the dialog left much to be desired.  See
https://silbloom.myjetbrains.com/youtrack/issue/BL-5736 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/708)
=> Tweak title of Script and Variant dialog, fix for Linux

SIL.Windows.Forms/Miscellaneous/X11.cs, SIL.Windows.Forms/SIL.Windows.Forms.csproj
This allows to set the WM_CLASS X11 property. This is needed to set the
icon and name on Ubuntu 18.04. This change is part of the fix for
LT-19085.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/701)
=> [Linux] Add SetWmClass method

SIL.Archiving/RampArchivingDlgViewModel.cs, SIL.Core.Desktop/IO/FileLocator.cs
* Handled the Ramp 3.0 Package doesn't have languages.yaml
* Locate the ramp installer for 3.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/711)
=> Fix: LT-19077 Crash while trying to use Archive with RAMP 3.0

SIL.Core/Migration/FolderMigrator.cs
* avoid crashing and skip migrating the file.
* partially fixes LT-19152
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/719)
=> Report when trying to migrate an unrecognized file

SIL.WritingSystems.Tests/LdmlDataMapperTests.cs, SIL.WritingSystems/NumberingSystemDefinition.cs
Some old ldml files had defined empty custom
numbers in the character section and crashed
this fix will return the default latn instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/727)
=> Handle bad numbering system data more gracefully

SIL.Archiving/IMDI/IMDIArchivingDlgViewModel.cs
check for empty path before combining.
(Approved May 18 & 23 on a different pull request but never merged)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/732)
=> SP-1816 Crash archiving IMDI

SIL.TestUtilities/TemporaryFolder.cs
* This may fix the linux test failures by removing
an unnecessary move of an empty file.
* Use RobustFile for writing as well
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/737)
=> Improve TempLiftFile code

SIL.WritingSystems.Tests/LanguageLookupTests.cs, SIL.WritingSystems/LanguageLookup.cs
It's really the Unicode RIGHT SINGLE QUOTATION MARK in the language
data.  See https://silbloom.myjetbrains.com/youtrack/issue/BL-6339.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/741)
=> Handle Unicode 'apostrophe' in language lookup

SIL.Core.Desktop/IO/FileUtils.cs
The class name is `PathHelper`, not `PathHelpers`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/734)
=> Fix typo in Obsolete attribute

SIL.Archiving/Extensions.cs, SIL.Windows.Forms.Scripture/LabelButton.cs, SIL.Windows.Forms.Scripture/VerseControl.cs, SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataDisplayControl.cs, SIL.Windows.Forms/Extensions/ToolStripExtensions.cs, SIL.Windows.Forms/ImageToolbox/Cropping/ImageCropper.cs, SIL.Windows.Forms/Widgets/BitmapButton.cs
Also use TextRenderer.MeasureText instead of Graphics.MeasureString.  This
change is motivated by a recent crash in Bloom caused by trying to measure
and draw a non-Roman script string.  TextRenderer successfully draws that
string.  See https://silbloom.myjetbrains.com/youtrack/issue/BL-6370.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/753)
=> Use TextRenderer.DrawText instead of Graphics.DrawString

SIL.Archiving/IMDI/Schema/IMDIDescription.cs, SIL.Archiving/IMDI/Schema/IMDI_3_0.cs
The IMDI xsd specifies the order of child elements in various xsd:sequence elements that include Description. This change puts them in the right order in our export.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/756)
=> Put Description elements in the right order in parent

GlobalAssemblyInfo.cs, GlobalAssemblyInfo.props, SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs, SIL.WritingSystems.Tests/WritingSystemDefinitionPropertyTests.cs, SIL.WritingSystems/GlobalWritingSystemRepository.cs, SIL.WritingSystems/IWritingSystemFactory.cs, SIL.WritingSystems/LdmlInFolderWritingSystemFactory.cs, SIL.WritingSystems/LocalWritingSystemRepositoryBase.cs, SIL.WritingSystems/SldrWritingSystemFactory.cs, SIL.WritingSystems/WritingSystemDefinition.cs, SIL.WritingSystems/WritingSystemFactory.cs, SIL.WritingSystems/WritingSystemFactoryBase.cs, build/Palaso.proj
- Allow to set path for GlobalWritingSystemRepo in unit tests
Get the default path to the GlobalWritingSystemRepo from a field. This allows unit tests to set the field through reflection so that they can have the global writing system repo in a defined state. This is necessary when testing S/R where changes in the global WS store might cause additional commits to appear.
- Don't update timestamp when copying to global store
Updating DateModified causes extra commits when doing a S/R because the WS gets copied from the global to the local store, introducing a modified timestamp and thus a change. This change adds an optional flag to `IWritingSystem.Create()` whether to clone the Id of the writing system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Fix and improve global writing system store

SIL.WritingSystems/IcuRulesCollator.cs, SIL.WritingSystems/Sldr.cs
This change implements a hack to dispose the RuleBasedCollators
we create when shutting down the SLDR. Disposing of the collators
is necessary to prevent a crash when running tests in LfMerge (and
potentially anywhere else we use collators).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/778)
=> Dispose RuleBasedCollators

SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs, SIL.WritingSystems/LdmlInFolderWritingSystemRepository.cs
Even if the file doesn't yet exist we shouldn't update the timestamp
when we save the file. This allows to copy the ws from the local to
the global repo without creating changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/781)
=> Don't update ws timestamp if nothing changed

SIL.WritingSystems.Tests/LdmlContentForTests.cs, SIL.WritingSystems.Tests/Migration/LdmlInFolderWritingSystemRepositoryMigratorTests.cs, SIL.WritingSystems/LdmlDataMapper.cs
* Addresses bugs found by Flex users (LT-19466)
* On Migration create default SystemCollation if
the default SystemCollation for the langage is invalid
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/783)
=> Stop creating invalid SystemCollations

DistFiles/Palaso.es.tmx, DistFiles/Palaso.fr.tmx, SIL.Windows.Forms/SettingProtection/SettingProtectionDialog.Designer.cs, SIL.Windows.Forms/SettingProtection/SettingProtectionDialog.cs, SIL.Windows.Forms/SettingProtection/SettingsProtection.cs
Apps can now override the default password if needed and also specify the support page URL.
This should be 100% compatible with existing apps and not break anything. However, apps that ship their own localized versions of Palaso TMX file will want to fix any existing translations for SettingsProtection.PasswordNotice. (I rewrote the wording such that googling the new param 2 should still work -- even better than before -- but it might sound/look weird if the wording is not adjusted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/789)
=> Improved the password notice in the settings protection dialog.

SIL.Windows.Forms.Tests/ClearShare/MetadataTests.cs, SIL.Windows.Forms/ClearShare/CreativeCommonsLicense.cs, SIL.Windows.Forms/ClearShare/LicenseInfo.cs, SIL.Windows.Forms/ClearShare/MetaData.cs
This requirement was brought to our attention by a Bloom user (BL-6880 or
https://community.software.sil.org/t/changing-cc-version-in-license-notice/1726)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/793)
=> Abbreviate Creative Commons as "CC " instead of "CC-"

SIL.WritingSystems.Tests/IetfLanguageTagTests.cs, SIL.WritingSystems.Tests/StandardSubtagsTests.cs, SIL.WritingSystems/IetfLanguageTag.cs, SIL.WritingSystems/LdmlInXmlWritingSystemRepository.cs, SIL.WritingSystems/StandardSubtags.cs
* Scripts added by SLDR from the languageTags.json
were not retaining their private use identity
* Also cleaned up some comments and added some new
comments relating to the private use convention
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/792)
=> Fix private use scripts showing up as normal

SIL.Windows.Forms.WritingSystems.Tests/WritingSystemSetupPMTests.cs, SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs
* If a language tag is using an implicit script it should
not push the user into the Script/Region/Variant options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/795)
=> Do not show Script/Region/Variant for Implicit Script

SIL.WritingSystems.Tests/LdmlDataMapperTests.cs, SIL.WritingSystems/LdmlDataMapper.cs
* The code to remove matching collations was buggy and removed
any unknown collation from the old content.
* Also update the remarks to point to the specific revision
that this library was built against.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/796)
=> Fix a bug where many collations were not round tripped

SIL.Windows.Forms/Reporting/ExceptionReportingDialog.cs
* ExceptionHandler.Init(true) will include close box
in all UI versions of error dialog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/799)
=> BL-5852 Add optional close box

SIL.Lexicon/ProjectLexiconSettingsWritingSystemDataMapper.cs, SIL.WritingSystems.Tests/Migration/LdmlInFolderWritingSystemRepositoryMigratorTests.cs
* Languages are referred to by different names in
different areas regardless of their private use designation
* Change code to store the users preferred language name and
verify that this happens during migration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/811)
=> Do not restrict custom language name to private use

SIL.Windows.Forms.Scripture/VerseControl.cs
When the code was moved from Paratext to Libpalaso a change was done to how text was measured that made an existing adjustment to the size no longer needed (adjustment is now causing text to look squished together).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/815)
=> PTX-17575 fix problem with book drop down display of search match

SIL.WritingSystems.Tests/GlobalWritingSystemRepositoryTests.cs, SIL.WritingSystems.Tests/IetfLanguageTagTests.cs, SIL.WritingSystems.Tests/Migration/IetfLanguageTagCleanerTests.cs, SIL.WritingSystems.Tests/Migration/LdmlInFolderWritingSystemRepositoryMigratorTests.cs, SIL.WritingSystems/GlobalWritingSystemRepository.cs, SIL.WritingSystems/IetfLanguageTag.cs, SIL.WritingSystems/LdmlInFolderWritingSystemFactory.cs, SIL.WritingSystems/LdmlInFolderWritingSystemRepository.cs, SIL.WritingSystems/Migration/IetfLanguageTagCleaner.cs, SIL.WritingSystems/Migration/LdmlMigrationInfo.cs, SIL.WritingSystems/Migration/WritingSystemsLdmlV2To3Migration/LdmlVersion2MigrationStrategy.cs, SIL.WritingSystems/WritingSystemDefinition.cs, SIL.WritingSystems/WritingSystemRepositoryBase.cs
* Stop treating the Canonicalized LanguageTag as a stable identifier
* Allow for multiple writing systems in the repository to have the same
Canonicalized LanguageTag data
* Update the tag cleaner to handle some of the clean-up that
Canonicalize did.
* Don't rename .ldml files if a writing system id has changed
but is still equivalent
* Don't canonicalize language tags on WritingSystemDefinition creation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/817)
=> Change WritingSystemRepository interaction with the Id field

SIL.WritingSystems.Tests/LdmlDataMapperTests.cs, SIL.WritingSystems/LdmlDataMapper.cs
* Past bugs have written out duplicate collation
elements of the same type. We saw files in the
wild with this data so we'll protect against crashes
when loading it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/822)
=> Do not crash if .ldml has bad collation data

SIL.WritingSystems.Tests/IetfLanguageTagTests.cs, SIL.WritingSystems.Tests/LanguageLookupTests.cs, SIL.WritingSystems/LanguageInfo.cs, SIL.WritingSystems/LanguageLookup.cs, SIL.WritingSystems/SingleStringToListOfStringConverter.cs, SIL.WritingSystems/Sldr.cs
* Add Country match into sort
* Add Match on any Name into sort
* Include iana names into data considered by the lookup
* Add class to handle loading a single json string into
a string collection (to handle the iana data)
* Add debugging help to LanguageInfo
* Modernize Exception handling in IetfLanguageTagTests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/820)
=> Improve LanguageLookup to work better with new langtags data

SIL.Core/Migration/FolderMigrator.cs
Getting "The file 'C:\ProgramData\SIL\WritingSystemStore\bn.ldml.bad' already exists" exception if there is a problem migrating a writing system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/825)
=> Fix exception when there is a problem migrating writing systems

SIL.WritingSystems.Tests/LdmlDataMapperTests.cs, SIL.WritingSystems/LdmlDataMapper.cs, SIL.WritingSystems/WritingSystemChangeLog.cs
At least one user was found to have a duplicated font in
their ldml data (we don't know how it was duplicated)
* Throw an exception with the actual font name and .ldml file
when a duplicate is found during the parse.
* Add a unit test to verify this.
* Fix a typo that I noticed in a random file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/827)
=> Report useful error from bad font content in ldml

SIL.Lexicon.Tests/ProjectLexiconSettingsWritingSystemDataMapperTests.cs, SIL.Lexicon/ProjectLexiconSettingsWritingSystemDataMapper.cs
If all WS's have been removed from a project,
but there are still global settings that apply to all WS's,
preserve those settings.
Needed for https://jira.sil.org/browse/LT-19632
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/830)
=> Preserve Writing Systems Settings

SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs
This is mainly for (massive) performance improvement, but it also avoids a race condition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/832)
=> Avoid getting the list of recording devices twice when updating.

SIL.WritingSystems.Tests/GlobalWritingSystemRepositoryTests.cs, SIL.WritingSystems.Tests/Migration/LdmlInFolderWritingSystemRepositoryMigratorTests.cs, SIL.WritingSystems/GlobalWritingSystemRepository.cs
While writing system ids in general were already case insensitive, the global writing system repository used two fields that compared by case. This is a problem on Linux where the file system is case
sensitive. This change modifies `GlobalWritingSystemRepository` to use case-insensitive dictionaries to store the ws ids. This fixes LF-297.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/838)
=>  Fix global WS repo to compare ws ids case insensitive (LF-297) 

SIL.Core.Tests/Acknowledgements/AcknowledgementsProviderTests.cs, SIL.Core.Tests/Email/LinuxEmailProviderTests.cs, SIL.Core.Tests/Email/MailToEmailProviderTests.cs, SIL.Core.Tests/Email/ThunderbirdEmailProviderTests.cs, SIL.Core.Tests/IO/FileLocationUtilitiesTests.cs, SIL.Core.Tests/IO/PathHelperTests.cs, SIL.Core.Tests/PlatformUtilities/PlatformTests.cs, SIL.TestUtilities/NUnitExtensions/Does.cs, SIL.TestUtilities/NUnitExtensions/OneTimeSetUpAttribute.cs
These classes allow to use NUnit 3 syntax while still using NUnit 2. This will then allow to switch to NUnit 3 without requiring code changes.
Also adjust SIL.Core.Tests for NUnit 3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/836)
=>  Add classes to increase compatibility with NUnit 3 

SIL.Lexicon.Tests/ProjectLexiconSettingsDataMapperTests.cs, SIL.Lexicon.Tests/ProjectLexiconSettingsWritingSystemDataMapperTests.cs, SIL.Lexicon.Tests/UserLexiconSettingsWritingSystemDataMapperTests.cs, SIL.TestUtilities.Tests/NUnitExtensions/IsTests.cs, SIL.TestUtilities.Tests/NUnitExtensions/XmlEquatableConstraintTests.cs, SIL.TestUtilities.Tests/SIL.TestUtilities.Tests.csproj, SIL.TestUtilities/NUnitExtensions/Is.cs, SIL.TestUtilities/NUnitExtensions/XmlEquatableConstraint.cs, SIL.TestUtilities/SIL.TestUtilities.csproj
- implement `XmlEquatableConstraint` class
- implement `Is.XmlEqualTo` method
- refactor `SIL.Lexicon.Tests` to use `XmlEqualTo`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/831)
=> [TestUtilities] Implement XmlEqualTo constraint for unit tests

SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs
* 2 UI desires are conflicting here:
1) update the Script and Variant label (to the right of the Script and Variant link)
with the language clicked on in the list view
2) keep script/region/variant info from the Script and Variant dialog when
returning to the main list view.
* At this point, we are making the first a priority. If the user selects their
language, then goes and adds more detail in the Script and Variant dialog,
they can click 'OK' in the outer dialog and keep all that info. But clicking on a
different language will reset that information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/841)
=> BL-7224 Give language lookup click priority

SIL.Windows.Forms.Tests/Progress/LogBox/LogBoxTests.cs, SIL.Windows.Forms/Progress/LogBox.cs
MaximumLength is now exposed so the client can set it (mainly to support testing).
The logic is in place (with passing unit tests) to truncate any message that would exceed the limit and output a special error message.
WIP: Failing (and very slow) test for the more interesting case where the default maximum is used. In this case, an access violation occurs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/845)
=> Made LogBox enforce the MaximumLength value

SIL.Core.Tests/Extensions/DateTimeExtensionTests.cs, SIL.Core/IO/FileLocationUtilities.cs, SIL.Core/Migration/FolderMigrator.cs, SIL.DblBundle/Text/TextBundle.cs, SIL.Lift.Tests/Merging/SynchronicMergerTests.cs, SIL.Lift/LiftSorter.cs, SIL.Windows.Forms.DblBundle/ProjectsListBase.cs, SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs, SIL.WritingSystems/GlobalWritingSystemRepository.cs, SIL.WritingSystems/LdmlInFolderWritingSystemRepository.cs
With Mono 6 we get a new set of failing tests. This change fixes or ignores those tests.
- `SynchronicMergerTests`: this test should be ignored on Linux since it is possible to move locked files 
on Linux.
- `DateTimeExtensionTests`: it seems that Mono 6 shares the implementation with .NET Core which 
checks that the timezone offset is within plus or minus 14. Adjusted the tests.
- `LdmlInFolderWritingSystemRepositoryTests`: The tests were dependent on the order of files that 
`Directory.GetFiles` returned. Since this can result in hard-to-reproduce error reports we now sort
the list of LDML files before we process them.
- `LdmlInFolderWritingSystemRepositoryMigratorTests`: failing tests caused by another case of 
differing sort order. Add sorting to all relevant instances of …
=> Fix or ignore tests that fail on Linux

SIL.Windows.Forms.DblBundle/SIL.Windows.Forms.DblBundle-Designer.csproj, SIL.Windows.Forms.DblBundle/packages.config, SIL.Windows.Forms.WritingSystems/SIL.Windows.Forms.WritingSystems-Designer.csproj, SIL.Windows.Forms.WritingSystems/packages.config
The designer projects still had references to L10NSharp.tmx instead
of L10NSharp. Also `packages.config` file was missing for two
designer projects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/856)
=> Replace remaining references to L10NSharp.tmx

SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorDialog.cs
See https://issues.bloomlibrary.org/youtrack/issue/BL-7381 for the motivation behind this change.  I think subclassing the dialog is a bit cleaner than making the original dialog more complicated.  And what Bloom wants to add here may be too Bloom-specific to be of interest to other projects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/859)
=> Allow easier subclassing of metadata dialog

SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs
Prevent bad input language settings from creating errors when initializing keyboards
This may be related to InKey keyboards - some systems have problems when InKey is running and Paratext is started.
The actual error is occurring in .Net code, so just needed to try accessing the value causing the error and ignore input languages that fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/858)
=> PTX-18778 Prevent errors when initializing keyboards

SIL.Windows.Forms.GeckoBrowserAdapter/GeckoFxWebBrowserAdapter.cs, SIL.Windows.Forms.GeckoBrowserAdapter/WebThumbnailViewer.cs, SIL.Windows.Forms/HtmlBrowser/IWebBrowser.cs, SIL.Windows.Forms/HtmlBrowser/WinFormsBrowserAdapter.cs, SIL.Windows.Forms/HtmlBrowser/XWebBrowser.Designer.cs, SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageGalleryControl.Designer.cs, SIL.Windows.Forms/ImageToolbox/ImageGallery/ThumbnailViewer.cs, SIL.Windows.Forms/Miscellaneous/SILAboutBox.Designer.cs, SIL.Windows.Forms/ReleaseNotes/ShowReleaseNotesDialog.Designer.cs, SIL.Windows.Forms/Widgets/HtmlLabel.Designer.cs
Tom Hindle has pointed out that GeckoWebBrowser objects should be disposed.  These are used
by various dialogs and controls in libpalaso under SIL.Windows.Forms, albeit indirectly through
SIL.Windows.Forms.GeckoBrowserAdapter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/861)
=> Dispose of GeckoWebBrowser objects properly (20190911)

SIL.Windows.Forms/SIL.Windows.Forms-Designer.csproj
When we replaced `TagLibSharp-patched` with `TagLibSharp` we forgot
to remove `TagLibSharp-patched` from the designer project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/866)
=> Remove obsolete package reference from designer project

CHANGELOG.md, SIL.Windows.Forms.Keyboarding/ILRepack.targets, SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj, SIL.Windows.Forms/ILRepack.targets, SIL.Windows.Forms/SIL.Windows.Forms-Designer.csproj, SIL.Windows.Forms/SIL.Windows.Forms.csproj, SIL.Windows.Forms/packages.config
We have some unsigned dependencies that we sign on-the-fly during
the build. However, this makes it difficult for clients to use
the library. This change uses ILRepack to merge these dependent
assemblies.
NOTE: there is still a similar problem with `ibusdotnet.dll`. We can't
merge that because it appears in the API. The solution here will be
to create a nuget package version with signed `ibusdotnet.dll`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/869)
=> Merge unsigned assemblies (Fixes #865)

SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
This time nuget.org complained about a different project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/872)
=> User portable PDB file for SIL.WIndows.Forms.Keyboarding

CHANGELOG.md, SIL.Media/SIL.Media.targets
The irrKlang.NET4.dll comes in different versions for 32- and 64-bit.
Copying it to the respective directory in the `lib` subdirectory of
the client's output directory allows the client application to pick
up the correct version at runtime.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/876)
=> Fix missing irrKlang.NET4 exception

CHANGELOG.md, SIL.Core.Tests/IO/PathUtilitiesTests.cs, SIL.Core.Tests/Reporting/ExceptionHandlerTests.cs, SIL.Core/Reporting/ConsoleExceptionHandler.cs, SIL.Core/Reporting/ExceptionHandler.cs, SIL.Linux.Logging/SyslogExceptionHandler.cs, SIL.Windows.Forms/Reporting/WinFormsExceptionHandler.cs
- Deprecate `ExceptionHandler.Init()`. Clients should use `ExceptionHandler.Init(ExceptionHandler)` 
instead.
- Move `HandleUnhandledException()` to base class
- Add some unit tests
In `ExeceptionHandler.Init()` so far we used reflection to load `WinFormsExceptionHandler` from `SIL.Windows.Forms.dll`. If we couldn't load that assembly we used `ConsoleExceptionHandler` instead. While this is convenient for the client it can hide problems when the client partially updates to use a newer version of the libpalaso assemblies. In particular the client app seems to work unless it gets an exception, in which case it still works but doesn't show the expected green screen for error reporting. Using `ExceptionHandler.Init(new WinFormsExceptionHandler())` instead will allow to catch the …
=> Improvements in ExceptionHandler

SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs, SIL.Windows.Forms.WritingSystems/LanguageLookupDialog.cs, SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs, SIL.WritingSystems.Tests/LanguageLookupTests.cs, SIL.WritingSystems/LanguageLookup.cs
For example, when asked to choose a language, users can be confused by
seeing "en-Brai", "en-Desr", "en-Dupl", and "en-Shaw" in addition to "en"
in the list.  See https://issues.bloomlibrary.org/youtrack/issue/BL-7641.
The dialog has a means to manually add a script to the tag if it is
needed.
This change does not involve any UI or the need for any project to change
its code unless it wants this new functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/881)
=> Add ability to exclude language tags with scripts

SIL.Core/Keyboarding/UnsupportedKeyboardDefinition.cs, SIL.Windows.Forms.Keyboarding/KeyboardController.cs, SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardUtils.cs, SIL.WritingSystems.Tests/LdmlContentForTests.cs, SIL.WritingSystems.Tests/LdmlDataMapperTests.cs, SIL.WritingSystems/LdmlDataMapper.cs
* Don't crash if two unsupported keyboards are
found in an ldml file
* Support round tripping unsupported keyboards to ldml
* Refactor NullKeyboard functionality to allow detecting an
unsupported keyboard and round tripping
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/886)
=> Handle multiple unsupported keyboards

SIL.Archiving/SIL.Archiving-Designer.csproj, SIL.Media.Tests/SIL.Media.Tests-Designer.csproj, SIL.Media/SIL.Media-Designer.csproj, SIL.Windows.Forms.DblBundle/SIL.Windows.Forms.DblBundle-Designer.csproj, SIL.Windows.Forms.GeckoBrowserAdapter/SIL.Windows.Forms.GeckoBrowserAdapter-Designer.csproj, SIL.Windows.Forms.Scripture/SIL.Windows.Forms.Scripture-Designer.csproj, SIL.Windows.Forms.Tests/SIL.Windows.Forms.Tests-Designer.csproj, SIL.Windows.Forms.WritingSystems/SIL.Windows.Forms.WritingSystems-Designer.csproj, SIL.Windows.Forms/SIL.Windows.Forms-Designer.csproj, TestApps/FastSplitterTest/FastSplitterTest-Designer.csproj, TestApps/ReportingTest/Reporting.TestApp-Designer.csproj, TestApps/SIL.Email.TestApp/SIL.Email.TestApp-Designer.csproj, TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp-Designer.csproj, TestApps/TestAppKeyboard/TestAppKeyboard-Designer.csproj
The nuget symbol packages for some projects fail validation after
uploading to nuget.org with the message: "The uploaded symbols
package contains one or more pdbs that are not portable." The
.csproj files specifies to use portable pdbs, but the Designer.csproj
files did not. Hopefully changing those as well will allow all
symbol packages to upload successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/893)
=> Hopefully fix symbol package for some projects

SIL.Windows.Forms.WritingSystems.Tests/LanguageLookupControlTests.cs, SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs, SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs, SIL.WritingSystems/LanguageInfo.cs
* going into LanguageLookupDialog with SRV data doesn't
lose said data
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/896)
=> BL-8082/8097 Don't lose Script/Region/Variant info

SIL.Windows.Forms/ClearShare/WinFormsUI/ContributorsListControl.cs
If a role is not selected for the participant, a "reentrant call" exception may be thrown when setting focus on the role cell.
This solution was found on S.O. - https://stackoverflow.com/questions/5114668/why-is-my-bound-datagridview-throwing-an-operation-not-valid-because-it-results
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/898)
=> SP-2133: Crash when editing participant

SIL.Archiving.Tests/RampArchivingDlgViewModelTests.cs, SIL.Archiving/ArchivingDlg.cs, SIL.Archiving/IMDI/IMDIArchivingDlgViewModel.cs
Archive directory is being set to empty string instead of the selected directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/902)
=> SP-1816: Archive directory set to empty string

CHANGELOG.md, SIL.DblBundle.Tests/DBLMetadataTests.cs, SIL.DblBundle.Tests/Text/TextBundleTests.cs, SIL.DblBundle/DblMetadata.cs, SIL.DblBundle/Text/DblTextMetadata.cs
This is needed to allow Vessel to use a non-file-based persistence layer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/905)
=> Added DblMetadata.Load overload to allow deserialization from a TextReader.

SIL.WritingSystems.Tests/IetfLanguageTagTests.cs, SIL.WritingSystems/IetfLanguageTag.cs
* Invalid private use codes should cause a false return
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/915)
=> Add missing validation to TryGetVariantSubtags

SIL.WritingSystems/GlobalWritingSystemRepository.cs, SIL.WritingSystems/LdmlInFolderWritingSystemRepository.cs, SIL.WritingSystems/WritingSystemRepositoryBase.cs
When we save a writing system, we are supposed to preserve any data we don't care about, typically from the SLDR. If the WS has already been saved in the destination folder, we merge changes into the previously saved version. New writing systems that are based on an SLDR template are supposed to have a Template field set, which is used to copy the SLDR version before we look for an existing Save. But this only works for the first place we save a new writing system, since we clear it after using it. I'm not sure why we clear it, so hesitated to change that. A more robust fix, anyway, seems to be that if we are writing a new WS and don't already know of a template to copy and there is a corresponding template in the SLDR, just use it.
---
This change is [<img …
=> Use SLDR template when making new WS (LT-20022)

SIL.Core/Acknowledgements/AcknowledgementsProvider.cs
* FW links oleaut32.dll to libViews.so (as discussed in FWNX-823).
* AcknowledgementsProvider crashes when Assembly.LoadFile opens
oleaut32.dll, saying System.BadImageFormatException: Invalid Image.
* This results in FW not showing any acknowledgements, as reported in
LT-20121.
--- 
Unfortunately I could not test or confirm this locally since I haven't managed to build libpalaso today. But hopefully it will work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/921)
=> Ignore oleaut32.dll in Acknowledgements

SIL.Core/Xml/XElementExtensions.cs, SIL.WritingSystems.Tests/GlobalWritingSystemRepositoryTests.cs, SIL.WritingSystems.Tests/LdmlDataMapperTests.cs, SIL.WritingSystems/CharacterSetDefinition.cs, SIL.WritingSystems/GlobalWritingSystemRepository.cs, SIL.WritingSystems/LdmlDataMapper.cs, SIL.WritingSystems/LdmlInFolderWritingSystemRepository.cs, SIL.WritingSystems/SldrWritingSystemFactory.cs, SIL.WritingSystems/WritingSystemFactory.cs
* ignores lists of exemplars with "extra" attributes like "draft" or "alt"
* if 2 lists of the same "type" happen to slip into the global SLDR,
it still won't crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/920)
=> LT-20124 Fix crash in reading LDML exemplars

SIL.WritingSystems/SldrWritingSystemFactory.cs
* If there is a ldml read error using the SLDR template
then bail and return the base create
Unit test skipped to avoid the need to mock receiving bad ldml from the internet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/922)
=> More work preventing crashes from bad ldml (LT-20125)

SIL.Windows.Forms/SIL.Windows.Forms.csproj, SIL.Windows.Forms/packages.config
Note that this version of DialogAdapters limits Geckofx use to Geckofx45
and before.  (DialogAdapters 1.6.* limit Geckofx use to Geckofx60 and
later!)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/919)
=> Update DialogAdapters package for mono5-sil compatibility

build/build, build/download-dependencies
* To make it easier to successfully figure out how to build the
project.
* Using some commands copied from CI.
* Not re-using TestBuild.sh. It has trouble presently from setting
RootDir. Other scripts may rely on TestBuild.sh being there,
receiving arguments in configuration,target order, and defaulting to
targets `Clean;Compile`.
* environ is not needed if mono 6 is installed to /usr.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/925)
=> Add Linux build and download-dependencies scripts

ExtractCopyright/Program.cs, Palaso.sln.DotSettings, SIL.Core.Desktop/Reporting/ErrorReport.cs, SIL.DblBundle.Tests/SIL.DblBundle.Tests.csproj, SIL.Lift/Validation/Validator.cs, SIL.Scripture.Tests/SIL.Scripture.Tests.csproj, SIL.Windows.Forms.DblBundle/SIL.Windows.Forms.DblBundle.csproj, SIL.Windows.Forms.Keyboarding/Linux/IbusCommunicator.cs, SIL.Windows.Forms.Keyboarding/Linux/XklEngine.cs, SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs, SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, SIL.Windows.Forms.WritingSystems/WSKeyboardControl.cs, SIL.Windows.Forms/ClearShare/CreativeCommonsLicense.cs, SIL.Windows.Forms/ImageToolbox/Cropping/ImageCropper.cs, SIL.Windows.Forms/Reporting/ProblemNotificationDialog.cs, SIL.WritingSystems/Sldr.cs
Environment.Version is supposed to return the version of the
common language runtime, not .NET. Also, for .NET Framework 4.5
and later, Microsoft does not recommend using Environment.Version
to determine the version, but instead recommends
"community-maintained" command-line tools that query the registry.
The registry query is tied to v4, so this will need to be rewritten for
.NET 5.0 at the latest (perhaps Microsoft will hide it again sooner).
* Label Environment.Version "CLR Version (deprecated)"
* Query the registry for the .NET (v4) Version
* Fix some warnings
This partially addresses https://jira.sil.org/browse/LT-19930
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpala …
=> LT-19930: Report correct .NET version (for 4)

SIL.Windows.Forms/Widgets/BetterLabel.cs
* Fixes LT-20131.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/929)
=> Prevent BetterLabel.OnSizeChanged recursion

SIL.Windows.Forms/ImageToolbox/AcquireImageControl.cs, SIL.Windows.Forms/SIL.Windows.Forms-Designer.csproj, SIL.Windows.Forms/SIL.Windows.Forms.csproj, SIL.Windows.Forms/packages.config, TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj, TestApps/SIL.Windows.Forms.TestApp/environ
This change makes use of the new DialogAdapters.Gtk2 nuget package. This can be swapped out by the client against the Gtk3-based DialogAdapters.
This change will fix the builds of the `feature/nuget` branch.
This change depends on the availability of `DialogAdapters.Gtk2` on nuget.org (cf. https://bitbucket.org/hindlemail/dialogadapters/pull-requests/5).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/937)
=> [feature/nuget] Use DialogAdapters.Gtk2

SIL.Core/Acknowledgements/AcknowledgementsProvider.cs
* On Linux, this is a symlink to libcom.so. An exception is thrown,
contributing to LT-20121.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/939)
=> Exclude ole32.dll from Acknowledgements

SIL.Windows.Forms/SIL.Windows.Forms.csproj, SIL.Windows.Forms/packages.config
This was already done on the feature/nuget branch, but is needed on master
as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/940)
=> Update DialogAdapters to DialogAdapters.Gtk2 0.1.9

CHANGELOG.md, SIL.Core/PlatformUtilities/Platform.cs, SIL.Core/Program/Process.cs, SIL.Windows.Forms.Keyboarding/KeyboardController.cs, SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardSwitchingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/GnomeShellIbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/GnomeShellIbusKeyboardSwitchingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/IUnityKeyboardSwitchingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardDescription.cs, SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardSwitchingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityIbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityIbusKeyboardSwitchingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityXkbKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityXkbKeyboardSwitchingAdaptor.cs
Ubuntu 18.04 changed the way how to switch keyboards. The previous
method of setting a dconf value is deprecated and no longer works.
Instead this is done by a DBus method call.
This change also adds a property to detect if the program runs in
a Gnome Shell, and fixes a bug where the wrong keyboard adaptor was
used in Ubuntu 18.04.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/949)
=> Fix keyboard switching on Ubuntu 18.04 (fixes #887)

Palaso.sln.DotSettings, SIL.Windows.Forms.Keyboarding.Tests/XkbKeyboardAdapterTests.cs, SIL.Windows.Forms.Keyboarding/Linux/XklConfigRegistry.cs
We already checked in most cases that we don't add the same
layout twice. However, in `ProcessLanguage` which adds the first
bunch of layouts we didn't check. It's not entirely clear why we
get the same layout twice (bug in Linux Mint?), but this change
deals with that case.
This PR is against the `feature/nuget` branch.
=> Check that we don't add duplicate layouts (LT-20288)

SIL.Windows.Forms/ClearShare/MetaData.cs
TagLib throws too many exceptions...
=> Prevent unknown image metadata from crashing programs

SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs, SIL.WritingSystems/LdmlInFolderWritingSystemRepository.cs, SIL.WritingSystems/LocalWritingSystemRepositoryBase.cs
* Fix Flex bug LT-20334
* Use the Id to index the global store
* Add some guards against extreme edge cases to avoid crashes
- This could result in failed updates of the global store
but that is more acceptable then crashing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/965)
=> Fix crashes updating global store with Id/LangTag mismatch

SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj, SIL.Windows.Forms.Keyboarding.Tests/packages.config, SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj, SIL.Windows.Forms.Keyboarding/packages.config, SIL.Windows.Forms.WritingSystems.Tests/SIL.Windows.Forms.WritingSystems.Tests.csproj, SIL.Windows.Forms.WritingSystems.Tests/packages.config, build/NuGet.targets
The new ibusdotnet version fixes the problem on Ubuntu 20.04 where ibus keyboards are not detected.
This change fixes #957.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/967)
=> Update ibusdotnet (#957)

Palaso.sln.DotSettings, SIL.Windows.Forms.Keyboarding/IKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/KeyboardController.cs, SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardSwitchingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/IIbusCommunicator.cs, SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardSwitchingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityIbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityIbusKeyboardSwitchingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityXkbKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/XkbKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs, SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs, TestApps/SIL.Windows.Forms.TestApp/Program.cs
This change enables the Keyman configuration link on Linux if _Keyman for Linux_ is installed, and adds a new method
`GetSecondaryKeyboardSetupAction()` to the semi-public `IKeyboardRetrievingAdaptor` interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/969)
=> Add Keyman configuration link on Linux (LT-20361)

SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/XkbKeyboardRetrievingAdaptor.cs, TestApps/TestAppKeyboard/KeyboardForm.cs
This change fixes the retrieving of xkb keyboards on Cinnamon desktop if ibus is not installed. It also fixes the issue that in this case the keyboard setup link opened the wrong application.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/971)
=> Support retrieving xkb keyboards on Cinnamon (#970)

SIL.Windows.Forms.GeckoBrowserAdapter/GeckoBase.cs, SIL.Windows.Forms.Keyboarding/KeyboardController.cs, SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs, SIL.Windows.Forms/Widgets/StdTextInputBox.cs
If the user removes all keyboards on Linux except ibus/keyman ones we still don't want to crash...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/975)
=> [keyboarding] Don't crash if no xkb keyboards installed

SIL.Windows.Forms.Keyboarding.Tests/GnomeKeyboardRetrievingHelperTests.cs, SIL.Windows.Forms.Keyboarding/Linux/GnomeKeyboardRetrievingHelper.cs
Sometimes for whatever reason we get duplicate keyboard layouts. This shouldn't lead to a crash. This fixes LT-20410.
(more or less cherry-pick from master branch)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/977)
=> [feature/nuget - keyboarding] Don't crash if we encounter duplicate layouts

SIL.Windows.Forms/ClearShare/MetaData.cs, SIL.Windows.Forms/ImageToolbox/AcquireImageControl.cs, SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs, SIL.Windows.Forms/ImageToolbox/ImageToolboxDialog.cs, SIL.Windows.Forms/ImageToolbox/PalasoImage.cs
- Many cases where image file has the wrong extension now open normally
- Many cases that previously wrongly reported OutOfMemoryException now report TagLib.CorruptFileException
- Client can provide own function to handle failing to load image
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/978)
=> Improve error handling when loading images (for BL-8996)

SIL.Windows.Forms.WritingSystems/LanguageLookupControl.Designer.cs, SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs, SIL.WritingSystems.Tests/IetfLanguageTagTests.cs, SIL.WritingSystems/IetfLanguageTag.cs, TestApps/SIL.Windows.Forms.TestApp/TestAppForm.cs
This is a partial fix for BL-9004, a crash that was happening if you open the scripts and variants control again after entering a private use language code other than qaa.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/973)
=> Allow private language tags and related improvements

SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj, SIL.Windows.Forms.Keyboarding.Tests/UnityKeyboardRetrievingHelperTests.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityIbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityKeyboardRetrievingHelper.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityXkbKeyboardRetrievingAdaptor.cs
Sometimes for whatever reason we get duplicate keyboard layouts. This shouldn't lead to a crash. This fixes [LT-20410](https://jira.sil.org/browse/LT-20410).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/976)
=> [master - keyboarding] Don't crash if we encounter duplicate layouts

SIL.Windows.Forms.Keyboarding.Tests/UnityKeyboardRetrievingHelperTests.cs, SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/GList.cs, SIL.Windows.Forms.Keyboarding/Linux/GlibHelper.cs, SIL.Windows.Forms.Keyboarding/Linux/GnomeShellIbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/GnomeShellIbusKeyboardSwitchingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/GnomeXkbInfo.cs, SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardDescription.cs, SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/IbusXkbKeyboardDescription.cs, SIL.Windows.Forms.Keyboarding/Linux/KeyboardRetrievingHelper.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityIbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityIbusKeyboardSwitchingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityKeyboardRetrievingHelper.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityXkbKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/Unmanaged.cs, SIL.Windows.Forms.Keyboarding/Linux/XkbIbusEngineDesc.cs, SIL.Windows.Forms.Keyboarding/Linux/XkbKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
This change fixes keyboard detection and switching in Gnome Shell.
Some fixes for other environments modified the base class which
broke keyboarding in Gnome Shell. Additionally some of the assumptions
were wrong - it's surprising that things worked earlier...
This change is basically a backport of the changes that were done
earlier on the feature/nuget branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/985)
=> [keyboarding] Fix keyboard switching in Gnome (LT-20428)

SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs, SIL.WritingSystems/ILocalWritingSystemRepository.cs, SIL.WritingSystems/LdmlInFolderWritingSystemRepository.cs, SIL.WritingSystems/LocalWritingSystemRepositoryBase.cs
Users of FieldWorks wanted to be able to update specific
writing systems from the global store
* Change signature of CheckForNewerGlobalWritingSystems to allow
a list of language tags to be used to filter the results
* Add unit tests for CheckForNewerGlobalWritingSystems
* Also do some minor code cleanup
This is a breaking api change, but only for liblcm - which we will
change concurrently
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/996)
=> Add langTag filtering in CheckForNewerGlobalWritingSystems

SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs
In some circumstances, it appears that `inputLanguage.culture.KeyboardLayoutId` property has a mismatch with the `inputLanguage.Handle` property, and is returning the wrong value (e.g. `0x04090409` instead of `0x04092000`), and we should instead be enumerating on the basis of the input value from `inputLanguage`.
This was spotted in testing by June, who found that Keyman keyboards associated with transient languages were not listed as available for use in PT.
About transient languages: https://docs.microsoft.com/en-us/globalization/locale/locale-names
Using the `inputLanguage.Handle` property removes this lookup and should return the same results.
It would be good to know if this is a bug in .NET or something else that's environmental. I have tested on Win 10 1909 and Win 10 2004 and the …
=> Handle transient languages with invalid .NET data

CHANGELOG.md, SIL.Scripture.Tests/VerseRefTests.cs, SIL.Scripture/VerseRef.cs
Done in response to issues with PR #997
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/999)
=> Separate non-Roman verse setting to restore USX compliance in VerseRef

ReadmeDesignerProjects.md, SIL.Core.Tests/SIL.Core.Tests.csproj
The Pack build target wasn't working likely due to a bug in msbuild https://github.com/dotnet/msbuild/issues/4303 This is a workaround for the issue. Also updated the readme for designer projects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1041)
=> Get nuget packaging build target working

SIL.WritingSystems.Tests/SIL.WritingSystems.Tests.csproj
This change prevents the dlls from Icu4c.Win.Min to automatically
get copied to the output directory when a client consumes the
SIL.WritingSystems.Tests nuget package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1046)
=> Don't automatically copy files from Icu4c

SIL.Windows.Forms.GeckoBrowserAdapter/GeckoFxWebBrowserAdapter.cs
* Change the expected type of the Length property to uint
falling back to int to support old and new Gecko versions.
This Fixes FieldWorks bug LT-20490
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1049)
=> Fix bug with scrolling the last element into view on GeckoFx60

SIL.Windows.Forms/SIL.Windows.Forms.csproj
We need the GtkSharp-signed and Mono.Posix packages for building on
Windows, but not at runtime. On Linux these assemblies are available
as part of Mono, but depending on the Windows versions will break
things. This change sets the `PrivateAssets` attribute for the two
Windows packages. This will allow to build on Windows, but will prevent
a package dependency on these two packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1053)
=> [SIL.Windows.Forms] Make GtkSharp and Mono.Posix build-only deps

SIL.Core/Acknowledgements/AcknowledgementsProvider.cs, TestApps/SIL.Windows.Forms.TestApp/README.md, TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj, TestApps/SIL.Windows.Forms.TestApp/environ
For some reason (probably newer mono version) we get a different exception message when the AcknowledgmentsProvider can't load a file. I can't see a reason why we'd have to check the exception message, so now we always ignore a BadImageException.
This change also fixes the SWF test app so that it properly works with Gecko on Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1054)
=> Fix AcknowledgementsProvider

SIL.Core.Desktop/IO/FileLocator.cs
* Add extra null checks to prevent crashes on systems where
a faulty ramp uninstallation has corrupted the registry
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1058)
=> Don't crash finding ramp in corrupted installs

SIL.Windows.Forms.GeckoBrowserAdapter/GeckoFxWebBrowserAdapter.cs
* Change the expected type of the Length property to uint
but fall back to int to support old and new Gecko versions
This Fixes FieldWorks bug LT-20490
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1059)
=> Fix bug with scrolling the last element into view on GeckoFx60 (cherry-pick of #1049)

SIL.Windows.Forms/ClearShare/WinFormsUI/ContributorsListControl.cs, TestApps/SIL.Windows.Forms.TestApp/ContributorsForm.cs, TestApps/SIL.Windows.Forms.TestApp/TestAppForm.Designer.cs, TestApps/SIL.Windows.Forms.TestApp/TestAppForm.cs, TestApps/SIL.Windows.Forms.TestApp/TestAppForm.resx
This prevents a null Role from causing an error to be displayed when formatting that cell in a new row.
Added to the TestApp so it would be easy to see how ContributorsListControl is to be used and to enable debugging it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1060)
=> SP-2193: Added handler for DataError in ContributorsListControl grid

SIL.Archiving.Tests/ArchivingFileSystemTests.cs, SIL.Archiving/Generic/ArchivingFileSystem.cs, SIL.Core.Tests/IO/FileLock/SimpleFileLockTests.cs, SIL.WritingSystems.Tests/GlobalWritingSystemRepositoryTests.cs, SIL.WritingSystems.Tests/Migration/GlobalWritingSystemRepositoryMigratorTests.cs, SIL.WritingSystems/GlobalWritingSystemRepository.cs, SIL.WritingSystems/Migration/GlobalWritingSystemRepositoryMigrator.cs, SIL.WritingSystems/Sldr.cs
* Use IsUnix instead of IsLinux for code involving file paths
to allow these libraries to execute on a Mac
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1056)
=> Improve Mac Support

SIL.Windows.Forms.Keyboarding/Linux/IbusCommunicator.cs
* Fix Flex bug LT-20429 by disposing and clearing out the connection
if we get a DBusConectionErrorException[*sic*]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1066)
=> Avoid crashes in cases where Ibus connection dropped

SIL.Windows.Forms.Tests/ImageToolbox/PalasoImageTests.cs, SIL.Windows.Forms/ImageToolbox/PalasoImage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1067)
=> Fix bug where PalasoImage disposes of its Image prematurely

SIL.Windows.Forms.GeckoBrowserAdapter/GeckoFxWebBrowserAdapter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1070)
=> Fix crash casting uint to int when using GeckoFx60

SIL.Windows.Forms.Tests/ClearShare/MetadataTests.cs, SIL.Windows.Forms/ClearShare/MetaData.cs
The change allows users to go from a CC license to a non-CC license for
images.  The reverse was already possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1071)
=> Save non-CC licenses properly in images

CHANGELOG.md, SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageCollectionManager.cs
This could possibly prevent such a crash in a real program as well.
See https://issues.bloomlibrary.org/youtrack/issue/BL-9825 for a crash
during a unit test that this should prevent 99.999% of the time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1075)
=> Prevent a race condition crash in a unit test

SIL.Windows.Forms/ImageToolbox/Cropping/ImageCropper.cs
The problem is really trying to crop to a section that is not quite inside the original image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1080)
=> Fix "OutOfMemory" in image cropping (BL-9925)

SIL.WritingSystems/SimpleRulesParser.cs
We have had exception reports when Paratext is saving language data that has passed the Paratext checks, but causes an error in the SimpleRulesParser. This change prevents a second exception from being created because the exception from the Spart parser must not contain the expected data.
Hopefully with this change, we will get a better message and be able to figure out what the problem data is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1081)
=> Prevent second exception when handling parser exception (PTX-15835)

CHANGELOG.md, SIL.Core.Tests/Xml/XmlUtilsTests.cs, SIL.Core/Xml/XmlUtils.cs
Add a utility method to remove XML namespaces
(cherry picked from commit 11e7dc941c0c2d0579ae26f799d071fe3d7d88ad)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1079)
=> [API] Remove XML Namespaces

CHANGELOG.md, Palaso.sln.DotSettings, SIL.Scripture.Tests/VerseRefTests.cs, SIL.Scripture/IScrVerseRef.cs, SIL.Scripture/SIL.Scripture.csproj, SIL.Scripture/VerseRef.cs, SIL.Windows.Forms.Scripture/VerseControl.cs
Added IScrVerseRef interface (largely extracted from VerseRef)
Made VerseRef class implement new IScrVerseRef interface
Changed VerseControl to use IScrVerseRef and not depend directly on ScrVers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1086)
=> Made VerseControl usable by Paratext plugins

SIL.Windows.Forms/ImageToolbox/AcquireImageControl.cs
Using Alt-F4 to close the dialog also provoked the crash in the same
circumstances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1091)
=> Prevent a crash closing the ImageToolboxDialog with the X button

CHANGELOG.md, Palaso.sln.DotSettings, SIL.Core.Tests/Extensions/StringExtensionTests.cs, SIL.Windows.Forms/ParentFormBase.cs, SIL.Windows.Forms/SIL.Windows.Forms.csproj
This base class allows a form to show a child form that is modal with respect to the parent but not application modal.
Note that this was written for Transcelerator, but it is potentially useful for other "standalone" Paratext plugins. And there may be good uses for it elsewhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1095)
=> +semver:minor Added ParentFormBase

SIL.WritingSystems/GlobalWritingSystemRepository.cs
- `USER_DATA_HOME` is more generic for re-use in other parts of
libpalaso if found to be helpful.
- The name of `USER_DATA_HOME` is intended to mean that it's the
user's `XDG_DATA_HOME`. Normally there would not need to be any
distinction, but when running in flatpak, the XDG_DATA_HOME is
application-specific. In this situation, the USER_DATA_HOME could be
set (by the application using libpalaso) to the location of the user's
XDG_DATA_HOME that is external to the flatpak.
===
For further discussion, see PR #1111. 
This PR is probably really a "breaking change", but as long as no one else discovered and started implementing the WSR_ROOT_PATH from a week and a half ago, this is just a revision of the added feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Use more generic environment variable for WS root

SIL.Core/Threading/GlobalMutex.cs
- On Ubuntu, /var/lock exists and is +t, writable by users, and so
isn't a problem there. But /var/lock isn't user-writable on other
Linux systems, like Fedora and Clear Linux. But each of these set
XDG_RUNTIME_DIR, and the user can write there.
- XDG_RUNTIME_DIR isn't a _global_ location for lock files. So if it
is important for GlobalMutex to provide a multi-user, system-wide lock
file, we may need to consider using /dev/shm, /tmp, or /var/tmp.
===
Without this problem, FieldWorks (flatpak) launches and works on Fedora :-)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1114)
=> Use XDG_RUNTIME_DIR for GlobalMutex on Linux

SIL.Windows.Forms/ParentFormBase.cs
when parent is on screen whose coordinates are negative (wrt primary screen).
Note: Technically, this code should perhaps determine what screen the parent is on and then use that screen's upper left corner as the minimum location, but typically a child window will be smaller than the parent, so it will seldom matter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1116)
=> Fixed code for positioning modal child window

CHANGELOG.md, SIL.Windows.Forms/SettingProtection/SettingsProtectionHelper.cs
Note: this code was supposed to be part of previous merge, but was inadvertently omitted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1119)
=> Ensure components are made visible when no longer being managed by SettingsProtectionHelper

appveyor.yml
The `cmd: >-` concatenates lines if there are no empty lines in-between, so this change should fix this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1121)
=> Fix appveyor environment setting

SIL.Core/IO/TempFile.cs
This would have made BL-10784 easier to diagnose.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1124)
=> Add path information to exceptions thrown by TempFile.InfolderOf

SIL.Archiving/RampArchivingDlgViewModel.cs
RAMP 3.0 does not contain a languages.yaml file. For Windows there
is existing code that returns an empty string. Added the same check
to return an empty string on Linux.
Note: The Windows fix for the same issue was added in Commit ef527269
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1125)
=> LT-19174: Fix Linux crash when archiving to RAMP

CHANGELOG.md, SIL.Archiving/SIL.Archiving.csproj, SIL.Windows.Forms.DblBundle/SIL.Windows.Forms.DblBundle.csproj, SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj, SIL.Windows.Forms.WritingSystems/SIL.Windows.Forms.WritingSystems.csproj, SIL.Windows.Forms/SIL.Windows.Forms.csproj, TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj
Although nothing in libpalaso uses the new (breaking change) version of StringsLocalized, I can't seem to find a way to make the Designer happy in other apps that refer to the new version of L10nSharp but also reference controls in libpalaso that reference the older version. (This is not a runtime problem - just a Design-time issue.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1130)
=> +semver:major Upgraded to version 5.0.0-beta0059 of `L10NSharp.dll`

SIL.TestUtilities.Tests/ValueEquatableComparerTests.cs, SIL.TestUtilities/CloneableTests.cs, SIL.TestUtilities/ValueEquatableComparer.cs
object.Equals returns false for two distinct but equal IValueEquatable<T>'s if T does not override .Equals and .GetHashCode (IValueEquatable<T> is specifically for cases when we do not want to override GetHashCode)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1131)
=> Allow CloneableTests to test classes' IValueEquatable fields

SIL.Core.Tests/PlatformUtilities/PlatformTests.cs, SIL.Core/PlatformUtilities/Platform.cs, SIL.Windows.Forms.Keyboarding.Tests/UnityKeyboardRetrievingHelperTests.cs, SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardSwitchingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityKeyboardRetrievingHelper.cs
===
Along with a needed ibusdotnet change, this should make keyboarding work in flatpak when the host is running Gnome on Ubuntu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1127)
=> keyboarding thru flatpak

.vscode/launch.json, SIL.Core.Desktop/Reporting/Logger.cs, SIL.Core.Tests/PlatformUtilities/PlatformTests.cs, SIL.Core/PlatformUtilities/Platform.cs, SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/GnomeShellIbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityIbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/XkbKeyboardRetrievingAdaptor.cs, TestApps/TestAppKeyboard/Program.cs, TestApps/TestAppKeyboard/TestAppKeyboard.csproj
===
These changes are not central to the fixes for flatpak keyboarding and so I put them in a separate PR. 
Notably, this allows you to show libpalaso logs instead of tuck them away at `/tmp/SIL/My\ App\ Name/foo.txt`. This is even more helpful when the app is running in a container where you need to do extra steps to see that part of the filesystem while the application is running.
A check in Platform was improved for flatpak.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1128)
=> improve logging, platform check

CHANGELOG.md, SIL.Media.Tests/AudioFactoryTests.cs, SIL.Media.Tests/AudioRecorderTests.cs, SIL.Media.Tests/AudioSessionTests.cs, SIL.Media/AudioFactory.cs, SIL.Media/Naudio/AudioRecorder.cs, SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs
I'm looking into HT-402. I don't have any good reason to believe this could be the cause of that problem, but it does seem like this lock should be done earlier lest the value change between the time we check it and the time we set it. I don't think this could inadvertently result in a new deadlock. If it does, then it probably shows there is a real problem, but because none of the unit tests probably are capable of testing this well even if they tried, it is worth careful scrutiny.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1139)
=> HT-402: Moved lock to cover check for initial _recordingState in BeginRecording

l10n/l10n.proj
- use GitVersion.MsBuild instead of deprecated GitVersionTask
- use TargetFramework**s** (plural) because that's defined in the parent Directory.Build.props
- 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1151)
=> Fix l10n.proj

.gitignore, CHANGELOG.md, DistFiles/Palaso.en.xlf, DistFiles/Palaso.es.xlf, Palaso.sln.DotSettings, SIL.Core/Extensions/StringExtensions.cs, SIL.Windows.Forms/Extensions/TextBoxExtensions.cs, SIL.Windows.Forms/Reporting/ExceptionReportingDialog.cs, SIL.Windows.Forms/Reporting/ExceptionReportingDialog.resx, SIL.Windows.Forms/Reporting/ProblemNotificationDialog.cs, TestApps/SIL.Windows.Forms.TestApp/Program.cs, TestApps/SIL.Windows.Forms.TestApp/TestAppForm.Designer.cs, TestApps/SIL.Windows.Forms.TestApp/TestAppForm.cs
Internationalized the ExceptionReportingDialog
Also used LocalizationManager for the caption for the ProblemNotificationDialog.
Fixed layout issues in ExceptionReportingDialog to prevent overlapping text.
Fixed handling of \n in message text so that it lays out correctly in the ProblemNotificationDialog (because strings returned from L10NSharp typically don't have the \r)
[WIP] Could not figure out how to re-extract the strings to update the XLF files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1148)
=> Internationalization and layout fixes in exception/problem reporting dialogs

SIL.Windows.Forms.Keyboarding.Tests/KeyboardRetrievingHelperTests.cs, SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj, SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/KeyboardRetrievingHelper.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityKeyboardRetrievingHelper.cs
When running in flatpak, prefix host paths when looking for programs
installed in /usr, and use flatpak-spawn to launch external programs
such as the keyboard configuration tools.
commit-id:7ba8be9b
---
**Stack**:
- #1150
- #1149
- #1144
- #1143 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
=> flatpak: keyboarding: flatpak-spawn keyboard config tool

SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs
Filter the sort language list so that it only contains languages
that are installed on the machine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1154)
=> LT-21002: Prevent crash by filtering the sort list

CHANGELOG.md, DistFiles/Palaso.en.xlf, SIL.Media/WindowsAudioSession.cs, SIL.Windows.Forms/ImageToolbox/AcquireImageControl.cs, SIL.Windows.Forms/ImageToolbox/ImageAcquisitionService.cs, SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs, l10n/l10n.proj
During a regular build (of a .csproj) the build system sets `TargetFramework` for each framework in `TargetFrameworks`. This causes the `PkgL10NSharp_ExtractXliff` to get defined (in `obj\l10n.proj.nuget.g.props`). However, if `TargetFrameworks` is set,
the definition of the property gets an additional condition on `TargetFramework` so that the property isn't set when `UpdateCrowdin` runs.
This change sets `TargetFramework` (and sets `TargetFrameworks` to the empty string) to work around this problem.
See also https://github.com/NuGet/Home/issues/11721 and https://github.com/NuGet/Home/issues/11725
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1155)
=> Another attempt to fix l10n.proj

SIL.Scripture/MultilingScrBooks.cs, SIL.Windows.Forms.Scripture.Tests/VerseControlTests.cs, SIL.Windows.Forms.Scripture/VerseControl.cs
Implementing a Paratext feature request to be able to paste a scripture reference into the verse control.
The reference can either be the short form: GEN 1:27
or a longer form that uses the localized book names: 2 Corinthians 3:18
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1153)
=> PTX-21397 add ability to paste scripture ref in VerseControl

SIL.Archiving/RampArchivingDlgViewModel.cs
- This was already done for Windows in LT-19077.
- This change returns string.Empty in Linux as well, when
languages.yaml is not found.
- This is to fix the problem reported in LT-20968.
---
**Stack**:
- #1157
- #1152 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1152)
=> archiving: don't throw when no languages.yaml in Linux

CHANGELOG.md, SIL.Core.Desktop/IO/DirectoryUtilities.cs, SIL.Core.Desktop/IO/FileLocator.cs, SIL.Core.Desktop/Progress/Commands/AsyncCommand.cs, SIL.Core.Desktop/Progress/Commands/BasicCommand.cs, SIL.Core.Desktop/SIL.Core.Desktop.csproj, SIL.Core.Desktop/UsbDrive/Linux/IUDiskDevice.cs, SIL.Core.Desktop/UsbDrive/Linux/IUDisks.cs, SIL.Core.Desktop/UsbDrive/Linux/UDiskDevice.cs, SIL.Core.Desktop/UsbDrive/Linux/UDisks.cs, SIL.Core.Desktop/UsbDrive/Linux/UsbDriveInfoHAL.cs, SIL.Core.Desktop/UsbDrive/Linux/UsbDriveInfoUDisks.cs, SIL.Core.Desktop/UsbDrive/Linux/UsbDriveInfoUDisks2.cs, SIL.Core.Desktop/UsbDrive/UsbDriveInfo.cs, SIL.Core.Desktop/UsbDrive/Windows/UsbDriveInfoWindows.cs, SIL.Lift/SIL.Lift.csproj, SIL.Lift/Utilities.cs, SIL.Linux.Logging/SIL.Linux.Logging.csproj
I didn't dual-target SIL.Linux.Logging to Framework 4.6.1 (as appears to be the pattern), because the .NET Standard version of SIL.Core contains Mono.Posix.NetStandard, which required me to remove the Mono.Posix reference here. If this is desired, I can spend more time on it. **Edit: 4.6.1 support added back.**
I also added a preprocessor directive to Utilities.cs for Framework only, since .NET Standard doesn't support the .TemporaryFiles property.
For more information, see:
https://docs.microsoft.com/en-us/dotnet/api/system.xml.xsl.xslcompiledtransform.temporaryfiles?view=netframework-4.6.1
https://github.com/sillsdev/lift-standard/blame/4c3cd07950b58615549fd6005426304942d0b1f1/LIFTDotNet/LiftIO/Utilities.cs#L54
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Upgrading SIL.Core.Desktop, SIL.Lift, and SIL.Linux.Logging to .NET Standard.

SIL.Scripture/MultilingScrBooks.cs, SIL.Windows.Forms.Scripture.Tests/VerseControlTests.cs, SIL.Windows.Forms.Scripture/VerseControl.cs
Paratext testers found a couple of cases where the results from the pasting test in the verse control were not correct based on diacritics or RTL markers in the pasted text. The code was changed to remove diacritics and RTL markers from the the search text and use the BaseName of the book for all searches.
The UX team also decided that the best partial match should be returned rather than always requiring a unique match.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1162)
=> PTX-21397 revise book search based on Paratext testing

CHANGELOG.md, Palaso.sln.DotSettings, SIL.Windows.Forms.WritingSystems/Extensions.cs, SIL.WritingSystems.Tests/IetfLanguageTagTests.cs, SIL.WritingSystems/IetfLanguageTag.cs, SIL.WritingSystems/WellKnownSubtags.cs
Added common UI string for More menu.
Improved logic in IetfLanguageTag to get better results for zh-TW
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1171)
=> Improvements for UI locale menu strings

SIL.Windows.Forms/ImageToolbox/AcquireImageControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1173)
=> Fixed a couple strings that were not properly internationalized.

CHANGELOG.md
The changelog entries were merged in under the 9.* section, but should've been in the post-9.* section. I thought I had manually fixed this, but apparently that didn't make it into the final version :(
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1200)
=> Fix changelog entries merged into wrong place

CHANGELOG.md, Palaso.sln.DotSettings, SIL.Core.Tests/Extensions/StringExtensionTests.cs, SIL.Core/Extensions/StringExtensions.cs, SIL.WritingSystems.Tests/SldrTests.cs, SIL.WritingSystems/GlobalWritingSystemRepository.cs, SIL.WritingSystems/IcuUCharCategoryExtensions.cs, SIL.WritingSystems/Sldr.cs
Also added unit tests for this method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1202)
=> Allowed for alternate way of getting Unicode character categories in  IsLikelyWordForming

SIL.Core/Extensions/StringExtensions.cs, SIL.WritingSystems.Tests/SldrTests.cs, SIL.WritingSystems/Sldr.cs
Made the method testable and made it handle the case where the index passed in to IsLikelyWordForming is the character between the high and low surrogates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1203)
=> Made ICU-based implementation of method to get Unicode category of a character more robust

SIL.Archiving/IMDI/IMDIArchivingDlgViewModel.cs, SIL.Archiving/RampArchivingDlgViewModel.cs, SIL.DictionaryServices.Tests/Lift/LiftWriterTests.cs, SIL.WritingSystems.Tests/LdmlDataMapperTests.cs
In Germany, sometimes a dot is used instead of the colon to separate hours, minutes, and seconds: "16.12" for "16:12".
* Use DateTimeExtensions to write DateTimes to files (in the few places that didn't already)
* Test that LDML data is written in an invariant culture (LIFT writing was already tested).
https://jira.sil.org/browse/LT-20698
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="right" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1210)
=> Test for normalised DateTimes

SIL.Lexicon.Tests/UserLexiconSettingsWritingSystemDataMapperTests.cs, SIL.Lexicon/UserLexiconSettingsWritingSystemDataMapper.cs
This only happens if the LocalKeyboard does not get added
to the KeyboardController (e.g. invalid)
See: https://jira.sil.org/browse/LT-21112
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1217)
=> Fix crash if the LocalKeyboard is in KnownKeyboards

CHANGELOG.md, Palaso.sln.DotSettings, SIL.DblBundle.Tests/Usx/UsxDocumentTests.cs, SIL.DblBundle.Tests/Usx/UsxNodeTests.cs, SIL.DblBundle/Bundle.cs, SIL.DblBundle/Usx/UsxNode.cs
Made UsxNode abstract and added sealed subclasses, with tighter checking to ensure correct use.
Improved documentation
https://jira.sil.org/browse/PG-1487
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1220)
=> PG-1487: Added support for USX version 3 (chapter end nodes).

CHANGELOG.md, SIL.Core/EntryAssembly.cs, SIL.Core/IO/FileLocationUtilities.cs
When running under net6.0 our previous detection of unit tests no longer works because `GetEntryAssembly()` now returns the test runner. This change additionally searches the directory where SIL.Core.dll is located.
This change also moves the list of subdirectories where we look for files or directories into a private field. When looking for
directories we now also look directly in the application directory, which is a breaking change from previous behavior where we only looked in `DistFiles`, `common`, and `src` subdirectories. This matches the behavior of `GetFileDistributedWithApplication`.
+semver:major
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1227)
=> Fix `GetDirectoryDistributedWithApplication`

SIL.WritingSystems/Sldr.cs
Previous implementation caused us to request `uid=unknown` to which the server replied with `501 not implemented`. Since that was treated the same as the server not being available this wasn't noticeable unless you ran the tests marked as Explicit.
This change compares the uid with the default user id and omits the parameter if necessary. That causes the server to send a proper response and causes the explicit tests to pass.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1235)
=> Fix requesting LDML file with default user id

.vscode/launch.json, SIL.Core/PlatformUtilities/Platform.cs, SIL.Windows.Forms.Keyboarding.Tests/CombinedIbusKeyboardRetrievingAdaptorTests.cs, SIL.Windows.Forms.Keyboarding.Tests/Linux/GnomeShellIbusKeyboardSwitchingAdaptorTests.cs, SIL.Windows.Forms.Keyboarding.Tests/LinuxKeyboardControllerTests.cs, SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj, SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardSwitchingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/GlibHelper.cs, SIL.Windows.Forms.Keyboarding/Linux/GnomeShellIbusKeyboardSwitchingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardDescription.cs, SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardRetrievingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/IbusXkbKeyboardDescription.cs, SIL.Windows.Forms.Keyboarding/Linux/KeyboardRetrievingHelper.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityIbusKeyboardSwitchingAdaptor.cs, SIL.Windows.Forms.Keyboarding/Linux/UnityKeyboardRetrievingHelper.cs, SIL.Windows.Forms.Keyboarding/Linux/Unmanaged.cs, SIL.Windows.Forms.Keyboarding/Linux/XkbKeyboardRetrievingAdaptor.cs, TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj, TestApps/TestAppKeyboard/KeyboardForm.Designer.cs, TestApps/TestAppKeyboard/KeyboardForm.cs, build/buildupdate.mono.sh
The work is split in separate commits, which may also help when reviewing.
With these changes, keyboarding is working in Flatpak FieldWorks 9.0 in each of
- Ubuntu 20.04 (Gnome)
- Ubuntu 22.04 (Gnome)
- Wasta 20.04 (Cinnamon)
- Wasta 22.04 (Cinnamon)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1239)
=> Support keyboarding in Ubuntu 22.04, and other improvements

Palaso.sln.DotSettings, SIL.Windows.Forms/ClearShare/WinFormsUI/ContributorsListControl.cs, TestApps/SIL.Windows.Forms.TestApp/ContributorsForm.cs
Did a little bit of extra code cleanup
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1244)
=> SP-2297: Prevent changing row in ContributorsListControl if not in a valid state to commit edit

CHANGELOG.md, SIL.Core.Tests/ObjectModel/BulkObservableListTests.cs, SIL.Core/ObjectModel/BulkObservableList.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1247)
=> Fix BulkObservableList.MoveRange when moving a single item forward

CHANGELOG.md, SIL.Windows.Forms/Clipboarding/LinuxClipboard.NativeMethods.cs
- they don't have libdl.so - but only libdl.so.2
- see https://stackoverflow.com/questions/75855053/how-to-address-crash-due-to-missing-libdl-so-on-ubuntu-22
This work is untested
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1250)
=> This is to fix running on Ubuntu 22x

SIL.Core/Reflection/ReflectionHelper.cs
Previously `DirectoryOfTheApplicationExecutable` was determining that it was in a testing context by checking if `Assembly.GetEntryAssembly() == null` this is no longer always true, for example running tests in Rider.
This PR changes the code to use the presence of a loaded unit testing dll as the indicator that we're running tests. I have preserved the check for `Assembly.GetEntryAssembly() == null` so as to not break backwards compatibility with any code that currently depends on the unit test path running when the assembly is null. This should reduce this to only changing functionality when running tests and not in any other cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> change detection of a unit test context

SIL.Core/IO/FileLocationUtilities.cs
When calling `GetDirectoryDistributedWithApplication` and it doesn't find the path on the first try, it will attempt to use the location of the executing assembly. However the code incorrectly assumes that `Assembly.GetExecutingAssembly().Location` returns a directory path, when it actually returns a file path. This change fixes that.
I have not run any test. However I checked `Assembly.GetExecutingAssembly().Location` via linqpad against .Net 7 and .Net framework and they both return a file path. I have verified that `Path.GetDirectoryName` returns the full path, not just the name of the parent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1252)
=> fix bug where a dll was treated as a folder when trying to find a directory

CHANGELOG.md, SIL.Core.Tests/Code/RetryUtilityTests.cs, SIL.Core/Code/RetryUtility.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1257)
=> RetryUtility now retries for subclasses of exceptions listed (BL-12363)

CHANGELOG.md, SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageGalleryControl.cs
Fixed a spelling error in an API method for ImageGalleryControl and removed an unused/misspelled public field
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1269)
=> ImageGalleryControl API corrections

CHANGELOG.md, Palaso.sln.DotSettings, SIL.Core/IO/DirectoryHelper.cs, SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs
One version of each of these methods does not require Windows Forms. So by putting them into SIL.Core, they will be available for non-Forms applications.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1271)
=> +semver:major Moved versions of CanWriteToDirectories and CanWriteToDirectory

SIL.Windows.Forms/Reporting/WinFormsExceptionHandler.cs
Check ControlOnUIThread for null first
(this is the fancy syntax R# recommended)
Fixes the crash reported in https://jira.sil.org/browse/LT-21467 which swallows the crash reported in https://github.com/sillsdev/libpalaso/issues/1275
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1277)
=> Don't throw trying to report errors

CHANGELOG.md, SIL.Media/Naudio/AudioRecorder.cs
For Bloom https://issues.bloomlibrary.org/youtrack/issue/BL-12406/Dont-show-error-Dialog-if-mic-access-is-off
Create a version of BeginMonitoring that doesn't catch the exceptions so that they can be handled by the caller
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1280)
=> add audio monitoring without exception catching

CHANGELOG.md, SIL.Core.Desktop/IO/RobustImageIO.cs, SIL.Core/Code/RetryUtility.cs, SIL.Core/IO/RobustFile.cs, SIL.Core/IO/RobustIO.cs
Almost all of the methods have been implemented and used in Bloom for some time.  (and flagged for moving to libpalaso)
The enhancements to RetryUtility have been useful for finding problems and verifying the operation of the Robust methods.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1283)
=> Add several RobustFile and RobustIO methods and enhance RetryUtility

CHANGELOG.md, DistFiles/Palaso.en.xlf, DistFiles/Palaso.es.xlf, DistFiles/Palaso.fr.xlf, SIL.Windows.Forms/SettingProtection/SettingsLauncherButton.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1284)
=> Fixed i18n problem: SettingsProtection.LauncherButtonLabel was ID for two different strings

CHANGELOG.md, SIL.Core.Desktop/IO/FileUtils.cs, SIL.Core/IO/RobustFile.cs
This fixes a robustness hole discovered in Bloom (BL-12669).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1297)
=> Make FileUtils.ReplaceFileWithUserInteractionIfNeeded robust

SIL.Windows.Forms/ImageToolbox/AcquireImageControl.Designer.cs, SIL.Windows.Forms/ImageToolbox/AcquireImageControl.cs, SIL.Windows.Forms/ImageToolbox/AcquireImageControl.resx
Use the custom no border toolstrip renderer to eliminate the white border artifact in AquireImageControl. (Other part of [LT-21652](https://jira.sil.org/browse/LT-21652).)
Also set toolStrip1's RenderMode to Professional and reset back color to control from within the design view, which regenerated the designer & resx files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1301)
=> LT-21652: polish picture dialog

CHANGELOG.md, SIL.Windows.Forms.WritingSystems/WSIdentifiers/ScriptRegionVariantView.Designer.cs, SIL.Windows.Forms.WritingSystems/WSIdentifiers/WSIdentifierView.cs
This fixes a bug reported by Bloom in BL-12373.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1304)
=> Prevent editing combobox controls for Script and Variant dialog

CHANGELOG.md, SIL.Windows.Forms/ClearShare/Metadata.cs
Losing metadata shouldn't keep the image itself from being used.  This helps with a Bloom bug reported in BL-11933.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1305)
=> Catch ArgumentOutOfRangeException exception from TagLib

CHANGELOG.md, SIL.Windows.Forms/Widgets/BetterGrid/BetterGrid.cs
This change should make it so the delete button works correctly if there is no "new row"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1307)
=> Fixed error in BetterGrid.OnCellContentClick

CHANGELOG.md, SIL.DictionaryServices/Lift/HtmlArticleMaker.cs, SIL.DictionaryServices/Lift/LiftWriter.cs
Noticed one of these variable misspellings when debugging an issue in The Combine.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1306)
=> Fix typos in SIL.DictionaryServices/Lift/

CHANGELOG.md, SIL.Core.Tests/Extensions/StringExtensionTests.cs, SIL.Core/Extensions/StringExtensions.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1309)
=> Fixed bug in GetLongestUsefulCommonSubstring when string ends with an ORC

CHANGELOG.md, SIL.Windows.Forms/Extensions/ToolStripExtensions.cs, SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteViewModel.cs
(Technically this is a breaking contractual change, since effectively the behavior is the opposite of the original implementation, but the name so clearly indicates the desired behavior that it seems unlikely any subclass implementation would have implemented the logic according to the previously expected backwards behavior.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1318)
=> Fixed backwards logic for LocalizationIncompleteViewModel.ShouldShowDialog

CHANGELOG.md, SIL.Core/Threading/GlobalMutex.cs
The Linux approach for generating a lock doesn't work on macOS because `/var/lock` doesn't exist on macOS.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1327)
=> Add a macOS-compatible global lock

SIL.Lift/Migration/Migrator.cs
Seems to be used only in WorldPad, which isn't even available for download, so I don't know how much we care about this, But it's a public method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1332)
=> Added using to ensure that the XSL stream gets disposed in DoOneMigrationStep

CHANGELOG.md, SIL.Windows.Forms.Tests/ImageToolbox/ImageToolboxTests.cs, SIL.Windows.Forms/ImageToolbox/AcquireImageControl.cs
This enforces the image file filter even when users type or paste in a file path that defeats the filter.  This fix is motivated by https://issues.bloomlibrary.org/youtrack/issue/BL-13552.  Using the DialogAdapters interface prevents having an actual FileOk handler.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1335)
=> Simulate a FileOk handler when choosing an image file

SIL.Media/MediaInfo.cs
Otherwise, the value set is ignored!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1333)
=> Added call to GlobalFFOptions.Configure when setting FFprobeFolder.

SIL.Lift.Tests/Parsing/ParserTests.cs, SIL.Lift/Parsing/LiftMultiText.cs
- This bug caused a crash importing into FieldWorks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1338)
=> Fix crash parsing an empty multi-text that contains an empty span

.github/workflows/l10n-packaging.yml, .github/workflows/l10n-source.yml
the Update l10n workflow is [broken](https://github.com/sillsdev/libpalaso/actions/runs/10400639520) since #1336 was merged in. This wasn't caught as part of the PR because those workflows don't run.
Now these 2 workflows will always use the latest version of dotnet, this should help us avoid this issue in the future if projects target dotnet 9 etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1339)
=> fix l10n workflows by using latest dotnet version

CHANGELOG.md, SIL.Windows.Forms/Clipboarding/WindowsClipboard.cs
This can help preserve transparency in copied images.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1344)
=> Reorder image fetching for GetImageFromClipboard to try PNG first

.github/workflows/l10n-packaging.yml, .github/workflows/l10n-source.yml, SIL.WritingSystems.Tests/SldrTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1345)
=> Fix build errors

CHANGELOG.md, SIL.Archiving.Tests/IMDIArchivingDlgViewModelTests.cs, SIL.Archiving.Tests/RampArchivingDlgViewModelTests.cs, SIL.Archiving/ArchivingDlgViewModel.cs, SIL.Archiving/RampArchivingDlgViewModel.cs, TestApps/ArchivingTestApp/MainForm.cs
Added unit tests and changed test app to illustrate intended usage of the new properties. Improved/added some comments in ArchivingDlgViewModel
Note: I considered removing OverrideDisplayInitialSummary because with this change, I anticipate that it will no longer be needed, but since it is inexpensive to leave in and allows for maximum flexibility, I decided to leave it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1349)
=> +semver:major Added properties to ArchivingDlgViewModel to facilitate customizing the initial summary

SIL.Archiving.Tests/IMDIArchivingDlgViewModelTests.cs, SIL.Archiving.Tests/SIL.Archiving.Tests.csproj, SIL.Archiving/SIL.Archiving.csproj
Test library targets .NET8. I did have to make a few tests which were testing for exact strings a little less specific, since the message varies between frameworks. They are different, since directory checking works differently between frameworks, but the core failure+warning is present.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1347)
=> Added .NET Standard 2.0 to SIL.Archiving

SIL.Core.Desktop.Tests/SIL.Core.Desktop.Tests.csproj, SIL.Core.Tests/Acknowledgements/AcknowledgementAttributeTests.cs, SIL.Core.Tests/PlatformUtilities/PlatformTests.cs, SIL.Core.Tests/Progress/ConsoleProgressTests.cs, SIL.Core.Tests/SIL.Core.Tests.csproj, SIL.Core/CommandLineProcessing/SynchronousProcessOutputReader.cs, TestApps/CommandLineRunnerTestApp/CommandLineRunnerTestApp.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1348)
=> .NET8 SIL.Core.Tests

Directory.Build.props
by adding `<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />` to our test projects they were marked as `IsPackable` false, which usually makes sense, this reverts that
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1356)
=> make all test projects packable

.github/workflows/build.yml, CHANGELOG.md, SIL.Core.Tests/Xml/XmlUtilsTests.cs, SIL.Core/Xml/XmlUtils.cs
We need this for FlexBridge to avoid some occasional data mangling during Send/Receive
I left the original behavior intact assuming that it was intentional, if it wasn't we could simply always write out the namespace names.
I also updated one of our gha dependencies in this PR, that is unrelated to the core change. (If someone else decides to merge this please rebase rather than merge to keep the changes separate)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1357)
=> Add an optional parameter to XmlUtils.WriteNode to preserve specific namespaces

.github/workflows/build.yml, SIL.Archiving.Tests/SIL.Archiving.Tests.csproj, SIL.Core.Desktop.Tests/SIL.Core.Desktop.Tests.csproj, SIL.Core.Tests/SIL.Core.Tests.csproj, SIL.DblBundle.Tests/SIL.DblBundle.Tests.csproj, SIL.DictionaryServices.Tests/SIL.DictionaryServices.Tests.csproj, SIL.Lexicon.Tests/SIL.Lexicon.Tests.csproj, SIL.Lift.Tests/SIL.Lift.Tests.csproj, SIL.Linux.Logging.Tests/SIL.Linux.Logging.Tests.csproj, SIL.Media.Tests/SIL.Media.Tests.csproj, SIL.Scripture.Tests/SIL.Scripture.Tests.csproj, SIL.TestUtilities.Tests/SIL.TestUtilities.Tests.csproj, SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj, SIL.Windows.Forms.Scripture.Tests/SIL.Windows.Forms.Scripture.Tests.csproj, SIL.Windows.Forms.Scripture.Tests/VerseControlTests.cs, SIL.Windows.Forms.Tests/SIL.Windows.Forms.Tests.csproj, SIL.Windows.Forms.WritingSystems.Tests/SIL.Windows.Forms.WritingSystems.Tests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1362)
=> Added framework matrix to build

CHANGELOG.md, SIL.Archiving/ArchivingPrograms.cs, SIL.Core.Desktop.Tests/IO/FileLocatorTests.cs, SIL.Core.Desktop/IO/FileLocator.cs
Renamed GetFromRegistryProgramThatOpensFileType to GetDefaultProgramForFileType and implemented it in a way that works on Windows 11, Mono (probably) and MacOS (untested).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1361)
=> Renamed and reimplemented GetFromRegistryProgramThatOpensFileType

CHANGELOG.md, Palaso.sln.DotSettings, SIL.Archiving.Tests/RampArchivingDlgViewModelTests.cs, SIL.Archiving.Tests/SIL.Archiving.Tests.csproj, SIL.Archiving/RampArchivingDlgViewModel.cs, SIL.Archiving/SIL.Archiving.csproj, SIL.DblBundle.Tests/BundleTests.cs, SIL.DblBundle.Tests/SIL.DblBundle.Tests.csproj, SIL.DblBundle.Tests/Text/TextBundleTests.cs, SIL.DblBundle/SIL.DblBundle.csproj, SIL.Windows.Forms.Archiving/SIL.Windows.Forms.Archiving.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1360)
=> Replaced dependency on DotNetZip with System.IO.Compression.ZipFile

SIL.Windows.Forms.Tests/Hotspot/HotSpotProviderTestForms.cs, SIL.Windows.Forms.Tests/Hotspot/MouseSimulator.cs, SIL.Windows.Forms.Tests/Miscellaneous/PortableClipboardTests.cs
These tests formerly relied on clipboard access or Application.DoEvents and actual mouse positions and timing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1365)
=> Improved unit tests to eliminate spurious failures

SIL.Core.Desktop.Tests/Progress/Commands/CommandTests.cs, SIL.Windows.Forms/SIL.Windows.Forms.csproj, build/Palaso.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1363)
=> Upgraded SIL.BuildTasks used in .proj file. Removed dependency on it from SIL.Windows.Forms

CHANGELOG.md, Palaso.sln.DotSettings, SIL.DblBundle/DblMetadata.cs, SIL.TestUtilities/FluentAssertXml.cs
Also fixed a typo in DblMetadata
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1373)
=> Made FluentAssertXml classes use "Assert.That" so they can work in clients that use NUnit 4.

SIL.Windows.Forms.Keyboarding.Tests/KeyboardControllerTests.cs, SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj, SIL.Windows.Forms.Keyboarding/KeyboardController.cs, SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj, SIL.Windows.Forms.WritingSystems.Tests/SIL.Windows.Forms.WritingSystems.Tests.csproj, SIL.Windows.Forms.WritingSystems/SIL.Windows.Forms.WritingSystems.csproj, SIL.Windows.Forms/ImageToolbox/PalasoImage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1366)
=> Net8windows keyboarding and writing systems

CHANGELOG.md, SIL.Windows.Forms/Miscellaneous/SILAboutBox.cs, TestApps/SIL.Windows.Forms.TestApp/TestAppForm.cs
Probably never matters for production builds, which start clean each time, but using the creation time makes the build date look wrong for local builds where the entry assembly is merely updated by the build and not re-created.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1374)
=> Changed build date in SILAboutBox to be computed using the last write time

CHANGELOG.md, SIL.Windows.Forms/ClearShare/WinFormsUI/ContributorsListControl.cs, SIL.Windows.Forms/ClearShare/WinFormsUI/FadingMessageForm.cs, TestApps/SIL.Windows.Forms.TestApp/TestAppForm.Designer.cs, TestApps/SIL.Windows.Forms.TestApp/TestAppForm.cs, TestApps/SIL.Windows.Forms.TestApp/TestAppForm.resx
This fixes crashes like SP-2340
I have marked this as a breaking change because of the removal of protected members, but I know of no derived classes, and in practice, the existing implementation was such that these members would be unlikely to have been meaningful or helpful in a derived class anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1375)
=> Made FadingMessageWindow implement all UI logic on the UI thread

CHANGELOG.md, SIL.Core.Tests/Threading/GlobalMutexTests.cs, SIL.Core/Threading/GlobalMutex.cs
On Linux, snap package confinement prevents reading and writing from many places in the system. That includes `/var/lock` which is used by GlobalMutex. We need a way to disable GlobalMutex in these situations. This PR provides an environment variable that can be set which makes GlobalMutex no longer global. It sill does some locking, though, in case something within the same process relies on a GlobalMutex for local locking.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1378)
=> +semver:minor Add environment variable to disable `GlobalMutex` across processes

CHANGELOG.md, SIL.WritingSystems/Resources/ianaSubtagRegistry.txt
Followed the instructions on https://github.com/sillsdev/libpalaso/tree/master/SIL.WritingSystems#silwritingsystems-library:
- langtags.json is from 2024-06-03
- ianaSubtagRegistry.txt is from 2025-02-06
Fixes #1084
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1393)
=> [SIL.WritingSystems] Update langtags.json, ianaSubtagRegistry.txt

CHANGELOG.md, SIL.WritingSystems.Tests/GlobalWritingSystemRepositoryTests.cs, SIL.WritingSystems.Tests/LdmlDataMapperTests.cs, SIL.WritingSystems.Tests/Migration/LdmlInFolderWritingSystemRepositoryMigratorTests.cs, SIL.WritingSystems/FontDefinition.cs, SIL.WritingSystems/LdmlDataMapper.cs
Resolves #1212 (implementing https://github.com/sillsdev/libpalaso/issues/1212#issuecomment-1282380561)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1389)
=> +semver:major [SIL.WritingSystems] Add UI font role

CHANGELOG.md, Palaso.sln.DotSettings, SIL.Windows.Forms.WritingSystems.Tests/Tree/WritingSystemVariantSuggestorTests.cs, SIL.Windows.Forms/ClearShare/ContributorsListControlViewModel.cs, SIL.Windows.Forms/ClearShare/WinFormsUI/ContributorsListControl.cs, SIL.Windows.Forms/ClearShare/WinFormsUI/ContributorsListControl.designer.cs, SIL.Windows.Forms/Extensions/ControlExtensions.cs, SIL.Windows.Forms/Widgets/BetterGrid/BetterGrid.cs, SIL.WritingSystems.Tests/IetfLanguageTagTests.cs, SIL.WritingSystems/Subtag.cs, TestApps/SIL.Windows.Forms.TestApp/ContributorsForm.Designer.cs, TestApps/SIL.Windows.Forms.TestApp/ContributorsForm.cs, TestApps/SIL.Windows.Forms.TestApp/ContributorsForm.resx
Made ContributorsListControl more threadsafe. Possibly fixes crashes like SP-2353 or at least makes them less likely.
Added ContributorsListControl.Initialize method to allow the model to be set later when using the (existing) parameterless constructor in Designer.
Made the TestApp's ContributorsForm able to be edited in Designer and added code to test accessing various methods and properties on ContributorsListControl from a non-UI thread
Also did some minor refactoring, comment/spelling cleanup, etc.
[WIP?] See REVIEW comment at line 259 in ContributorsListControl.cs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1401)
=> SP-2353 ContributorsListControl thread safety improvements

SIL.WritingSystems/IetfLanguageTag.cs, SIL.WritingSystems/LdmlDataMapper.cs, SIL.WritingSystems/Sldr.cs, SIL.WritingSystems/StandardSubtags.cs, SIL.WritingSystems/Subtag.cs
This replaces the former inefficient logic that rebuilt the whole dictionary on each add.
Fair bit of additional code cleanup/refactoring
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1399)
=> Changed StandardSubtags.AddLanguage to add the new entry to the Iso3Languages dictionary

.github/workflows/codeql.yml
To make the code-scanning more useful and less annoying, we can exclude all "note" severity queries. Drops us from ~2700 to 725 alerts: https://github.com/sillsdev/libpalaso/security/code-scanning?query=pr%3A1402+tool%3ACodeQL+is%3Aopen
Using documentation from:
- https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#example-configuration
- https://codeql.github.com/docs/writing-codeql-queries/metadata-for-codeql-queries/
- https://colinsalmcorner.com/fine-tuning-codeql-scans/#widening-the-filter
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1402)
=> Exclude all CodeQL code-scanning queries of "Note" severity

SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj, SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj, SIL.Windows.Forms.Tests/SIL.Windows.Forms.Tests.csproj, SIL.Windows.Forms/SIL.Windows.Forms.csproj
This is a test to see if it passes tests on Appveyor build
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1410)
=> Now that L10nsharp 8.0.0 is released, removed beta

SIL.Core/Xml/FastXmlElementSplitter.cs
Fixes https://github.com/sillsdev/libpalaso/security/code-scanning/2305, https://github.com/sillsdev/libpalaso/security/code-scanning/2306, https://github.com/sillsdev/libpalaso/security/code-scanning/2307, https://github.com/sillsdev/libpalaso/security/code-scanning/2308
These 4 instances of `throw new ArgumentException("Unmatched opening tag " + marker);` will throw with string `"Unmatched opening tag System.Byte[]"`, which isn't very helpful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1419)
=> [SIL.Core] Fix byte-array strings in FastXmlElementSplitter

.github/workflows/build.yml, CHANGELOG.md, SIL.Core.Tests/Extensions/DateTimeExtensionTests.cs, SIL.Core.Tests/IO/FileLocationUtilitiesTests.cs, SIL.Core/Extensions/DateTimeExtensions.cs, TestApps/CommandLineRunnerTestApp/CommandLineRunnerTestApp.csproj
This is kind of related to SP-2356, though it's not yet clear whether any actual logic changes will be needed in these date-handling methods.
Added test cases for ToISO8601TimeFormatWithUTCString and some unit tests for Made ParseDateTimePermissivelyWithException
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1422)
=> +semver:major  Made ParseDateTimePermissivelyWithException into an extension method

CHANGELOG.md
Closes #1434
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1436)
=> Changelog for the Keyman Legacy Bundle dependency

CHANGELOG.md, Palaso.sln, SIL.Windows.Forms/Clipboarding/IClipboard.cs, SIL.Windows.Forms/Clipboarding/LinuxClipboard.cs, SIL.Windows.Forms/Clipboarding/WindowsClipboard.cs, SIL.Windows.Forms/Miscellaneous/PortableClipboard.cs, TestApps/ClipboardTestApp/ClipboardTestApp.csproj, TestApps/ClipboardTestApp/Form1.Designer.cs, TestApps/ClipboardTestApp/Form1.cs, TestApps/ClipboardTestApp/Form1.resx, TestApps/ClipboardTestApp/Program.cs
Also restores and enhances the ClipboardTestApp. Most of it is restored after e3f8d8da748bed3a436f3c095b6d86d9dd52f526. I added the button and label for "paste any image" and "contains any image" which use the newer functions, and tweaked to show the whole image.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1438)
=> +semver:minor Added PortableClipboard.CanGetImage()

.github/workflows/update-language-data.yml, CHANGELOG.md, SIL.WritingSystems/Readme.md
* Also update the Readme
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1439)
=> Add a github workflow for updating language data

SIL.Core.Tests/Extensions/DateTimeExtensionTests.cs
* Run the test code which changes the calendar in an isolated thread. NUnit can re-use a thread even when [NonParellelizable] is set so this technique should avoid any cross test complications
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1447)
=> Fix flaky DateTimeExtension tests

SIL.Media.Tests/FFmpegRunnerTests.cs
Ensure tests don't step on each other.
Give developers a clue why tests fail if they have an old version of FFmpeg.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1453)
=> Stabilize FFmpeg tests

SIL.Core.Tests/Extensions/DateTimeExtensionTests.cs, SIL.Core/Extensions/DateTimeExtensions.cs
The tests that were previously commented out because of their dependency on certain current dates should now be reliable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1461)
=> SP-2356: Fixed flaky DateTimeExtensionTests
