sillsdev/libpalaso

- PalasoUIWindowsForms/ImageToolbox/AcquireImageControl.cs
Removing console line for resizing
ArtOfReading chooser size
> BL-911 HACK line appears on terminal

- Palaso.Media/ShortSoundFieldControl.cs
Try pulling into FlexBridgeBeta this time.
> LT-15375 Don't copy sound file if it's in the right place already

- Palaso.Tests/WritingSystems/IWritingSystemRepositoryTests.cs
NUnit test runner can handle tests in abstract base class, so we
can enable these tests.
Change-Id: I53c15391c03ca51e7939b0e3f44d07b079c50b1a
> Enable tests on Linux

- Palaso/Properties/AssemblyInfo.cs
- PalasoUIWindowsForms/Keyboarding/Interfaces/IKeyboardErrorDescription.cs
- PalasoUIWindowsForms/Keyboarding/InternalInterfaces/IKeyboardAdaptor.cs
- PalasoUIWindowsForms/Keyboarding/InternalInterfaces/IKeyboardControllerImpl.cs
- PalasoUIWindowsForms/Keyboarding/KeyboardController.cs
- PalasoUIWindowsForms/Keyboarding/KeyboardDescriptionNull.cs
- PalasoUIWindowsForms/Keyboarding/KeyboardErrorDescription.cs
- PalasoUIWindowsForms/Keyboarding/Linux/GlobalCachedInputContext.cs
- PalasoUIWindowsForms/Keyboarding/Linux/IbusKeyboardAdaptor.cs
- PalasoUIWindowsForms/Keyboarding/Linux/X11.cs
- PalasoUIWindowsForms/Keyboarding/Linux/XkbKeyboardAdaptor.cs
- PalasoUIWindowsForms/Keyboarding/Linux/XkbKeyboardDescription.cs
- PalasoUIWindowsForms/Keyboarding/Linux/XklConfigRegistry.cs
- PalasoUIWindowsForms/Keyboarding/Linux/XklEngine.cs
- PalasoUIWindowsForms/Keyboarding/Types/KeyboardCollection.cs
- PalasoUIWindowsForms/Keyboarding/Types/MouseEvent.cs
- PalasoUIWindowsForms/Properties/AssemblyInfo.cs
- Update copyright information for keyboarding code
- Cleanup KeyboardController interface
- update version numbers (see commit message for reasons)
> Various cleanup

- PalasoUIWindowsForms/Keyboarding/KeyboardController.cs
Bloom needs this in order to determine if it should activate jquery.longpress or not. KeyMan 9 doesn't play well with jquery.longpress.
> BL-1071: Added method to determine if an input processor is active

- PalasoUIWindowsForms.Tests/ImageToolbox/ImageToolboxTests.cs
- PalasoUIWindowsForms/ImageToolbox/AcquireImageControl.cs
Although not explicitly mentioned in the issue, this is part of
making Bloom work the same on both Linux and Windows with
regard to choosing an image file with the file chooser dialog.
(Getting thumbnail images to show is at the Mono library level, this
just uses reflection to get large icons instead of tiny ones.)
> Start OpenFileDialog with large icon view (BL-1021)

- Palaso/PlatformUtilities/Platform.cs
These are needed for fixing https://jira.sil.org/browse/BL-1147.
> Add checks for Wasta and Cinnamon in PlatformUtilities

- PalasoUIWindowsForms/Reporting/MemoryManagement.cs
Also allow higher limit for 64-bit processes with ample physical
memory.  (Currently only Linux supports 64-bit processes for our
code as far as I know.)
> Fix recent memory check work for Linux

- PalasoUIWindowsForms/Reporting/MemoryManagement.cs
Also try to clarify between process and system memory measurements.
> Tweak CheckMemory method to provide more information

- PalasoUIWindowsForms/ImageToolbox/PalasoImage.cs
This was leaking thousands of image files in Bloom.
> BL-2169: Stop leaking image files

- PalasoUIWindowsForms/ImageToolbox/PalasoImage.cs
The change did not work at all well on Linux: the copied Bitmap was
too different from the original Bitmap loaded from the file.
> Revert to using temp files for PalasoImage.FromFile

- PalasoUIWindowsForms/Reporting/ExceptionReportingDialog.cs
(BL-2247: Bloom needs to reword this since now using YouTrack)
> Make it possible for clients to configure the privacy notice

- PalasoUIWindowsForms/ImageToolbox/ImageToolboxControl.cs
This fixes https://silbloom.myjetbrains.com/youtrack/issue/BL-2354.
> Fix display of meta-information in ImageToolboxControl

- Palaso.Tests/WritingSystems/DefaultKeyboardDefinitionTests.cs
- Palaso.Tests/WritingSystems/RFC5646TagTests.cs
- Palaso.Tests/WritingSystems/WritingSystemDefinitionPropertyTests.cs
- PalasoUIWindowsForms.Tests/Keyboarding/KeyboardDescriptionTests.cs
- PalasoUIWindowsForms/WritingSystems/WritingSystemSetupModel.cs
Also switched some of the ValuesToSet in the ICloneableGeneric
tests.
> Some reformatting

- Palaso.Tests/Code/IClonableGenericTests.cs
- Palaso.Tests/WritingSystems/DefaultKeyboardDefinitionTests.cs
- Palaso/WritingSystems/DefaultKeyboardDefinition.cs
- PalasoUIWindowsForms.Tests/ErrorReporting/ErrorReportingTests.cs
- PalasoUIWindowsForms.Tests/Keyboarding/IbusKeyboardAdaptorTests.cs
- PalasoUIWindowsForms.Tests/Keyboarding/IbusKeyboardDescriptionTests.cs
- PalasoUIWindowsForms.Tests/Keyboarding/KeyboardDescriptionTests.cs
- PalasoUIWindowsForms.Tests/Keyboarding/WinKeyboardDescriptionTests.cs
- PalasoUIWindowsForms.Tests/PalasoUIWindowsForms.Tests.csproj
- PalasoUIWindowsForms/Keyboarding/Linux/CinnamonIbusAdaptor.cs
- PalasoUIWindowsForms/Keyboarding/Linux/CombinedKeyboardAdaptor.cs
- PalasoUIWindowsForms/Keyboarding/Linux/IbusKeyboardAdaptor.cs
- PalasoUIWindowsForms/Keyboarding/Linux/IbusKeyboardDescription.cs
Various fixes and improvements to keyboarding code (see individual commits for details)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/259)
> Keyboarding

- Palaso/Reporting/ErrorReport.cs
See https://silbloom.myjetbrains.com/youtrack/issue/BL-2418 for the
justification of this added functionality.
> Expose standard properties for analytics use.

- Palaso.Media/AlsaAudio/AlsaAudioDevice.cs
- Palaso.Media/AlsaAudio/AudioAlsaSession.cs
- Palaso.Media/AudioFactory.cs
- Palaso.Media/AudioIrrKlangSession.cs
- Palaso.Media/ShortSoundFieldControl.cs
If bit rate is 0, defer to the OS.
> Check bit rate before trying to play a sound

- Palaso.Tests/Email/LinuxEmailProviderTests.cs
- Palaso.Tests/Palaso.Tests.csproj
- Palaso/Email/LinuxEmailProvider.cs
> Escape quotes and backslashes passed to xdg-email

- SIL.Archiving/Generic/ArchivingFileSystem.cs
On Linux we should use /var/lib instead of /usr/share (which is the
default for CommonApplicationData). Additionally, /var/lib might not
be writable. This change tries to use /var/lib/SIL. If that folder
can't be created, we use a subfolder in ApplicationData instead
(default: $HOME/.config/SIL).
> Adjust archiving path for Linux

- PalasoUIWindowsForms/SettingProtection/SettingsProtectionHelper.Designer.cs
- PalasoUIWindowsForms/SettingProtection/SettingsProtectionHelper.cs
- PalasoUIWindowsForms/Widgets/BitmapButton.cs
* Dispose of temporary bitmaps as well as the Disabled grey
scale bitmaps in BitmapButton
* Dispose of SettingsProtectionHelper components and timer
> Add missing dispose calls to fix program hangs on Linux

- PalasoUIWindowsForms.Tests/Keyboarding/CombinedIbusKeyboardSwitchingAdaptorTests.cs
- PalasoUIWindowsForms.Tests/Keyboarding/IbusKeyboardAdaptorTests.cs
- PalasoUIWindowsForms.Tests/PalasoUIWindowsForms.Tests.csproj
- PalasoUIWindowsForms/Keyboarding/KeyboardController.cs
- PalasoUIWindowsForms/Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs
- PalasoUIWindowsForms/Keyboarding/Linux/CombinedIbusKeyboardSwitchingAdaptor.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/270)
> Add tests for CombinedIbusKeyboardSwitchingAdaptor.DefaultKeyboard

- Palaso.Tests/PlatformUtilities/PlatformTests.cs
- Palaso/PlatformUtilities/Platform.cs
- PalasoUIWindowsForms/Keyboarding/Linux/CombinedIbusKeyboardSwitchingAdaptor.cs
- PalasoUIWindowsForms/Keyboarding/Linux/XkbKeyboardRetrievingAdaptor.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/274)
> More Keyboarding fixes

- PalasoUIWindowsForms/Keyboarding/Linux/IbusKeyboardSwitchingAdaptor.cs
Certain keys like backspace, the arrow keys and page up/down are
handled by ibus when a pre-edit window is active. Those keys
shouldn't close the pre-edit window.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/280)
> Fix handling of backspace for Chinese ibus IME (FWNX-1324)

- PalasoUIWindowsForms/ImageToolbox/Cropping/ImageCropper.cs
while disposing of ImageCropper
> BL-2680, ignore problems deleting temp files

- DistFiles/Palaso.en.tmx
- PalasoUIWindowsForms/Extensions/ToolStripExtensions.cs
- PalasoUIWindowsForms/ImageGallery/ArtOfReadingImageCollection.cs
- PalasoUIWindowsForms/ImageGallery/IImageCollection.cs
- PalasoUIWindowsForms/ImageToolbox/ArtOfReadingChooser.Designer.cs
- PalasoUIWindowsForms/ImageToolbox/ArtOfReadingChooser.cs
- PalasoUIWindowsForms/ImageToolbox/ArtOfReadingChooser.resx
- PalasoUIWindowsForms/PalasoUIWindowsForms.csproj
- PalasoUIWindowsForms/Widgets/TextInputBox.cs
This implements https://silbloom.myjetbrains.com/youtrack/issue/BL-2481.
> Add GUI selection of index language for Art of Reading chooser

- PalasoUIWindowsForms/ImageGallery/ArtOfReadingImageCollection.cs
- PalasoUIWindowsForms/ImageToolbox/ArtOfReadingChooser.Designer.cs
- PalasoUIWindowsForms/ImageToolbox/ArtOfReadingChooser.cs
This addresses https://silbloom.myjetbrains.com/youtrack/issue/BL-2728.
> Fix Art of Reading chooser for old version of AOR

- PalasoUIWindowsForms/Keyboarding/Linux/IbusKeyboardSwitchingAdaptor.cs
When IBus didn't handle the key we should let the control deal with
the keypress. This fixes the problem when typing with Korean Hangul
keyboard it was not possible to backspace past the beginning of the
pre-edit. This change makes it possible, although there is still a
slight problem in that when backspacing over the first character
in the pre-edit the display doesn't get updated, but when backspacing
again the first character in the pre-edit and the character before
that get deleted (as it should be, but the visual indication is
wrong).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/290)
> Fix backspacing with Korean IBus keyboard

- .gitignore
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/291)
> Add Spart.dll to .gitignore

- PalasoUIWindowsForms/Widgets/BetterLabel.cs
- PalasoUIWindowsForms/Widgets/BetterLabel.designer.cs
I would be glad to hear if anyone has a better name for CanSelectText
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/293)
> Betterlabel

- PalasoUIWindowsForms.GeckoFxWebBrowserAdapter/GeckoFxWebBrowserAdapter.cs
- PalasoUIWindowsForms.GeckoFxWebBrowserAdapter/WebThumbnailViewer.cs
- PalasoUIWindowsForms/HtmlBrowser/IWebBrowserCallbacks.cs
- PalasoUIWindowsForms/HtmlBrowser/XWebBrowser.cs
- PalasoUIWindowsForms/PalasoUIWindowsForms.csproj
- PalasoUIWindowsForms/Widgets/HtmlLabel.Designer.cs
- PalasoUIWindowsForms/Widgets/HtmlLabel.cs
- PalasoUIWindowsForms/Widgets/HtmlLabel.resx
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/294)
> Html label

- BuildTaskTests/GenerateReleaseArtifactsTests.cs
- BuildTaskTests/Palaso.BuildTask.Tests.csproj
- Palaso.MSBuildTasks/GenerateReleaseArtifacts.cs
- Palaso.MSBuildTasks/Palaso.BuildTasks.csproj
- Palaso.MSBuildTasks/packages.config
The task uses a markdown file and a version number as input
* Optionally stamp the markdown file with latest version and release
* Generate html file (or element) from the markdown file
* Generate new changelog entry from the latest markdown entry
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/296)
> Add build task for generating release artifacts

- Palaso.Tests/CommandLineProcessing/CommandLineRunnerTests.cs
- Palaso.Tests/Progress/ConsoleProgressTests.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/297)
> Remove two tests that fail intermittently from TC consideration

- BuildTaskTests/GenerateReleaseArtifactsTests.cs
- Palaso.MSBuildTasks/GenerateReleaseArtifacts.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/298)
> Fix minor format problems in author line for the debian changelog

- Palaso/WritingSystems/DefaultKeyboardDefinition.cs
- Palaso/WritingSystems/IKeyboardDefinition.cs
- PalasoUIWindowsForms.Tests/Keyboarding/WinKeyboardDescriptionTests.cs
- PalasoUIWindowsForms.Tests/UniqueToken/UniqueTokenTests.cs
- PalasoUIWindowsForms/Keyboarding/KeyboardDescriptionNull.cs
- PalasoUIWindowsForms/Keyboarding/Windows/KeymanKeyboardDescription.cs
- PalasoUIWindowsForms/Keyboarding/Windows/WinKeyboardDescription.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/300)
> Add UseNfcContext property (part of fix for LT-16637)

- SIL.DblBundle.Tests/Properties/Resources.Designer.cs
- SIL.DblBundle.Tests/Properties/Resources.resx
- SIL.DblBundle.Tests/Resources/TestBundleFiles/ldml.xml
- SIL.DblBundle.Tests/SIL.DblBundle.Tests.csproj
- SIL.DblBundle.Tests/Text/TextBundleTests.cs
- SIL.DblBundle/Bundle.cs
- SIL.DblBundle/SIL.DblBundle.csproj
- SIL.DblBundle/Text/TextBundle.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/302)
> Get LDML from bundle if it exists (PG-259)

- Palaso/IO/TempFile.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/303)
> Add Detach() to TempFile

- Palaso/IO/FileUtils.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/304)
> Msg on denied file writes now includes read only & file permissions

- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupDialog.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs
- SIL.WritingSystems/LanguageInfo.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/305)
> Changes need to get Bloom working again after merge

- SIL.Windows.Forms/ImageGallery/ThumbnailViewer.cs
* reflection was referencing the old namespace system
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/307)
> Fix ThumbnailViewer (BL-2901)

- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/308)
> Fix null ref in LanguageLookupControl

- SIL.Core/Reporting/ErrorReport.cs
- SIL.Core/Reporting/ExceptionHandler.cs
- SIL.Windows.Forms.GeckoBrowserAdapter/Properties/AssemblyInfo.cs
- SIL.Windows.Forms/Extensions/ToolStripExtensions.cs
- SIL.Windows.Forms/ImageGallery/ThumbnailViewer.cs
- SIL.Windows.Forms/Widgets/TextInputBox.cs
- TestApps/SIL.Windows.Forms.TestApp/Properties/Settings.settings
* mostly comments
* one variable renaming
* TextInputBox had the same reflection problems fixed
earlier in ThumbnailViewer
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/309)
> Change remaining refs to PalasoUIWindowsForms

- SIL.Core/Settings/CrossPlatformSettingsProvider.cs
- SIL.Windows.Forms.Tests/SettingsProviderTests.cs
- SIL.Windows.Forms/Registration/RegistrationSettingsProvider.cs
* updated CrossPlatformSettingsProvider to rename section names during upgrade
* updated RegistrationSettingsProvider to provide renamed sections
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/321)
> Properly upgrade renamed registration settings

- SIL.WritingSystems.Tests/Migration/GlobalWritingSystemRepositoryMigratorTests.cs
- SIL.WritingSystems/GlobalWritingSystemRepository.cs
- SIL.WritingSystems/Migration/GlobalWritingSystemRepositoryMigrator.cs
* updated GlobalWritingSystemRepositoryMigrator to migrate LDML files from old location on Linux
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/320)
> Change global WS repo on Linux to "~/.local/share"

- SIL.TestUtilities/OfflineSldr.cs
- SIL.TestUtilities/OfflineSldrAttribute.cs
- SIL.TestUtilities/SIL.TestUtilities.csproj
Add a class to enable offline mode for the SLDR, in addition to the existing NUnit action attribute.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/326)
> Add OfflineSldr class to enable offline mode for the SLDR in test setup methods

- SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs
- SIL.Windows.Forms/ImageToolbox/ImageToolboxDialog.Designer.cs
- SIL.Windows.Forms/ImageToolbox/ImageToolboxDialog.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/327)
> More plumbing to let client of ImageToolBox read SearchLanguage

- SIL.Core/Reporting/ErrorReport.cs
- SIL.Core/Reporting/ExceptionHelper.cs
- SIL.Core/Reporting/Logger.cs
Add a few methods that are needed for FW so that the duplicated
code in FW can be removed.
This change adds the following methods: Logger.WriteError,
ExceptionHelper.GetHiearchicalExceptionInfo, .GetExceptionText,
and .LogAndIgnoreErrors. ErrorReport will use these new methods.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/331)
> Enhance Logger and ExceptionHelper classes

- SIL.Core/SIL.Core.csproj
- SIL.Core/Settings/README
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/335)
> Cleanup readme for CrossPlatformSettingsProvider

- SIL.Core/Reporting/Logger.cs
This change adds a new overload for Init() that takes a prefix for
the log file. This is needed for FieldWorks where a new process gets
started when a new project gets opened. Without this change the log
file of the previously started instance would be overwritten when
opening a new project.
Also a little bit of cleanup (moving a method and static variable
around that accidentally got added in the IDisposable region).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/334)
> Allow to set prefix for logging

- SIL.Core/IO/DirectoryUtilities.cs
If a directory is created by an administrator in ProgramData, the default
access is read-only for non-admin users
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/339)
> PG-433: Add function to set permission to 'full control' for everyone

- SIL.Windows.Forms/ClearShare/MetaData.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/343)
> Improve name of new method

- SIL.Core/Reporting/Logger.cs
This is useful when running tests where we might init and shutdown
the logger multiple times, but don't want to overwrite the log file
each time.
Also fix a bug where passing a different logfilePrefix didn't
change the name of the logfile if the name was set previously.
Fix a bug where the WriteEventCore call in the c'tor failed because
the singleton variable wasn't set yet.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/348)
> Allow to append to log file

- Palaso.MSBuildTasks/FileUpdate.cs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/358)
> Improve FileUpdate build task to accept date format for output

- SIL.TestUtilities/FluentAssertXml.cs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/360)
> Dispose writer when done

- SIL.Windows.Forms.DblBundle/ProjectsListBase.Designer.cs
- SIL.Windows.Forms.DblBundle/ProjectsListBase.cs
- SIL.Windows.Forms.DblBundle/ProjectsListBase.resx
* Was calling PrepareToSort twice, causing the Debug.Assert to fail.
* Was causing the OnDoubleClick event to be raised.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/361)
> Fix problems when user double-clicks column header

- SIL.Windows.Forms.DblBundle/ProjectsListBase.Designer.cs
- SIL.Windows.Forms.DblBundle/ProjectsListBase.cs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/362)
> Add grid changed events to DBL project dialog

- SIL.DblBundle/Text/DblTextMetadata.cs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/364)
> Return Unknown, not qaa, for DblMetadataLanguage.ToString (PG-581)

- Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs
This is based on changes that are already in master branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/365)
> Fix crash in USB disk handling

- SIL.Core.Tests/Extensions/CollectionExtensionsTests.cs
- SIL.Core.Tests/ObjectModel/NullableValueTests.cs
- SIL.Core.Tests/ObjectModel/UnorderedTupleTests.cs
- SIL.Core.Tests/SIL.Core.Tests.csproj
- SIL.Core/Extensions/CollectionExtensions.cs
- SIL.Core/Extensions/ComparerExtensions.cs
- SIL.Core/ObjectModel/AnonymousComparer.cs
- SIL.Core/ObjectModel/AnonymousEqualityComparer.cs
- SIL.Core/ObjectModel/NullableValue.cs
- SIL.Core/ObjectModel/ProjectionComparer.cs
- SIL.Core/ObjectModel/ProjectionEqualityComparer.cs
- SIL.Core/ObjectModel/ReferenceEqualityComparer.cs
- SIL.Core/ObjectModel/ReverseComparer.cs
- SIL.Core/ObjectModel/SequenceComparer.cs
- SIL.Core/ObjectModel/SequenceEqualityComparer.cs
- SIL.Core/ObjectModel/StructuralEqualityComparer.cs
- SIL.Core/ObjectModel/UnorderedTuple.cs
- SIL.Core/ObjectModel/WrapperEqualityComparer.cs
- SIL.Core/SIL.Core.csproj
* added various comparers and equality comparers
* added UnorderedTuple
* added NullableValue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/371)
> Add some useful classes to SIL.ObjectModel namespace

- SIL.Core.Tests/Unicode/CharacterUtilsTests.cs
- SIL.Core/Unicode/CharacterUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/375)
> Add Unicode category lookup to SIL.Unicode.CharacterUtils (PG-644)

- SIL.Windows.Forms/ImageToolbox/ArtOfReadingChooser.cs
This fixes https://silbloom.myjetbrains.com/youtrack/issue/BL-2753
(at least the part that wasn't already fixed).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/376)
> Fix message alignment in AOR dialog message

- SIL.DblBundle.Tests/Text/TextBundleTests.cs
- SIL.DblBundle/Text/TextBundle.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/377)
> Fail more gracefully when canon directory not found (PG-679)

- SIL.Core.Tests/IO/FileLocatorTests.cs
- SIL.Core/IO/FileLocator.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/378)
> BL-3352 Improve error reporting on missing directory

- SIL.Core.Tests/Unicode/CharacterUtilsTests.cs
- SIL.Core/Unicode/CharacterUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/380)
> PG-741: Add check for string ending with sentence final punctuation

- SIL.Core/Reporting/ExceptionHandler.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/379)
> Correct logic for initializing Windows Forms handlers by default if present

- SIL.Windows.Forms.WritingSystems/WSTree/WritingSystemSuggestion.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/381)
> Correct typo in Doulos SIL font name

- SIL.Windows.Forms/Widgets/BetterGrid/BetterGrid.cs
Added support for full column of delete buttons. Made it use the correct image to determine column width. Enabled user-deletion of rows that do not pass validation. Prevent auto-sizing the "remove row" column.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/384)
> Enhancements to BetterGrid

- SIL.Core/IO/TempFile.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/385)
> Do not crash if TempFile is unable to be deleted in Dispose (BL-3590)

- SIL.Windows.Forms/ReleaseNotes/ShowReleaseNotesDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/387)
> Set character encoding when displaying html from markdown (BL-3785)

- SIL.Windows.Forms/Miscellaneous/SILAboutBox.Designer.cs
- SIL.Windows.Forms/Miscellaneous/SILAboutBox.cs
- SIL.Windows.Forms/ReleaseNotes/ShowReleaseNotesDialog.Designer.cs
- SIL.Windows.Forms/ReleaseNotes/ShowReleaseNotesDialog.resx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/388)
> Correct I18N of SILAboutBox and ShowReleaseNotesDialog (BL-3795)

- SIL.Core.Tests/IO/TempFileForSafeWritingTests.cs
- SIL.Core/IO/RobustFile.cs
- SIL.Core/IO/TempFileForSafeWriting.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/389)
> Make TempFileForSafeWriting more robust by using RobustFile (BL-3665)

- DistFiles/Palaso.en.tmx
- SIL.Windows.Forms.Tests/ClearShare/CreativeCommonsLicenseTests.cs
- SIL.Windows.Forms/ClearShare/CreativeCommonsLicense.cs
- SIL.Windows.Forms/ClearShare/LicenseInfo.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorDialog.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/392)
> Enable "Intergovernmental" version of CreativeCommons license

- DistFiles/Palaso.en.tmx
- GlobalAssemblyInfo.cs
- SIL.Core.Tests/IO/TempFileForSafeWritingTests.cs
- SIL.Core/Code/RetryUtility.cs
- SIL.Core/IO/RobustFile.cs
- SIL.Core/IO/RobustIO.cs
- SIL.Core/IO/TempFileForSafeWriting.cs
- SIL.Core/Retry/RetryUtility.cs
- SIL.Core/SIL.Core.csproj
- SIL.TestUtilities/FluentAssertXml.cs
- SIL.Windows.Forms.Tests/ClearShare/CreativeCommonsLicenseTests.cs
- SIL.Windows.Forms/ClearShare/CreativeCommonsLicense.cs
- SIL.Windows.Forms/ClearShare/LicenseInfo.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorDialog.Designer.cs
- build/Palaso.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/396)
> Merge libpalaso-3.1 into master

- Palaso/IO/FileUtils.cs
- Palaso/Reporting/ErrorReport.cs
- PalasoUIWindowsForms/SIL/SILAboutBox.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/398)
> Add FileUtils.StripFilePrefix method

- Palaso.MSBuildTasks/UnitTestTasks/NUnit3.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/406)
> Add optional --teamcity argument for NUnit3 build task

- SIL.Core.Tests/IO/FileLock/SimpleFileLockTests.cs
- SIL.Core/IO/FileLock/SimpleFileLock.cs
- SIL.Windows.Forms.WritingSystems.Tests/WritingSystemSetupPMTests.cs
These are mostly related to the new FileLock code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/397)
> Fix some problems on Linux with failing tests

- BuildTaskTests/Palaso.BuildTask.Tests.csproj
- BuildTaskTests/UnitTestTasks/NUnit3Tests.cs
- Palaso.MSBuildTasks/UnitTestTasks/NUnit.cs
- Palaso.MSBuildTasks/UnitTestTasks/NUnit3.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/408)
> Add include and exclude category functionality for NUnit 3

- SIL.Windows.Forms/HtmlBrowser/XWebBrowser.cs
When we ilrepack/ilmerge assemblies the GeckoFxWebBrowserAdapter
class is in the executing assembly, so we try to get it from
there first. (It is important to ilrepack both SIL.Windows.Forms
and GeckoBrowserAdapter assemblies, otherwise the interface
definition will be different)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/409)
> Allow GeckoBrowserAdapter to work when ilrepacked/ilmerged

- SIL.WritingSystems.Tests/LanguageLookupTests.cs
- SIL.WritingSystems/LanguageLookup.cs
This fixes #419
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/420)
> Filter out pejorative alternative names

- SIL.WritingSystems.Tests/LanguageLookupTests.cs
- SIL.WritingSystems/LanguageLookup.cs
- SIL.WritingSystems/Resources/LanguageIndex.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/421)
> Temporarily omit some language names for Ethiopia

- Palaso.MSBuildTasks/UnitTestTasks/NUnit.cs
- Palaso.MSBuildTasks/UnitTestTasks/NUnit3.cs
- Palaso.MSBuildTasks/UnitTestTasks/TestTask.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/424)
> Add option to unit test build task to fail if a test fails (BL-4087)

- SIL.Core/PlatformUtilities/Platform.cs
This fixes a strange problem in the Bloom alpha that prevents the image toolbox dialog from
appearing.  (http://issues.bloomlibrary.org/youtrack/issue/BL-4076)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/425)
> Fix Linux Platform.SessionManager to work reliably.

- .gitignore
- Palaso/Palaso.csproj
- Palaso/packages.config
- PalasoUIWindowsForms/PalasoUIWindowsForms.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/426)
> Get icu.net from nuget package

- BuildTaskTests/UnitTestTasks/NUnit3Tests.cs
- Palaso.MSBuildTasks/UnitTestTasks/NUnit.cs
- Palaso.MSBuildTasks/UnitTestTasks/NUnit3.cs
Made this change as a result of comments during code review for PR424 which had already been merged
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/427)
> Default NUnit3.FailTaskIfAnyTestsFail to true if TeamCity true (BL-4087)

- .gitignore
- BuildTaskTests/Palaso.BuildTask.Tests.Helper/Palaso.BuildTask.Tests.Helper.csproj
- BuildTaskTests/Palaso.BuildTask.Tests.Helper/Tests.cs
- BuildTaskTests/Palaso.BuildTask.Tests.Helper/packages.config
- BuildTaskTests/Palaso.BuildTask.Tests.csproj
- BuildTaskTests/UnitTestTasks/NUnitTests.cs
- Palaso.MSBuildTasks/UnitTestTasks/TestTask.cs
- Palaso.sln
The previous code used a wrong assumption. NUnit will report failed
tests as warnings not as errors. The previous code didn't fail the
build when we got exceptions from the finalizer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/428)
> Fail the build if NUnit task logged errors

- Palaso/Palaso.csproj
- Palaso/packages.config
- PalasoUIWindowsForms/PalasoUIWindowsForms.csproj
- PalasoUIWindowsForms/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/431)
> Update icu.net to 2.0.1

- SIL.Media/AlsaAudio/AlsaAudioDevice.cs
- SIL.Media/AlsaAudio/AudioAlsaSession.cs
This is used by some work I'm doing in Bloom.  Existing code will continue to work the same without modification.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/432)
> Enhance Alsa based sound recording to be more adjustable

- SIL.Media/AlsaAudio/AudioRecorder.cs
- SIL.Media/AlsaAudio/RecordingDevice.cs
- SIL.Media/AlsaAudio/WaveFormat.cs
- SIL.Media/Naudio/AudioRecorder.cs
- SIL.Media/Naudio/IAudioRecorder.cs
- SIL.Media/SIL.Media.csproj
(minimal implementation for Bloom)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/433)
> Implement AudioRecorder class for Linux

- SIL.Windows.Forms/ImageToolbox/PalasoImage.cs
* maintains image metadata
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/438)
> Add a Robust Save method to PalasoImage

- SIL.Core/IO/FileUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/439)
> Fix ReplaceFileWithUserInteractionIfNeeded for network drive (BL-4179)

- SIL.WritingSystems/Resources/LanguageDataIndex.txt
- SIL.WritingSystems/Resources/LanguageIndex.txt
- SIL.WritingSystems/Resources/ianaSubtagRegistry.txt
These are the new iana subtag and ethnologue files. They have been requested.
Using them it still passes all the tests including for pejorative names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/442)
> Jan 2017 iana, ethnologue and LanguageDataIndex

- SIL.Windows.Forms.Tests/ClearShare/MetadataTests.cs
- SIL.Windows.Forms/ClearShare/CreativeCommonsLicense.cs
- SIL.Windows.Forms/ClearShare/LicenseInfo.cs
- SIL.Windows.Forms/ClearShare/MetaData.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/446)
> Add MetaData.MinimalCredits()

- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs
- SIL.Windows.Forms/Widgets/BetterLinkLabel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/445)
> Prevent BetterLinkLabel from defaulting to disabled (BL-4215)

- SIL.Windows.Forms/ClearShare/MetaData.cs
See http://issues.bloomlibrary.org/youtrack/issue/BL-4244.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/455)
> Add "Additional Requests" string to license summary paragraph

- Palaso.Tests/WritingSystems/EthnologueLookupTests.cs
- Palaso/Resources/LanguageIndex.txt
- Palaso/WritingSystems/EthnologueLookup.cs
this applies JH's changes adapted for the libpalaso-2.6 branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/451)
> Libpalaso 2.6 remove pejorative languages

- SIL.WritingSystems.Tests/LanguageLookupTests.cs
- SIL.WritingSystems/LanguageLookup.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/460)
> Add LanguageLookup.GetLanguageFromCode()

- SIL.Core/Reporting/Logger.cs
Following a pattern in WriteMinorEventCore, don't use message
as a format string if no args, and catch any problem formatting
the error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/463)
> Cope with braces in Logger.WriteError message

- DistFiles/Palaso.en.tmx
- DistFiles/Palaso.es.tmx
- DistFiles/Palaso.fr.tmx
- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.Designer.cs
- TestApps/SIL.Windows.Forms.TestApp/Program.cs
- TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj
http://issues.bloomlibrary.org/youtrack/issue/BL-4396#u=1488995842399
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/468)
> Remove '?' in language search box when ui lang is non-english

- SIL.Core.Tests/IO/RobustFileTests.cs
- SIL.Core.Tests/SIL.Core.Tests.csproj
- SIL.Core/IO/RobustFile.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/467)
> BL-4030 Make RobustFile use WriteThrough

- SIL.Core/IO/FileUtils.cs
- SIL.Core/IO/RobustFile.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/469)
> Make RobustFile.Replace handle mapped network drives (BL-4436)

- SIL.Windows.Forms.GeckoBrowserAdapter/WebThumbnailViewer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/472)
> BL-4492 make thumbnailer use charset for empty page

- SIL.Archiving/ArchivingDlg.Designer.cs
- SIL.Archiving/ArchivingDlg.cs
- SIL.Archiving/ArchivingDlg.resx
- SIL.Archiving/ArchivingDlgViewModel.cs
- SIL.Archiving/IMDI/IMDIArchivingDlgViewModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/477)
> Added IMDI archiving metadata-only option

- SIL.Windows.Forms/Extensions/ControlExtensions.cs
- SIL.Windows.Forms/Progress/LogBox.cs
This method was based on implementations in LogBox, Glyssen, and BloomDesktop, plus insights from MSDN and SO. Note that it represents a definite change to the implementation in LogBox (which I removed). TimS and I studied it and feel like it is a slight improvement in that it is actually checking IsDisposed on the correct control, rather than the LogBox itself. But it does get away from using the SynchronizationContext, which Microsoft argues is actually the best way to handle synchronization. I left in place the apparently redundant try-catch blocks in the calling code, somewhat against my better judgment (but scared off by the confusing comments there). I did test it in HearThis, but not in WeSay (or any other clients).
---
This change is [<img …
> Added SafeInvoke method to ControlExtensions

- GlobalAssemblyInfo.cs
- build/Palaso.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/485)
> Move to version 4.0

- SIL.Media.Tests/AudioPlayerTests.cs
- SIL.Media.Tests/AudioRecorderTests.cs
- SIL.Media.Tests/FFmpegRunnerTests.cs
- SIL.Media.Tests/MediaInfoTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/479)
> Disables various failing tests in SIL.Media.Tests

- SIL.WritingSystems.Tests/LanguageLookupTests.cs
- SIL.WritingSystems/LanguageLookup.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/489)
> Lookup languages by country as well as name

- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.Designer.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupDialog.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/491)
> Hide alt names

- SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs
- SIL.Windows.Forms.Tests/SIL.Windows.Forms.Tests.csproj
- SIL.Windows.Forms/Extensions/ControlExtensions.cs
- SIL.Windows.Forms/Reporting/WinFormsExceptionHandler.cs
on PR #480 and added unit tests, which showed need for additional improvements to improve robustness and handle edge cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/486)
> Improved the SafeInvoke method in response to JohnT's feedback

- SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/496)
> Attempt to improve timing and diagnostics to make tests pass reliably on Linux

- SIL.Archiving/Properties/AssemblyInfo.cs
- SIL.Core.Tests/Acknowledgements/AcknowledgementAttributeTests.cs
- SIL.Core.Tests/Acknowledgements/AcknowledgementsProviderTests.cs
- SIL.Core.Tests/SIL.Core.Tests.csproj
- SIL.Core/Acknowledgements/AcknowledgementAttribute.cs
- SIL.Core/Acknowledgements/AcknowledgementsProvider.cs
- SIL.Core/Properties/AssemblyInfo.cs
- SIL.Core/SIL.Core.csproj
- SIL.DblBundle/Properties/AssemblyInfo.cs
- SIL.Windows.Forms.Tests/Miscellaneous/SILAboutBoxTests.cs
- SIL.Windows.Forms.Tests/SIL.Windows.Forms.Tests.csproj
- SIL.Windows.Forms/Miscellaneous/SILAboutBox.cs
- TestApps/SIL.Windows.Forms.TestApp/Properties/AssemblyInfo.cs
- TestApps/SIL.Windows.Forms.TestApp/TestAppForm.cs
* add AcknowledgementAttribute class and tests
* add AcknowledgementsProvider class
* setup SILAboutBox to pull in Acknowl. Attributes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/487)
> Add AcknowledgementsProvider to SIL.Core

- Palaso.sln
- SIL.Archiving.Tests/IMDIArchivingDlgViewModelTests.cs
- SIL.Media.Tests/AudioRecorderTests.cs
- SIL.Media.Tests/SampleForm.cs
- SIL.Windows.Forms.GeckoBrowserAdapter/ProgressUtils.cs
- SIL.Windows.Forms.Tests/SettingsProviderTests.cs
- SIL.Windows.Forms/ImageGallery/PictureChooser.cs
- SIL.Windows.Forms/ImageGallery/ThumbnailViewer.cs
- SIL.Windows.Forms/ImageToolbox/AcquireImageControl.cs
- SIL.Windows.Forms/ImageToolbox/ArtOfReadingChooser.cs
- SIL.Windows.Forms/ImageToolbox/Cropping/Grip.cs
- SIL.Windows.Forms/Spelling/TextBoxSpellChecker.cs
- SIL.Windows.Forms/Widgets/HtmlLabel.cs
- SIL.Windows.Forms/Widgets/TextInputBox.cs
These are the most simple and safe
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/498)
> First round of changes to get rid of compiler warnings

- build/Palaso.proj
The NUnitTeamCity task has issues when run with mono-4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/503)
> Use NUnitAddin instead of NUnitTeamCity task on TC

- LanguageData/Properties/AssemblyInfo.cs
- Palaso.MSBuildTasks/Palaso.BuildTasks.csproj
- Palaso.MSBuildTasks/Properties/AssemblyInfo.cs
- SIL.Archiving/Properties/AssemblyInfo.cs
- SIL.Core/Acknowledgements/AcknowledgementAttribute.cs
- SIL.Core/Properties/AssemblyInfo.cs
- SIL.DblBundle/Properties/AssemblyInfo.cs
- SIL.DictionaryServices/Properties/AssemblyInfo.cs
- SIL.Lift/Properties/AssemblyInfo.cs
- SIL.Linux.Logging/Properties/AssemblyInfo.cs
- SIL.Media/Properties/AssemblyInfo.cs
- SIL.TestUtilities/Properties/AssemblyInfo.cs
- SIL.Windows.Forms.DblBundle/Properties/AssemblyInfo.cs
- SIL.Windows.Forms.DblBundle/SIL.Windows.Forms.DblBundle.csproj
- SIL.Windows.Forms.Keyboarding/Properties/AssemblyInfo.cs
- SIL.Windows.Forms.WritingSystems/Properties/AssemblyInfo.cs
- SIL.Windows.Forms/Miscellaneous/SILAboutBox.Designer.cs
- SIL.Windows.Forms/Properties/AssemblyInfo.cs
- SIL.WritingSystems/Properties/AssemblyInfo.cs
* LanguageData
* Palaso.MSBuildTasks
* SIL.Core
* SIL.DictionaryServices
* SIL.Lift
* SIL.Media
* SIL.TestUtilities (should we do Test projects?)
* SIL.Windows.Forms
* SIL.Windows.Forms.DblBundle
* SIL.Windows.Forms.Keyboarding
* SIL.Windows.Forms.WritingSystems
* SIL.WritingSystems
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/499)
> Update AssemblyInfo files with Acknowledgements

- SIL.Windows.Forms.Keyboarding.Tests/KeyboardControllerTests.cs
- SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/509)
> Make KeyboardController tests OS Independant

- SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageCollectionManager.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/513)
> Fix unit test on (single core?) machines by waiting for all image indices to load

- SIL.DictionaryServices.Tests/Lift/LiftRepositoryTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/515)
> Improve test

- SIL.Core/Annotations/Annotation.cs
- SIL.Core/CommandLineProcessing/AsyncProcessOutputReader.cs
- SIL.Core/CommandLineProcessing/SynchronousProcessOutputReader.cs
- SIL.Core/Data/MemoryDataMapper.cs
- SIL.Core/IO/FileLocator.cs
- SIL.Core/IO/PathUtilities.cs
- SIL.Core/IO/TempFile.cs
- SIL.Core/Migration/FileMigrator.cs
- SIL.Core/Migration/FolderMigrator.cs
- SIL.Core/Migration/MigratorBase.cs
- SIL.Core/Text/LanguageForm.cs
- SIL.DictionaryServices/Lift/LiftReader.cs
- SIL.DictionaryServices/Lift/LiftWriter.cs
- SIL.Lift/LiftDataMapper.cs
- SIL.Lift/Options/OptionRef.cs
- SIL.Lift/Options/OptionsList.cs
- SIL.TestUtilities/TemporaryFolder.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/FadingMessageForm.cs
- SIL.Windows.Forms/FolderBrowserControl/FolderBrowserControl.cs
- SIL.Windows.Forms/Reporting/MemoryManagement.cs
- SIL.Windows.Forms/Widgets/BetterGrid/BetterGrid.cs
- SIL.Windows.Forms/Widgets/BetterGrid/CellCustomDropDownList.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/516)
> Removed some compiler warnings caused by code not being CLS compliant.

- SIL.Core.Desktop/Settings/CrossPlatformSettingsProvider.cs
- SIL.Core.Desktop/i18n/StringCatalog.cs
- SIL.Core.Tests/Misc/GuardAgainstReentry.cs
- SIL.Core/CommandLineProcessing/CommandLineRunner.cs
- SIL.Core/Extensions/DateTimeExtensions.cs
- SIL.Core/Progress/Progress.cs
- SIL.Core/Progress/XslTransformWithProgress.cs
- SIL.Core/Reporting/UsageReporter.cs
- SIL.DictionaryServices.Tests/LexEntryRepositoryCreateItemTransitionTests.cs
- SIL.DictionaryServices.Tests/LexEntryRepositoryCreatedFromPersistedData.cs
- SIL.DictionaryServices.Tests/LexEntryRepositoryDeleteAllItemsTransitionTests.cs
- SIL.DictionaryServices.Tests/LexEntryRepositoryDeleteIdTransitionTests.cs
- SIL.DictionaryServices.Tests/LexEntryRepositoryDeleteItemTransitionTests.cs
- SIL.DictionaryServices.Tests/LexEntryRepositoryTests.cs
- SIL.DictionaryServices.Tests/Lift/LiftRepositoryTests.cs
- SIL.DictionaryServices.Tests/Lift/LiftWriterTests.cs
- SIL.Lift.Tests/Merging/LiftChangeReportTests.cs
- SIL.Lift/LiftDataMapper.cs
- SIL.Lift/MultiText.cs
- SIL.Media/SoundFieldControl.cs
- SIL.TestUtilities/TemporaryFolderTests.cs
- TestApps/ReportingTest/Reporting.TestApp.csproj
- TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj
These are also pretty simple and safe
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/501)
> Second round of changes to get rid of compiler warnings

- SIL.Windows.Forms.Scripture/SIL.Windows.Forms.Scripture.csproj
- SIL.Windows.Forms.Scripture/ToolStripVerseControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/518)
> Added ToolStripVerseControl (needed by Glyssen)

- SIL.Core.Tests/SIL.Core.Tests.csproj
- SIL.Core.Tests/Xml/XElementExtensionTests.cs
- SIL.Core.Tests/Xml/XmlUtilsTests.cs
- SIL.Core/SIL.Core.csproj
- SIL.Core/Xml/XElementExtensions.cs
- SIL.Core/Xml/XmlUtils.cs
- SIL.WritingSystems.Tests/SIL.WritingSystems.Tests.csproj
- SIL.WritingSystems/SIL.WritingSystems.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/519)
> Add more XElement extensions and Xml utilities

- SIL.Scripture.Tests/ScrVersTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/525)
> Changed class to public so it can be accessed by Paratext

- SIL.Core.Desktop/Properties/AssemblyInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/527)
> Update SIL.Core.Desktop with Acknowledgements

- SIL.Core.Tests/Xml/XmlUtilsTests.cs
- SIL.Core/Xml/XmlUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/523)
> Some refactorings in XmlUtils

- SIL.Windows.Forms/Properties/AssemblyInfo.cs
- SIL.Windows.Forms/SIL.Windows.Forms.csproj
- TestApps/ReportingTest/Reporting.TestApp.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/534)
> Remove references to IrrkLang in project but not in code

- SIL.Windows.Forms.Scripture/SIL.Windows.Forms.Scripture.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/535)
> Warning message ignored for 32-bit build and 64-bit build

- SIL.DblBundle.Tests/Usx/UsxDocumentTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/540)
> (Re)Make some constants and methods public which are used by Glyssen

- ExtractCopyright.Tests/ExtractCopyright.Tests.csproj
- ExtractCopyright.Tests/Properties/AssemblyInfo.cs
- ExtractCopyright/ExtractCopyright.csproj
- ExtractCopyright/Properties/AssemblyInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/541)
> Add strong name logic to ExtraCopyright projects

- SIL.Windows.Forms.Scripture.Tests/ScrPassageControlTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/544)
> Skip flaky UI tests on TeamCity

- SIL.Media.Tests/AudioRecorderTests.cs
- SIL.Media/AudioIrrKlangSession.cs
- TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj
- TestApps/SIL.Windows.Forms.TestApp/TestAppForm.Designer.cs
- TestApps/SIL.Windows.Forms.TestApp/TestAppForm.cs
Also adds a way to test interactively
Therefore makes TestApp x86 (since SIL.Media is)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/548)
> Use system sound play instead of IrrKlang

- SIL.Core/Xml/XmlUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/549)
> Get code for AppendAttribute from libpalaso-3.1 branch

- SIL.Media.Tests/AudioRecorderTests.cs
- SIL.Media/AudioIrrKlangSession.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/551)
> session.IsPlaying should be false during stopped event handler

- SIL.Windows.Forms/Reporting/MemoryManagement.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/556)
> Allow client to control garbage collection in CheckMemory

- SIL.Core.Desktop/Settings/CrossPlatformSettingsProvider.cs
- SIL.Core.Tests/IO/RobustFileTests.cs
- SIL.Core.Tests/IO/RobustIOTests.cs
- SIL.Core.Tests/SIL.Core.Tests.csproj
- SIL.Core/IO/RobustFile.cs
- SIL.Core/IO/RobustIO.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/560)
> BL-4705 Save settings using a RobustFile retry

- SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs
An attempt to make certain that this crash can't happen because the relevant controls can't be visible when the variable is null
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/562)
> BL-4684 ensure metadata links not clicked when imageInfo null

- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupDialog.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs
- TestApps/SIL.Windows.Forms.TestApp/TestAppForm.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/565)
> BL-4780 Allow setting aliases for languages in LanguageLookupDialog

- LanguageData.Tests/GetAndCheckSourcesTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/572)
> Skip this test on TC at least until the new URL is given by Ethnologue

- SIL.WritingSystems.Tests/GlobalWritingSystemRepositoryTests.cs
- SIL.WritingSystems/GlobalWritingSystemRepository.cs
* Fill the value in WS language id.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/576)
> Fix : LT-18668 Crash creating new project - Migration of WS Fails

- SIL.Windows.Forms/ReleaseNotes/ShowReleaseNotesDialog.cs
This is needed for Bloom, which is moving away from using translated
markdown files to generating HTML files based on the English HTML and
xliff files that contain translated text strings for the HTML file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/578)
> Allow ReleaseNotesDialog to handle raw HTML properly

- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/582)
> BL-4780 further changes to how UserSimplifiedChinese simplifies things

- SIL.BuildTasks.AWS/S3/S3BuildPublisher.cs
- SIL.BuildTasks.AWS/S3/S3Helper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/580)
> Add ability to upload a directory to S3 (BL-5089)

- Palaso.DictionaryServices/Lift/LiftDataMapper.cs
and there was much rejoicing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/589)
> remove CopyOverGlossesIfDefinitionsMissing

- SIL.Core/IO/FileUtils.cs
avoids problems with tests interfering with each other
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/592)
> use a TempFile for GrepFile search and replace

- LanguageData.Tests/LanguageData.Tests.csproj
- LanguageData.Tests/LanguageDataIndexTests.cs
- LanguageData/LanguageDataIndex.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/594)
> Fix generation of LanguageDataIndex.json

- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorDialog.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/596)
> BL-5464 improve internationalization of credits dialog

- SIL.Windows.Forms/Widgets/BitmapButton.cs
This addresses a problem reported in Bloom localization
(https://issues.bloomlibrary.org/youtrack/issue/BL-5506).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/598)
> Add word wrapping to BitmapButton control

- SIL.Core.Tests/IO/RobustIOTests.cs
- SIL.Core/IO/RobustIO.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/600)
> BL-5416 Improve RobustIO.LoadXElement NR path names

- LanguageData/LanguageDataIndex.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/603)
> too many EndObject writing out json

- SIL.WritingSystems/LdmlInFolderWritingSystemRepository.cs
* Checking the File Exist before copy the file
* Included, After Writingsystem modified should AcceptChanges
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/609)
> Fix : LT-18895 Crash appears when adding Audio WS

- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs
See https://issues.bloomlibrary.org/youtrack/issue/BL-5638 for the
motivation of this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/612)
> Preserve language choice in LanguageLookupControl

- SIL.WritingSystems.Tests/LdmlContentForTests.cs
- SIL.WritingSystems.Tests/Migration/LdmlInFolderWritingSystemRepositoryMigratorTests.cs
- SIL.WritingSystems/Migration/WritingSystemsLdmlV2To3Migration/LdmlVersion2MigrationStrategy.cs
Fix bug where RTL info was lost during migration from ldml v2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/611)
> Ldml bug fixes

- SIL.Windows.Forms.Keyboarding/KeyboardController.cs
- SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/617)
> Support Keyman 10 configuration link

- SIL.Media.Tests/SIL.Media.Tests.csproj
- SIL.Media.Tests/packages.config
- SIL.Media/SIL.Media.csproj
- SIL.Media/packages.config
- SIL.Windows.Forms/SIL.Windows.Forms.csproj
- SIL.Windows.Forms/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/623)
> Upgraded to Naudio 1.8.4

- SIL.Windows.Forms/SIL.Windows.Forms.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/626)
> Fixed mistake in the references for the new version of NAudio.

- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorDialog.cs
- SIL.Windows.Forms/Miscellaneous/PortableClipboard.cs
See https://issues.bloomlibrary.org/youtrack/issue/BL-5681 for the motivation of this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/628)
> Extend PortableClipboard to handle dialog TextBox controls

- SIL.Windows.Forms.Keyboarding.Tests/WindowsKeyboardControllerTests.cs
- SIL.Windows.Forms.Keyboarding/KeyboardController.cs
- SIL.Windows.Forms.Keyboarding/KeyboardDescription.cs
- SIL.Windows.Forms.Keyboarding/Linux/XkbKeyboardRetrievingAdaptor.cs
- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs
- SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardDescription.cs
- SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardSwitchingAdapter.cs
- SIL.Windows.Forms.Keyboarding/Windows/LayoutName.cs
- SIL.Windows.Forms.Keyboarding/Windows/LegacyKeymanKeyboardSwitchingAdapter.cs
- SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs
- SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardDescription.cs
- SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardUtils.cs
- SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs
- SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs
- SIL.Windows.Forms.WritingSystems/WSSortControl.cs
* Refactor KeyboardSwitchingAdapter
* Implement new adapter for KM 10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/627)
> Support Keyman10 Keyboard Switching

- SIL.Windows.Forms.Tests/ClearShare/MetadataTests.cs
- SIL.Windows.Forms/ClearShare/MetaData.cs
* update regex and add a test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/631)
> BL-5708 Allow multiline copyright holder

- SIL.Windows.Forms/SuperToolTip/SuperToolTip.cs
See https://issues.bloomlibrary.org/youtrack/issue/BL-5705 for the
motivation of this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/633)
> Tweak SuperToolTip to not constantly create/destroy windows

- SIL.Windows.Forms.WritingSystems/LanguageLookupDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/638)
> Use PortableClipboard in LanguageLookupDialog (for Linux)

- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- SIL.Windows.Forms.Keyboarding/packages.config
- SIL.WritingSystems/SIL.WritingSystems.csproj
- SIL.WritingSystems/packages.config
and Icu4c.Win.Min.56.1.82
I can't get master building locally (testapps can't find SIL.Media.dll) so this is untested before the PR
Note this Icu4c.Win.Min version changes the location of the icu dlls which may affect installers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/639)
> use icu.net 2.3.0

- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
reverting to verbose condition
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/644)
> Condition importing NDesk.DBus.targets was failing

- Palaso/Palaso.csproj
- Palaso/packages.config
- PalasoUIWindowsForms/PalasoUIWindowsForms.csproj
- PalasoUIWindowsForms/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/661)
> icu.net 2.3.2 (libpalaso-2.6)

- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- SIL.Windows.Forms.Keyboarding/packages.config
- SIL.WritingSystems/SIL.WritingSystems.csproj
- SIL.WritingSystems/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/654)
> use icu.net 2.3.2 (libpalaso-3.1)

- Palaso/Resources/CountryCodes.txt
- Palaso/Resources/LanguageCodes.txt
- Palaso/Resources/LanguageIndex.txt
and add extra country codes used by them
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/665)
> Feb 2018 Ethnologue files update

- SIL.Archiving/Generic/ArchivingActor.cs
- SIL.Archiving/IMDI/Schema/IMDI_3_0.cs
Add Ethnic Group, FamilySocialRole, and Code
(These fields are used by the IMDI export.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/645)
> St380 Add Ethnic Group, FamilySocialRole, and Code

- SIL.Archiving.Tests/IMDI30Tests.cs
- SIL.Archiving/Generic/ArchivingSession.cs
- SIL.Archiving/IMDI/Schema/IMDI_3_0.cs
Allow calling programs to access the file object so they
can attach additional information such as recording equipment
card: https://trello.com/c/IlOdLSNy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/653)
> St384 - Allow calling programs access to the IMDI file object

- GlobalAssemblyInfo.cs
- GlobalAssemblyInfo.props
- build/Palaso.proj
This should have been updated when I converted SIL.Core and SIL.WritingSystems to .NET Standard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/667)
> Update version to 4.2

- DistFiles/Palaso.en.tmx
- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.Designer.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupDialog.cs
- SIL.Windows.Forms/ImageToolbox/AcquireImageControl.cs
- SIL.Windows.Forms/ImageToolbox/OpenFileDialogWithViews.cs
- SIL.Windows.Forms/SIL.Windows.Forms.csproj
- SIL.Windows.Forms/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/670)
>  Merge libpalaso-4.1 into master

- SIL.Archiving.Tests/SimpleObjectTests.cs
- SIL.Archiving/Extensions.cs
card: https://trello.com/c/P2knXht8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/659)
> St389 - file names only allow one period

- CopyTo SayMore.bat
Uses new list of dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/652)
> Update Saymore copy

- SIL.Archiving/Generic/ArchivingSession.cs
- SIL.Archiving/IMDI/Schema/IMDI_3_0.cs
Add Description for actor, resource, and content
Add Contact information for actors
Add Ethnic group for Actors
Add Media file times for resources
Fix setting of task to not override subgenre
Card: https://trello.com/c/hgZrUmAB
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/657)
> St386 - add IMDI properties fields and notes

- SIL.Archiving/Generic/ArchivingSession.cs
- SIL.Archiving/IMDI/Schema/IMDI_3_0.cs
Project fields are added to the session and files
Card: https://trello.com/c/aW8AwRH9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/662)
> St391 - Add project fields

- SIL.Archiving/IMDI/Schema/IMDI_3_0.cs
Allow values available in the closed vocabulary
Card: https://trello.com/c/uCwpmaSo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/658)
> St387 - Don't force uppercase for involvment or planning

- SIL.Windows.Forms/ImageToolbox/Cropping/ImageCropper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/672)
> BL-5830 Add safety to PalasoImage function

- SIL.Core/PlatformUtilities/Platform.cs
This property returns a description string like 'Windows 10'
or 'Ubuntu 16.04.4 LTS'.
Note that you might have to add an app.config file to your executable
that lists the supported Windows versions in order to get the correct
Windows version reported!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/673)
> Add Platform.OperatingSystemDescription property

- SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardDescription.cs
* Do not crash if Keyman10 is not installed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/674)
> Fix newly introduced bug in keyboarding

- SIL.WritingSystems/LanguageLookup.cs
For instance "english" should select "English", not "Angloromani".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/676)
> Prefer closer matches in language lookup

- SIL.WritingSystems/LanguageLookup.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/678)
> Merge libpalaso-4.1 into master

- SIL.Windows.Forms.WritingSystems.Tests/LanguageLookupControlTests.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.Designer.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs
- SIL.Windows.Forms.WritingSystems/SIL.Windows.Forms.WritingSystems.csproj
- SIL.Windows.Forms.WritingSystems/ScriptsAndVariantsDialog.Designer.cs
- SIL.Windows.Forms.WritingSystems/ScriptsAndVariantsDialog.cs
- SIL.Windows.Forms.WritingSystems/ScriptsAndVariantsDialog.resx
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/WSIdentifierView.cs
- SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs
* add 'Scripts and Variants' link to
LanguageLookupControl and control visibility
* removed obsolete adjustment for moved link
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/683)
> BL-5736 Add Script link to LanguageLookup

- SIL.Windows.Forms.WritingSystems.Tests/LanguageLookupControlTests.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.Designer.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs
- SIL.Windows.Forms.WritingSystems/SIL.Windows.Forms.WritingSystems.csproj
- SIL.Windows.Forms.WritingSystems/ScriptsAndVariantsDialog.Designer.cs
- SIL.Windows.Forms.WritingSystems/ScriptsAndVariantsDialog.cs
- SIL.Windows.Forms.WritingSystems/ScriptsAndVariantsDialog.resx
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/WSIdentifierView.cs
- SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs
- SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageGalleryControl.Designer.cs
- SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageGalleryControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/688)
> Merge from libpalaso-4.1 onto master

- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupDialog.cs
* complete libpalaso side of things
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/692)
> BL-5736 Enable Variants

- SIL.Windows.Forms.WritingSystems.Tests/LanguageLookupControlTests.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/693)
> BL-5736 Enable Variants (cleaner version)

- SIL.Archiving.Tests/IMDI30Tests.cs
- SIL.Archiving/IMDI/Schema/IMDI_3_0.cs
Fixing the removal of <> broke the default null value logic
card: https://trello.com/c/9eUfILJG
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/699)
> st382b - Handle Genre set to null.

- SIL.Core/IO/RobustFile.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/705)
> BL-5936 Make RobustFile GetWriteTime methods do what they say

- SIL.Archiving.Tests/IMDI30Tests.cs
- SIL.Archiving/IMDI/Schema/IMDI_3_0.cs
Card: https://trello.com/c/hgZrUmAB
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/702)
> Include code from archiving actor to IMDI Actor

- SIL.Archiving/IMDI/IMDIFile.cs
- SIL.Archiving/IMDI/Schema/IMDI_3_0.cs
- SIL.Archiving/IMDI/xsd/imdi-v3.xsd
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/703)
> Update to remove Type from Quality as per latest IMDI schema

- SIL.Scripture/VerseRef.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/707)
> Update VerseRef to implement IComparable

- SIL.Scripture/SIL.Scripture.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/709)
> Set "Build Action" to "None" for versification files

- PalasoUIWindowsForms/Miscellaneous/X11.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/712)
> Make X11 class public

- SIL.Core/Program/Process.cs
This one takes two arguments, like the corresponding
System.Diagnostics.Process.Start() variant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/713)
> Add another SIL.Program.Process.SafeStart() variant

- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataDisplayControl.cs
- SIL.Windows.Forms/HtmlBrowser/XWebBrowser.cs
- SIL.Windows.Forms/Widgets/HtmlLabel.cs
These are all needed by Bloom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/714)
> More fixes for reliable browser display of web links on Linux

- SIL.Core/Localizer.cs
- SIL.Windows.Forms/i18n/L10NSharpLocalizer.cs
Also added a property and some methods
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/695)
> Improve Localizer by using interface rather than abstract class

- SIL.Archiving/Generic/ArchivingSession.cs
- SIL.Archiving/IMDI/Schema/IMDI_3_0.cs
Card: https://trello.com/c/i6PPaPJX
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/716)
> st394 - Add Session languages

- SIL.WritingSystems.Tests/IetfLanguageTagTests.cs
- SIL.WritingSystems/IetfLanguageTag.cs
* Added the code to create fully costomized WS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/721)
> Fix LT-19153: Unable to create fully customized writing system

- SIL.Core/IO/RobustIO.cs
We were getting hangs in Bloom when a multi-level directory had a file that couldn't be deleted. Turns out in February 2018 the libpalaso deletion code was changed to essentially require 40^(n-1) * 2 seconds wait, where n = level of nesting (n=1 if no child directories).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/723)
> Fix exponential retry & delay problem with DeleteDirectoryAndContents

- SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs
- SIL.WritingSystems/GlobalWritingSystemRepository.cs
- SIL.WritingSystems/IWritingSystemRepository.cs
- SIL.WritingSystems/LocalWritingSystemRepositoryBase.cs
- SIL.WritingSystems/WritingSystemRepositoryBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/722)
> Actually round trip unknown ldml content to global store

- SIL.Media/Naudio/RecordingDevice.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/725)
> BL-6127 Give RecordingDevice a meaningful equality function

- SIL.WritingSystems.Tests/LdmlDataMapperTests.cs
- SIL.WritingSystems/LdmlDataMapper.cs
* Changed the code to save the default font fole
* Added test case to test the code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/726)
> Fix bug with saving the default font role (LT-18669)

- Palaso.sln
- TestApps/TestAppKeyboard/TestAppKeyboard.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/730)
> Fix TestAppKeyboard reference to SIL.Windows.Forms.WritingSystems

- SIL.Archiving/Properties/Settings.Designer.cs
- SIL.Archiving/Properties/Settings.settings
- SIL.Archiving/app.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/728)
> Update link to Ramp User's Manual

- SIL.WritingSystems/LdmlInFolderWritingSystemRepository.cs
* Removed AcceptChanges which resets WS status
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/733)
> Fix: LT-19153 Unable to create fully customized writing system

- SIL.Windows.Forms/Widgets/BetterLabel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/749)
> BL-6384/5 Restore BetterLabel wrapping text

- SIL.Windows.Forms/Widgets/BetterLabel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/750)
> Merge libpalaso-4.2 into master

- SIL.Core/Email/MAPIHelper.cs
* Changed the code to avoid the crash
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/748)
> Fix: LT-19356 FLEx crashes when trying to send in a suggestion

- SIL.Scripture.Tests/VerseRefTests.cs
- SIL.Scripture/VerseRef.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/751)
> Fixed serialization of a default VerseRef

- SIL.WritingSystems/GlobalWritingSystemRepository.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/752)
> PTX-180 delete existing bad ldml file before move

- SIL.Archiving/IMDI/Schema/IMDI_3_0.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/754)
> Fix ID generated for IMDI language export

- SIL.Archiving/ArchivingLanguage.cs
- SIL.Archiving/SIL.Archiving.csproj
If we don't have one from any other source.
Note: makes SIL.Archiving depend on SIL.WritingSystems
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/755)
> Make ArchivingLanguage get EnglishName from Ethnologue

- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/757)
> BL-6464 Typing 'en' in Language Lookup should pre-select English

- SIL.Archiving/IMDI/Schema/IMDI_3_0.cs
(to conform to IMDI schema, which uses a sequence)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/758)
> Fix order of fields in IMDI Project object

- SIL.Archiving/IMDI/IMDIPackage.cs
- SIL.Archiving/IMDI/Schema/IMDI_3_0.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/759)
> Add project and description where needed for IMDI archive export

- SIL.Archiving.Tests/LanguageListTests.cs
- SIL.Archiving/IMDI/Lists/ItemListBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/760)
> Add missing language names and tags for IMDI export

- SIL.WritingSystems.Tests/LanguageLookupTests.cs
- SIL.WritingSystems/LanguageLookup.cs
Currently detects that they might be looking for sign language in English, French, Spanish.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/764)
> Enable user to see all sign languages (Bloom Bl-6153)

- SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageGalleryControl.Designer.cs
- SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageGalleryControl.cs
requested by https://issues.bloomlibrary.org/youtrack/issue/BL-6442
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/767)
> Improve ImageGalleryChooser result reporting

- SIL.Media.Tests/AudioRecorderTests.cs
- SIL.Media/AlsaAudio/AudioAlsaSession.cs
- SIL.Media/AlsaAudio/AudioRecorder.cs
- SIL.Media/AudioIrrKlangSession.cs
Also change exception to FileLoadException when trying to play
empty file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/772)
> Fix Audio tests on Linux

- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- SIL.Windows.Forms.Keyboarding/packages.config
- SIL.WritingSystems/SIL.WritingSystems.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/780)
> Upgrade to latest version of icu.net

- SIL.Windows.Forms.WritingSystems.Tests/LanguageLookupControlTests.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs
- SIL.WritingSystems.Tests/LanguageLookupTests.cs
- SIL.WritingSystems/LanguageLookup.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/784)
> Fix crashes in using LanguageLookupDialog

- SIL.Windows.Forms/SettingProtection/SettingProtectionDialog.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/787)
> Corrected confusing localization comment

- DistFiles/Palaso.en.tmx
- SIL.Windows.Forms/ClearShare/CreativeCommonsLicense.cs
- SIL.Windows.Forms/ClearShare/MetaData.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorDialog.Designer.cs
This was requested a year ago by a Bloom user (BL-5612).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/794)
> Handle Public Domain (CC0) in license control/dialog

- SIL.WritingSystems.Tests/GlobalWritingSystemRepositoryTests.cs
- SIL.WritingSystems.Tests/LdmlDataMapperTests.cs
- SIL.WritingSystems/LdmlDataMapper.cs
* Fix bug where collations that we handle weren't removed from
the existing ldml
* Enhance test coverage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/801)
> Fix recently introduced bug that duplicated collations

- SIL.Windows.Forms.Tests/ClearShare/CreativeCommonsLicenseTests.cs
- SIL.Windows.Forms/ClearShare/CreativeCommonsLicense.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/807)
> Provide string constant for CC0 URL

- SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/808)
> Fix crash bug on updating keyboards for missing culture

- SIL.Windows.Forms.WritingSystems/WSIdentifiers/WSIdentifierView.Designer.cs
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/WSIdentifierView.cs
* Fix odd behavior with the details when reusing
the view with related writing systems
* Give a combobox a better name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/809)
> Improve WSIdentifierView

- SIL.Lexicon.Tests/ProjectLexiconSettingsDataMapperTests.cs
- SIL.Lexicon/ProjectLexiconSettings.cs
- SIL.Lexicon/ProjectLexiconSettingsDataMapper.cs
* Added the feature to enable project sharing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/798)
> Fix: LT-19564 Improve LCM Project Sharing

- SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs
- SIL.WritingSystems/NumberingSystemDefinition.cs
* Add the NumberingSystemDefinition to the PM
* Add digit access (for use by view code)
Note: So far Flex is the only user of this model
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/814)
> Improve NumberingSystemDefinition API

- SIL.WritingSystems.Tests/SldrTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/816)
> If SLDR is offline (like today) ignore tests which need it

- SIL.Windows.Forms.WritingSystems/WSIdentifiers/CustomIdentifierView.Designer.cs
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/CustomIdentifierView.cs
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/CustomIdentifierView.resx
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/IpaIdentifierView.Designer.cs
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/IpaIdentifierView.cs
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/IpaIdentifierView.resx
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/VoiceIdentifierView.Designer.cs
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/VoiceIdentifierView.cs
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/VoiceIdentifierView.resx
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/WSIdentifierView.Designer.cs
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/WSIdentifierView.resx
- SIL.Windows.Forms/ClearShare/LicenseInfo.cs
* Add the L10NSharpExtender to controls and add comments for localizers
* Also change 'Unspecified' to 'Default' in IpaIdentifier view to
discourage novice users from changing it
* Also fix some typos in LicenseInfo code comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/818)
> Add localization to writing system identifier controls

- SIL.WritingSystems.Tests/IetfLanguageTagTests.cs
- SIL.WritingSystems/IetfLanguageTag.cs
* This will help debugging bad language data
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/819)
> Report more details about invalid codes from IetfLanguageTag.Create

- SIL.WritingSystems/Sldr.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/821)
> Handle bad ldml content being returned from the SLDR api

- TestApps/SIL.Windows.Forms.TestApp/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/824)
> Migrate to L10NSharp 4.0

- SIL.Windows.Forms/ClearShare/MetaData.cs
See https://issues.bloomlibrary.org/youtrack/issue/BL-7002.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/823)
> Omit copyright in MinimalCredits for CC0 (public domain) license

- SIL.Scripture/VerseRef.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/826)
> Small fix for VerseRef.IsParseable to prevent null-ref exception

- SIL.Windows.Forms.GeckoBrowserAdapter/GeckoFxWebBrowserAdapter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/828)
> Update for Geckofx60

- SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs
for unknown headsets that have the word "Headset" in their names or generic capability descriptions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/833)
> Removed unnecessary code and added support to display headset icon

- SIL.Archiving/SIL.Archiving.csproj
- SIL.Core.Desktop/SIL.Core.Desktop.csproj
- SIL.Core.Tests/SIL.Core.Tests.csproj
- SIL.Core/SIL.Core.csproj
- SIL.DblBundle/SIL.DblBundle.csproj
- SIL.DictionaryServices/SIL.DictionaryServices.csproj
- SIL.Lexicon/SIL.Lexicon.csproj
- SIL.Lift/SIL.Lift.csproj
- SIL.Linux.Logging/SIL.Linux.Logging.csproj
- SIL.Media/SIL.Media.csproj
- SIL.Scripture/SIL.Scripture.csproj
- SIL.TestUtilities/SIL.TestUtilities.csproj
- SIL.Windows.Forms.GeckoBrowserAdapter/SIL.Windows.Forms.GeckoBrowserAdapter.csproj
- SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj
- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- SIL.Windows.Forms.Scripture/SIL.Windows.Forms.Scripture.csproj
- SIL.Windows.Forms.Tests/SIL.Windows.Forms.Tests.csproj
- SIL.Windows.Forms.WritingSystems/SIL.Windows.Forms.WritingSystems.csproj
- SIL.Windows.Forms/SIL.Windows.Forms.csproj
- SIL.WritingSystems.Tests/SIL.WritingSystems.Tests.csproj
- SIL.WritingSystems/SIL.WritingSystems.csproj
(see https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/837)
> Create symbol packages together with nuget packages

- SIL.Windows.Forms.WritingSystems/WSIdentifiers/ScriptRegionVariantView.Designer.cs
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/ScriptRegionVariantView.resx
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/WSIdentifierView.Designer.cs
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/WSIdentifierView.cs
- SIL.Windows.Forms.WritingSystems/WSIdentifiers/WSIdentifierView.resx
* Fix "Abbreviation:" cutoff
* Fix right side alignment of comboboxes
* Fix odd grey combo boxes to be white
* Make single option special combobox select the one
item so the user doesn't have to
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/839)
> BL-7224 Script/Region/Variant dialog regression

- CHANGELOG.md
- Palaso.sln
- SIL.Core.Tests/SIL.Core.Tests.csproj
- SIL.NUnit3Compatibility/Does.cs
- SIL.NUnit3Compatibility/OneTimeSetUpAttribute.cs
- SIL.NUnit3Compatibility/OneTimeTearDownAttribute.cs
- SIL.NUnit3Compatibility/SIL.NUnit3Compatibility.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/842)
> Move NUnit 3 compatibility classes to separate nuget package

- SIL.Windows.Forms.Tests/Progress/LogBox/LogBoxTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/847)
> Changed/added categories to prevent running long-running LogBox test

- SIL.Archiving.Tests/SIL.Archiving.Tests.csproj
- SIL.Archiving.Tests/packages.config
- SIL.Archiving/SIL.Archiving.csproj
- SIL.Archiving/packages.config
- SIL.DblBundle.Tests/SIL.DblBundle.Tests.csproj
- SIL.DblBundle.Tests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/849)
> Updated to latest version (1.13.3) of DotNetZip

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/853)
> Release version 7.0.0

- SIL.Windows.Forms.Tests/Progress/LogBox/LogBoxTests.cs
- SIL.Windows.Forms/SIL.Windows.Forms-Designer.csproj
- SIL.Windows.Forms/SIL.Windows.Forms.csproj
- SIL.Windows.Forms/packages.config
Also mark long-running test as explicit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/854)
> Use TagLibSharp instead of TagLibSharp-patched

- SIL.Archiving/SIL.Archiving.csproj
- SIL.Core.Desktop/SIL.Core.Desktop.csproj
- SIL.Core.Tests/SIL.Core.Tests.csproj
- SIL.Core/SIL.Core.csproj
- SIL.DblBundle/SIL.DblBundle.csproj
- SIL.DictionaryServices/SIL.DictionaryServices.csproj
- SIL.Lexicon/SIL.Lexicon.csproj
- SIL.Lift/SIL.Lift.csproj
- SIL.Linux.Logging/SIL.Linux.Logging.csproj
- SIL.Media/SIL.Media.csproj
- SIL.NUnit3Compatibility/SIL.NUnit3Compatibility.csproj
- SIL.Scripture/SIL.Scripture.csproj
- SIL.TestUtilities/SIL.TestUtilities.csproj
- SIL.Windows.Forms.DblBundle/SIL.Windows.Forms.DblBundle.csproj
- SIL.Windows.Forms.GeckoBrowserAdapter/SIL.Windows.Forms.GeckoBrowserAdapter.csproj
- SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj
- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- SIL.Windows.Forms.Scripture/SIL.Windows.Forms.Scripture.csproj
- SIL.Windows.Forms.Tests/SIL.Windows.Forms.Tests.csproj
- SIL.Windows.Forms.WritingSystems/SIL.Windows.Forms.WritingSystems.csproj
- SIL.Windows.Forms/SIL.Windows.Forms.csproj
- SIL.WritingSystems.Tests/SIL.WritingSystems.Tests.csproj
- SIL.WritingSystems/SIL.WritingSystems.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/855)
> Add link to full changelog to package description

- CHANGELOG.md
- GitVersion.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/857)
> Include build number in AssemblyFileVersion

- SIL.Windows.Forms.GeckoBrowserAdapter/GeckoFxWebBrowserAdapter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/862)
> Fix crash in disposing GeckofxWebBrowserAdapter (20190916)

- SIL.Archiving.Tests/IMDIArchivingDlgViewModelTests.cs
- SIL.Archiving/ArchivingDlgViewModel.cs
- SIL.Archiving/IMDI/IMDIArchivingDlg.cs
- SIL.Core.Desktop.Tests/IO/DirectoryUtilitiesTests.cs
- SIL.Core.Desktop/IO/DirectoryUtilities.cs
Let the user know the directory is not accessible, without a fatal exception.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/863)
> SP-1816: Crash if archiving target directory is not accessible

- SIL.Scripture.Tests/SIL.Scripture.Tests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/867)
> Create nuget package for SIL.Scripture.Tests

- GitVersion.yml
- SIL.Archiving.Tests/IMDIArchivingDlgViewModelTests.cs
- SIL.Archiving/ArchivingDlgViewModel.cs
- SIL.Archiving/IMDI/IMDIArchivingDlg.cs
- SIL.Core.Desktop.Tests/IO/DirectoryUtilitiesTests.cs
- SIL.Core.Desktop/IO/DirectoryUtilities.cs
- SIL.Windows.Forms.GeckoBrowserAdapter/GeckoFxWebBrowserAdapter.cs
- SIL.Windows.Forms.GeckoBrowserAdapter/WebThumbnailViewer.cs
- SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorDialog.cs
- SIL.Windows.Forms/HtmlBrowser/IWebBrowser.cs
- SIL.Windows.Forms/HtmlBrowser/WinFormsBrowserAdapter.cs
- SIL.Windows.Forms/HtmlBrowser/XWebBrowser.Designer.cs
- SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageGalleryControl.Designer.cs
- SIL.Windows.Forms/ImageToolbox/ImageGallery/ThumbnailViewer.cs
- SIL.Windows.Forms/Miscellaneous/SILAboutBox.Designer.cs
- SIL.Windows.Forms/ReleaseNotes/ShowReleaseNotesDialog.Designer.cs
- SIL.Windows.Forms/Widgets/HtmlLabel.Designer.cs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/860)
> Merge master into feature/nuget

- CHANGELOG.md
- SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj
- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- SIL.Windows.Forms.WritingSystems.Tests/SIL.Windows.Forms.WritingSystems.Tests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/870)
> Use signed version of ibusdotnet (Fixes rest of #865)

- SIL.Windows.Forms/Reporting/MemoryManagement.cs
- SIL.Windows.Forms/SIL.Windows.Forms.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/871)
> Use portable PDB file for SIL.Windows.Forms

- SIL.Windows.Forms.WritingSystems/WSIdentifiers/ScriptRegionVariantView.cs
- SIL.WritingSystems.Tests/RegionSubtagTests.cs
- SIL.WritingSystems.Tests/SIL.WritingSystems.Tests.csproj
- SIL.WritingSystems.Tests/SldrTests.cs
- SIL.WritingSystems.Tests/StandardSubtagsTests.cs
- SIL.WritingSystems/RegionSubtag.cs
- SIL.WritingSystems/StandardSubtags.cs
Add the Code to RegionSubtag.ToString for Private Use regions.
Addresses https://jira.sil.org/browse/LT-19652
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/844)
> Disambiguate Private Use Regions (LT-19652)

- SIL.Media/Naudio/RecordingDevice.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/877)
> Fixed spelling error in comment in RecordingDevice.cs

- SIL.Core.Desktop/Reporting/ErrorReport.cs
* Allow Bloom to set our own problem reporting
dialog for when the user clicks "Details" in an error
report.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/880)
> BL-7923 Allow software to change reporting mechanism

- CHANGELOG.md
- SIL.DblBundle.Tests/SIL.DblBundle.Tests.csproj
- SIL.Scripture.Tests/SIL.Scripture.Tests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/882)
> [SIL.DblBundle.Tests] Create nuget package

- SIL.Core/Keyboarding/IKeyboardDefinition.cs
- SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs
- SIL.WritingSystems.Tests/LdmlDataMapperTests.cs
- SIL.WritingSystems/LdmlDataMapper.cs
* Handle kmp extension
* Roundtrip unknown formats without crashing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/883)
> Fix crash creating writing systems with kmp keyboards

- SIL.Windows.Forms.Keyboarding.Tests/LinuxKeyboardControllerTests.cs
- SIL.Windows.Forms.Keyboarding.Tests/XkbKeyboardAdapterTests.cs
- SIL.Windows.Forms.Keyboarding/KeyboardController.cs
- SIL.Windows.Forms.Keyboarding/Linux/XkbKeyboardRetrievingAdaptor.cs
Also some refactorings and a comment about a failing test that requires some production code changes to fix (cf #887).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/888)
> Fix unit test on Ubuntu 18.04

- SIL.Windows.Forms/Reporting/WinFormsExceptionHandler.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/889)
> Smaller change to Forms exception handler

- SIL.Windows.Forms/Reporting/WinFormsExceptionHandler.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/890)
> A further change to Win Forms exception handler

- SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/897)
> BL-8112 Fix crash when setting language to null

- SIL.WritingSystems.Tests/SldrTests.cs
- SIL.WritingSystems/Sldr.cs
* Add parameter to langtags and sldr requests asking for
staging data
* Add unit test for the LDML url builder
* Clean up the ByHand tests for SLDR that had suffered bitrot
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/900)
> Add environment variable to access SLDR staging site

- SIL.WritingSystems/LdmlInFolderWritingSystemRepository.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/903)
> Fixed typo in comment

- CHANGELOG.md
- Palaso.sln.DotSettings
- SIL.Scripture.Tests/VersificationTests.cs
- SIL.Scripture/Versification.cs
Also, improved a few comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/910)
> Added Versification.Table.Load overload to allow deserialization from TextReader

- Palaso.sln.DotSettings
- SIL.Archiving/IMDI/Lists/ItemListBase.cs
Also fixed misspelling of Telugu.
Note that this change was also merged without a code review (by accident) into the nuget branch, so if any changes are needed, we should also make them there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/911)
> Improved handling/reporting of error condition when data returned from mpi.nl/IMDI/Schema is invalid

- SIL.Scripture.Tests/ScrVersTests.cs
- SIL.Scripture/ScrVers.cs
- SIL.Scripture/Versification.cs
Simplified implementation of existing Save method
Improved/added unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/914)
> +semver:minor Added ScrVers.Save overload to allow serialization to a TextWriter

- SIL.WritingSystems.Tests/LdmlDataMapperTests.cs
- SIL.WritingSystems/LdmlDataMapper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/916)
> Fix bug where SimpleCustom collation could not be removed

- CHANGELOG.md
- SIL.Core.Tests/Xml/XmlSerializationHelperTests.cs
- SIL.Core/Xml/XmlSerializationHelper.cs
This allows for serialization/deserialization of objects using TextWriter/TextReader.
Also added unit tests for these new methods (none existed previously for this class).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/917)
> +semver:minor Added XmlSerializationHelper.Serialize<T> and XmlSerializationHelper.Deserialize<T>

- build/Palaso.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/909)
> Fix reporting NUnit 3 tests on TC

- build/build
* To not clean and re-build everything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/928)
> Fix new build script - default to Compile

- CHANGELOG.md
- SIL.Core/Network/HttpEncoderFromMono.cs
- SIL.Core/Network/HttpUtilityFromMono.cs
- SIL.WritingSystems/SIL.WritingSystems.csproj
- SIL.WritingSystems/Sldr.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/935)
> [feature/nuget] Deprecate HttpUtilityFromMono class

- l10n/.gitignore
- l10n/README.md
- l10n/crowdin.json
- l10n/l10n.proj
- l10n/l10ns.nuspec
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/927)
> Add libpalaso l10n tasks

- SIL.Windows.Forms.WritingSystems/LanguageLookupDialog.Designer.cs
- SIL.Windows.Forms.WritingSystems/WSFontControl.Designer.cs
- SIL.Windows.Forms.WritingSystems/WSSortControl.cs
- SIL.Windows.Forms/SettingProtection/SettingsPasswordDialog.Designer.cs
- l10n/crowdin.json
* Upload Palaso.en.xlf for localization
* Minor grammar fixes in strings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/945)
> Localization: Update source strings, fix upload

- SIL.Archiving/SIL.Archiving.csproj
- SIL.Windows.Forms.DblBundle/SIL.Windows.Forms.DblBundle-Designer.csproj
- SIL.Windows.Forms.DblBundle/SIL.Windows.Forms.DblBundle.csproj
- SIL.Windows.Forms.DblBundle/packages.config
- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- SIL.Windows.Forms.WritingSystems/SIL.Windows.Forms.WritingSystems-Designer.csproj
- SIL.Windows.Forms.WritingSystems/SIL.Windows.Forms.WritingSystems.csproj
- SIL.Windows.Forms.WritingSystems/packages.config
- SIL.Windows.Forms/SIL.Windows.Forms-Designer.csproj
- SIL.Windows.Forms/SIL.Windows.Forms.csproj
- SIL.Windows.Forms/packages.config
- TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp-Designer.csproj
- TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj
- TestApps/SIL.Windows.Forms.TestApp/packages.config
- l10n/l10n.proj
This depends on https://github.com/sillsdev/l10nsharp/pull/76
> PG-1365 added sil localizer methods to extract xliff

- Palaso.sln.DotSettings
- SIL.Windows.Forms.Keyboarding.Tests/XkbKeyboardAdapterTests.cs
- SIL.Windows.Forms.Keyboarding/Linux/XklConfigRegistry.cs
We already checked in most cases that we don't add the same
layout twice. However, in `ProcessLanguage` which adds the first
bunch of layouts we didn't check. It's not entirely clear why we
get the same layout twice (bug in Linux Mint?), but this change
deals with that case.
This PR is against the `master` branch.
> Check that we don't add duplicate layouts (LT-20288)

- SIL.Windows.Forms.WritingSystems/WSSortControl.Designer.cs
- SIL.Windows.Forms.WritingSystems/WSSortControl.cs
- SIL.Windows.Forms.WritingSystems/WSSortControl.resx
- TestApps/SIL.Windows.Forms.TestApp/Program.cs
- TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj
* Validate before saving to PM
* Validate on text change
* Remove timer
* Enable ICU testing in TestApp
> Fix LT-20269: Don't save bad ICU rules

- CHANGELOG.md
- SIL.Core/Reporting/ConsoleExceptionHandler.cs
- SIL.Core/Reporting/ExceptionHandler.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/964)
> Make ConsoleExceptionHandler public

- SIL.Windows.Forms.Keyboarding/Linux/UnityIbusKeyboardRetrievingAdaptor.cs
- SIL.Windows.Forms.Keyboarding/Linux/UnityKeyboardRetrievingHelper.cs
- SIL.Windows.Forms.Keyboarding/Linux/UnityXkbKeyboardRetrievingAdaptor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/966)
> [keyboarding] Fix keyboard setup for GnomeShell (LT-20188)

- SIL.Windows.Forms.WritingSystems.Tests/WritingSystemSetupPMTests.cs
- SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs
* Addresses part of LT-20348
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/968)
> Stop clearing script on ipa selection

- SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/972)
> Fix more places that could crash with an invalid culture (LT-19588)

- CHANGELOG.md
- SIL.Core.Tests/Xml/XmlSerializationHelperTests.cs
- SIL.Core/Xml/XmlSerializationHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/974)
> Added overload for SerializeToString to specify encoding

- SIL.Windows.Forms/Miscellaneous/PortableClipboard.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/980)
> Allow client to see errors loading image from clipboard (for BL-9009)

- SIL.Core.Tests/PlatformUtilities/PlatformTests.cs
- SIL.Core/PlatformUtilities/Platform.cs
- SIL.Windows.Forms.Keyboarding.Tests/CombinedIbusKeyboardRetrievingAdaptorTests.cs
- SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj
- SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs
- SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardRetrievingAdaptor.cs
- SIL.Windows.Forms.Keyboarding/Linux/UnityIbusKeyboardRetrievingAdaptor.cs
- SIL.Windows.Forms.Keyboarding/Linux/UnityXkbKeyboardRetrievingAdaptor.cs
- SIL.Windows.Forms.Keyboarding/Linux/XkbKeyboardRetrievingAdaptor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/981)
> [master - keyboarding] Fix detection of ibus keyboards in Cinnamon (LT-20418)

- SIL.Lift.Tests/SIL.Lift.Tests.csproj
- SIL.Linux.Logging.Tests/SIL.Linux.Logging.Tests.csproj
- SIL.Linux.Logging/SIL.Linux.Logging.csproj
- SIL.Media.Tests/SIL.Media.Tests.csproj
- SIL.Media/SIL.Media.csproj
- SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj
- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- TestApps/ReportingTest/Reporting.TestApp.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/986)
> Remove project references that are no longer needed

- SIL.Core.Tests/Extensions/StringExtensionTests.cs
- SIL.Core/Extensions/StringExtensions.cs
This is mostly taken from the implementation in Transcelerator. Needed by Glyssen for PG-1412.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/983)
> Improve filename checking

- SIL.Core.Tests/Extensions/StringExtensionTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/989)
> Fixed platform-specific unit tests for sanitizing paths so they work on Linux.

- SIL.DblBundle.Tests/Resources/TestBundleFiles/metadataVersion2_1.xml
to https://reap.sil.org
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/991)
> Update REAP URL

- CHANGELOG.md
- SIL.Windows.Forms/Properties/AssemblyInfo.cs
- SIL.Windows.Forms/ReleaseNotes/ShowReleaseNotesDialog.cs
- SIL.Windows.Forms/SIL.Windows.Forms.csproj
Succeeds PR #990
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/994)
> Replace MarkdownDeep with Markdig engine

- SIL.Scripture.Tests/VerseRefTests.cs
- SIL.Scripture/VerseRef.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/997)
> Update VerseRef.TryGetVerseNum() to handle non-latin numerals

- SIL.DblBundle.Tests/Resources/TestBundleFiles/metadataVersion2_1.xml
- SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs
- SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs
- SIL.WritingSystems/ILocalWritingSystemRepository.cs
- SIL.WritingSystems/LdmlInFolderWritingSystemRepository.cs
- SIL.WritingSystems/LocalWritingSystemRepositoryBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1019)
> Merge master into nuget branch

- SIL.Archiving/IMDI/IMDIArchivingDlgViewModel.cs
- SIL.Media/Naudio/AudioRecorder.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1025)
> Change http to https in comments and UI strings

- SIL.Windows.Forms.WritingSystems/WSKeyboardControl.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/995)
> Stop crashing designer for forms that use this control

- SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1033)
> Fix non-deterministic unit test failure

- SIL.Core/Reporting/ExceptionHandler.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1030)
> Re-apply PR https://github.com/sillsdev/libpalaso/pull/890

- GitVersion.yml
- SIL.Archiving/SIL.Archiving.csproj
- SIL.Core.Desktop/SIL.Core.Desktop.csproj
- SIL.Core.Tests/SIL.Core.Tests.csproj
- SIL.Core/SIL.Core.csproj
- SIL.DblBundle.Tests/SIL.DblBundle.Tests.csproj
- SIL.DblBundle/SIL.DblBundle.csproj
- SIL.DictionaryServices/SIL.DictionaryServices.csproj
- SIL.Lexicon/SIL.Lexicon.csproj
- SIL.Lift/SIL.Lift.csproj
- SIL.Linux.Logging/SIL.Linux.Logging.csproj
- SIL.Media/SIL.Media.csproj
- SIL.Scripture.Tests/SIL.Scripture.Tests.csproj
- SIL.Scripture/SIL.Scripture.csproj
- SIL.TestUtilities/SIL.TestUtilities.csproj
- SIL.Windows.Forms.DblBundle/SIL.Windows.Forms.DblBundle.csproj
- SIL.Windows.Forms.GeckoBrowserAdapter/SIL.Windows.Forms.GeckoBrowserAdapter.csproj
- SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj
- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- SIL.Windows.Forms.Scripture/SIL.Windows.Forms.Scripture.csproj
- SIL.Windows.Forms.Tests/SIL.Windows.Forms.Tests.csproj
- SIL.Windows.Forms.WritingSystems/SIL.Windows.Forms.WritingSystems.csproj
- SIL.Windows.Forms/SIL.Windows.Forms.csproj
- SIL.WritingSystems.Tests/SIL.WritingSystems.Tests.csproj
- SIL.WritingSystems/SIL.WritingSystems.csproj
* as per sillsdev/libpalaso#1011
* adjust paths to CHANGELOG.md in csproj files
* remove feature/nuget from GitVersion.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1035)
> Adjust references to CHANGELOG.md on master branch

- SIL.Windows.Forms/ImageToolbox/AcquireImageControl.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1039)
> Fix NullReferenceException in AcquireImageControl.Dispose()

- SIL.Core/IO/RobustFile.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1048)
> Added overload to RobustFile.Move to overwrite existing dest

- SIL.Core.Tests/SIL.Core.Tests.csproj
- SIL.Scripture.Tests/SIL.Scripture.Tests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1047)
> Publish nuget package for SIL.Core.Tests

- SIL.Archiving/SIL.Archiving.csproj
- SIL.Core.Desktop/SIL.Core.Desktop.csproj
- SIL.Core/SIL.Core.csproj
- SIL.DblBundle.Tests/SIL.DblBundle.Tests.csproj
- SIL.DblBundle/SIL.DblBundle.csproj
- SIL.DictionaryServices/SIL.DictionaryServices.csproj
- SIL.Lexicon/SIL.Lexicon.csproj
- SIL.Lift/SIL.Lift.csproj
- SIL.Linux.Logging/SIL.Linux.Logging.csproj
- SIL.Media/SIL.Media.csproj
- SIL.Scripture.Tests/SIL.Scripture.Tests.csproj
- SIL.Scripture/SIL.Scripture.csproj
- SIL.TestUtilities/SIL.TestUtilities.csproj
- SIL.Windows.Forms.DblBundle/SIL.Windows.Forms.DblBundle.csproj
- SIL.Windows.Forms.GeckoBrowserAdapter/SIL.Windows.Forms.GeckoBrowserAdapter.csproj
- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- SIL.Windows.Forms.Scripture/SIL.Windows.Forms.Scripture.csproj
- SIL.Windows.Forms.WritingSystems/SIL.Windows.Forms.WritingSystems.csproj
- SIL.Windows.Forms/SIL.Windows.Forms.csproj
- SIL.WritingSystems.Tests/SIL.WritingSystems.Tests.csproj
- SIL.WritingSystems/SIL.WritingSystems.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1045)
> Always use the latest version of L10NSharp

- Directory.Build.targets
- README.md
Copy packages to the local nuget repository
after packing, if the local nuget repo is specified
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1043)
> Copy packages to the local nuget repository  after packing, if the local nuget repo is specified

- CHANGELOG.md
- SIL.Core.Tests/Extensions/ProcessExtensionsTests.cs
- SIL.Core.Tests/SIL.Core.Tests.csproj
- SIL.Core/Extensions/ProcessExtensions.cs
- SIL.Windows.Forms.Tests/Progress/Commands/ProgressDialogHandlerTests.cs
This helps in suppressing unwanted warnings from the output.
+semver:minor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1050)
> Allow to redirect stdErr in RunProcess

- ExtractCopyright.Tests/ExtractCopyright.Tests.csproj
- SIL.Archiving.Tests/SIL.Archiving.Tests.csproj
- SIL.Core.Desktop.Tests/SIL.Core.Desktop.Tests.csproj
- SIL.Core.Tests/SIL.Core.Tests.csproj
- SIL.DblBundle.Tests/SIL.DblBundle.Tests.csproj
- SIL.DictionaryServices.Tests/SIL.DictionaryServices.Tests.csproj
- SIL.Lexicon.Tests/SIL.Lexicon.Tests.csproj
- SIL.Lift.Tests/SIL.Lift.Tests.csproj
- SIL.Linux.Logging.Tests/SIL.Linux.Logging.Tests.csproj
- SIL.Media.Tests/SIL.Media.Tests.csproj
- SIL.Scripture.Tests/SIL.Scripture.Tests.csproj
- SIL.TestUtilities.Tests/SIL.TestUtilities.Tests.csproj
- SIL.TestUtilities/SIL.TestUtilities.csproj
- SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj
- SIL.Windows.Forms.Scripture.Tests/SIL.Windows.Forms.Scripture.Tests.csproj
- SIL.Windows.Forms.Tests/SIL.Windows.Forms.Tests.csproj
- SIL.Windows.Forms.WritingSystems.Tests/SIL.Windows.Forms.WritingSystems.Tests.csproj
- SIL.WritingSystems.Tests/SIL.WritingSystems.Tests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1051)
> Update to NUnit 3.13

- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- SIL.Windows.Forms.Keyboarding/packages.config
- SIL.WritingSystems/SIL.WritingSystems.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1061)
> Upgrade to the latest ICU

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1064)
> Update ReadMe for the 6.0 branch

- SIL.Core/Email/MAPIHelper.cs
On Windows 10 the default is to use Unicode. Trying to send emails with the Ansi API fails for some email providers, e.g. Outlook. This change adds support for Unicode for Windows versions > 7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1072)
> Fix MapiHelper

- SIL.Archiving/ArchivingDlgViewModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1076)
> SP-2231: Improved error message in ArchivingDlgViewModel.AddFileGroup

- SIL.Core.Tests/Xml/XmlUtilsTests.cs
- SIL.Core/Xml/XmlUtils.cs
Add a utility method to remove XML namespaces
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1078)
> Remove XML Namespaces

- SIL.Core.Desktop/SIL.Core.Desktop.csproj
- SIL.Core.Desktop/Settings/UpdateSettings.cs
Part of https://jira.sil.org/browse/LT-19171
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1082)
> [API] Add settings for getting updates

- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs
See https://issues.bloomlibrary.org/youtrack/issue/BL-10061 for
pictures before and after.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1087)
> Tweak control sizes and locations to improve localization

- SIL.Archiving/SIL.Archiving.csproj
- SIL.Windows.Forms.DblBundle/SIL.Windows.Forms.DblBundle.csproj
- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- SIL.Windows.Forms.WritingSystems/SIL.Windows.Forms.WritingSystems.csproj
- SIL.Windows.Forms/SIL.Windows.Forms.csproj
- TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1090)
> Require newer L10nSharp

- SIL.Core.Desktop/Settings/CrossPlatformSettingsProvider.cs
- TestApps/ReportingTest/Settings.cs
Add a static method that clients can call to validate settings' providers
+semver:minor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1094)
> Ensure settings use CrossPlatformSettingsProvider

- Palaso.sln.DotSettings
- SIL.Scripture.Tests/BCVRefTests.cs
- SIL.Scripture/BCVRef.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1097)
> Enhanced MakeReferenceString to handle references in different books

- SIL.Scripture/BCVRef.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1098)
> Fixed stack overflow caused by recursive definition of AreEqual

- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1092)
> Improve display of version number on AppVeyor

- appveyor.yml
Also need to checkout a branch if it's not a PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1100)
> More improvements for AppVeyor

- SIL.Scripture.Tests/BCVRefTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1099)
> Added unit tests for BCVRef equality operator.

- SIL.Windows.Forms/ParentFormBase.cs
- TestApps/SIL.Windows.Forms.TestApp/ModalChildForm.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1115)
> Handled StartPosition of CenterParent when showing a modal child form

- CHANGELOG.md
- SIL.Core.Tests/Extensions/StringExtensionTests.cs
- SIL.Core/Extensions/StringExtensions.cs
This method was taken from Transcelerator code with minor adaptation. This logic is now needed in HearThis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1123)
> HT-359: Added GetLongestUsefulCommonSubstring

- CHANGELOG.md
- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.props
- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.targets
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1122)
> Copy `SIL.Windows.Forms.Keyboarding.dll.config` to output directory

- CHANGELOG.md
- Palaso.sln.DotSettings
- SIL.TestUtilities/FluentAssertXml.cs
- SIL.WritingSystems.Tests/LdmlDataMapperTests.cs
- SIL.WritingSystems/LdmlDataMapper.cs
- SIL.WritingSystems/StandardSubtags.cs
- SIL.WritingSystems/WritingSystemDefinition.cs
For at least one minority language, we need to use the case mapping from a regional language.
Required for https://jira.sil.org/browse/LT-20816
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1129)
> LT-20816: Add a Case Alias to LDML

- SIL.WritingSystems.Tests/LdmlDataMapperTests.cs
- SIL.WritingSystems/LdmlDataMapper.cs
* Look for /ldml/special/sil:external-resources/sil:case-tailoring@alias
* Round trip /ldml/special/sil:external-resources/sil:case-tailoring@transform
Documentation: https://github.com/silnrsi/sldr/blob/master/doc/sil_namespace.md#case-tailoring
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1133)
> Update case-tailoring element per documentation

- SIL.Core.Tests/Extensions/StringExtensionTests.cs
- SIL.Core/Extensions/StringExtensions.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1136)
> HT-359: Fixed problem with surrogate handling in GetLongestUsefulCommonSubstring

- SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj
- SIL.Windows.Forms.Keyboarding.Tests/packages.config
- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- SIL.Windows.Forms.Keyboarding/packages.config
- SIL.Windows.Forms.WritingSystems.Tests/SIL.Windows.Forms.WritingSystems.Tests.csproj
- SIL.Windows.Forms.WritingSystems.Tests/packages.config
+semver:feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1137)
> keyboarding: upgrade ibusdotnet for flatpak

- CHANGELOG.md
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.cs
This addresses https://issues.bloomlibrary.org/youtrack/issue/BL-11032.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1142)
> Fix CC-BY License problems if the license was once CC0

- CHANGELOG.md
- SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs
- SIL.Windows.Forms/ImageToolbox/ImageToolboxDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1147)
> Added option for alternate image metadata UI (BL-6259)

- SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardRetrievingAdaptor.cs
commit-id:889de444
---
**Stack**:
- #1150
- #1149
- #1144 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
> flatpak: keyboarding: flatpak-spawn keyman config

- SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs
- SIL.Windows.Forms.Keyboarding/Linux/UnityKeyboardRetrievingHelper.cs
commit-id:5d6599a0
---
**Stack**:
- #1150
- #1149 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
> flatpak: keyboarding: query preload-engines via spawn

- SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardSwitchingAdaptor.cs
> flatpak: keyboarding: xmodmap via spawn

- CHANGELOG.md
- SIL.Core.Tests/IO/TempFileTests.cs
- SIL.Core/IO/TempFile.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1156)
> Allow specifying a NamePrefix for temp files (BL-10005)

- SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs
- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1157)
> flatpak: keyboarding: handle empty gsettings array

- SIL.Windows.Forms/ClearShare/MetaData.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataDisplayControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1158)
> Only default NullLicense to CC if copyright is not set (BL-11093)

- SIL.Core/SIL.Core.csproj
- SIL.Scripture/SIL.Scripture.csproj
- SIL.Windows.Forms/SIL.Windows.Forms.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1163)
> Stop exporting JetBrains.Annotations

- ExtractCopyright.Tests/ExtractCopyright.Tests.csproj
- SIL.Archiving.Tests/SIL.Archiving.Tests.csproj
- SIL.Core.Desktop.Tests/SIL.Core.Desktop.Tests.csproj
- SIL.Core.Tests/SIL.Core.Tests.csproj
- SIL.DblBundle.Tests/SIL.DblBundle.Tests.csproj
- SIL.DictionaryServices.Tests/SIL.DictionaryServices.Tests.csproj
- SIL.Lexicon.Tests/SIL.Lexicon.Tests.csproj
- SIL.Lift.Tests/SIL.Lift.Tests.csproj
- SIL.Linux.Logging.Tests/SIL.Linux.Logging.Tests.csproj
- SIL.Media.Tests/SIL.Media.Tests.csproj
- SIL.Scripture.Tests/SIL.Scripture.Tests.csproj
- SIL.TestUtilities.Tests/SIL.TestUtilities.Tests.csproj
- SIL.TestUtilities/SIL.TestUtilities.csproj
- SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj
- SIL.Windows.Forms.Scripture.Tests/SIL.Windows.Forms.Scripture.Tests.csproj
- SIL.Windows.Forms.Tests/SIL.Windows.Forms.Tests.csproj
- SIL.Windows.Forms.WritingSystems.Tests/SIL.Windows.Forms.WritingSystems.Tests.csproj
- SIL.WritingSystems.Tests/SIL.WritingSystems.Tests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1168)
> Stop exporting NUnit3TestAdapter

- CHANGELOG.md
- Palaso.sln.DotSettings
- SIL.Core/PlatformUtilities/Platform.cs
- SIL.Core/Unicode/CharacterUtils.cs
- SIL.Windows.Forms.WritingSystems.Tests/LanguageLookupModelTests.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs
- SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs
- SIL.Windows.Forms.WritingSystems/SIL.Windows.Forms.WritingSystems.csproj
- SIL.Windows.Forms.WritingSystems/WSTree/WritingSystemTreeModel.cs
- SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs
- SIL.WritingSystems.Tests/IetfLanguageTagTests.cs
- SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs
- SIL.WritingSystems.Tests/Migration/IetfLanguageTagCleanerTests.cs
- SIL.WritingSystems.Tests/Migration/LdmlInFolderWritingSystemRepositoryMigratorTests.cs
- SIL.WritingSystems/IetfLanguageTag.cs
- SIL.WritingSystems/LanguageLookup.cs
- SIL.WritingSystems/Migration/IetfLanguageTagCleaner.cs
- SIL.WritingSystems/Migration/WritingSystemsLdmlV0To1Migration/FlexConformPrivateUseRfc5646TagInterpreter.cs
- SIL.WritingSystems/Migration/WritingSystemsLdmlV0To1Migration/Rfc5646Tag.cs
- SIL.WritingSystems/Migration/WritingSystemsLdmlV0To1Migration/WritingSystemDefinitionV1.cs
- SIL.WritingSystems/SIL.WritingSystems.csproj
- SIL.WritingSystems/StandardSubtags.cs
- SIL.WritingSystems/WellKnownSubtags.cs
This code was mostly pulled over from Bloom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1169)
> Added several methods to IetfLanguageTag class to support getting language names.

- CHANGELOG.md
- SIL.Windows.Forms.WritingSystems/Extensions.cs
- SIL.Windows.Forms/Extensions/ToolStripExtensions.cs
- TestApps/SIL.Windows.Forms.TestApp/Program.cs
- TestApps/SIL.Windows.Forms.TestApp/Properties/Resources.Designer.cs
- TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj
- TestApps/SIL.Windows.Forms.TestApp/TestAppForm.Designer.cs
- TestApps/SIL.Windows.Forms.TestApp/TestAppForm.cs
- TestApps/SIL.Windows.Forms.TestApp/TestAppForm.resx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1172)
> Moved InitializeWithAvailableUILocales to SIL.Windows.Forms

- .github/workflows/l10n-source.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1174)
> Use the correct path for the downloaded source translations

- .github/workflows/l10n-source.yml
- l10n/README.md
- l10n/crowdin.yml
- l10n/l10n.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1175)
> Change the GHA to use the Crowdin CLI to update localizations 

- SIL.Windows.Forms/SuperToolTip/SuperToolTipWindowData.cs
- TestApps/SIL.Windows.Forms.TestApp/TestAppForm.Designer.cs
- TestApps/SIL.Windows.Forms.TestApp/TestAppForm.resx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1178)
> Fix SuperToolTip width when text is long (BL-11297)

- SIL.WritingSystems/IetfLanguageTag.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1179)
> Don't crash if ICU not available

- SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1181)
> Layout improvements to LocalizationIncompleteDlg

- SIL.Windows.Forms.Scripture/VerseControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1185)
> PTX-22694: Add support for copying VerseRef using Ctrl+C

- SIL.Lexicon/SIL.Lexicon.csproj
- SIL.TestUtilities/SIL.TestUtilities.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1183)
> .NET Standard added for SIL.Lexicon and SIL.TestUtilities

- SIL.Windows.Forms.Scripture/VerseControl.Designer.cs
- SIL.Windows.Forms.Scripture/VerseControl.cs
- SIL.Windows.Forms/Widgets/EnterTextBox.cs
- SIL.Windows.Forms/Widgets/SafeComboBox.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1188)
> PTX-22682: Add copying/pasting from context menu in BCV control

- SIL.Windows.Forms.Scripture/VerseControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1189)
> PTX-22682: Create custom context menu for BCV

- SIL.Windows.Forms.Scripture/VerseControl.Designer.cs
- SIL.Windows.Forms.Scripture/VerseControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1194)
> Add custom context menu. Hide tooltip on opening context menu.

- SIL.Windows.Forms/CheckedComboBox/CheckedComboBox.cs
- TestApps/SIL.Windows.Forms.TestApp/ModalChildForm.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1196)
> Make CheckedComboBox summary display show any items that are initially checked

- SIL.Windows.Forms/CheckedComboBox/CheckedComboBox.cs
- TestApps/SIL.Windows.Forms.TestApp/ModalChildForm.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1197)
> Made CheckedComboBox display correctly when item list is changed after handle is created

- SIL.Windows.Forms.Scripture/VerseControl.Designer.cs
- SIL.Windows.Forms.Scripture/VerseControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1198)
> PTX-22682: Disable tooltips completely when context menu is opened

- CHANGELOG.md
- ExtractCopyright.Tests/ExtractCopyrightTests.cs
- ExtractCopyright/CopyrightFile.cs
- SIL.Core/Properties/AssemblyInfo.cs
- SIL.Core/SIL.Core.csproj
- SIL.Linux.Logging/Properties/AssemblyInfo.cs
- SIL.Linux.Logging/SIL.Linux.Logging.csproj
- SIL.Windows.Forms.Keyboarding/Properties/AssemblyInfo.cs
- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- SIL.Windows.Forms/Properties/AssemblyInfo.cs
- SIL.Windows.Forms/SIL.Windows.Forms.csproj
Fixes #1186.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1199)
> Replace deprecated Mono.Posix* with Mono.Unix

- SIL.WritingSystems/Sldr.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1205)
> Handle missing ICU library at runtime

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1208)
> Updated Changelog to prepare for release of 10.0.0

- CHANGELOG.md
- SIL.Core/IO/PathUtilities.cs
- SIL.Core/PlatformUtilities/Platform.cs
- SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageCollectionManager.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1209)
> Fixes needed for flatpak packages such as org.sil.Bloom (20220811)

- SIL.Core.Desktop/Settings/UpdateSettings.cs
* This was the preferred design choice for testing some
features of Automatic Updates in FieldWorks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1211)
> Add Testing channel to UpdateSettings

- SIL.WritingSystems/Sldr.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1213)
> Fix SLDR initialization for users with European number formats

- CHANGELOG.md
Some of the changes went in after the 10.0.0 release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1214)
> Update and fix CHANGELOG.md

- Palaso.sln.DotSettings
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1216)
> Add two acronyms: ISO and UTC

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1218)
> Preparation for v10.1.0 (additions require minor version change)

- CHANGELOG.md
- SIL.Core.Tests/Reporting/ExceptionHandlerTests.cs
- SIL.Core/Reporting/ExceptionHandler.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1223)
> +semver:minor Added TypeOfExistingHandler property to ExceptionHandler.

- CHANGELOG.md
- Palaso.sln.DotSettings
- SIL.Archiving.Tests/AccessProtocolListTests.cs
- SIL.Archiving/Generic/AccessProtocol/AccessProtocolList.cs
- SIL.Archiving/Resources/AccessProtocols.json
- SIL.Archiving/SIL.Archiving.csproj
This is probably not a "breaking change" per se, but it likely requires downstream products to do a data migration to prevent data loss.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1229)
> Changed REAP access protocol label from "Insite users" to "REAP users"

- SIL.WritingSystems.Tests/IetfLanguageTagTests.cs
- SIL.WritingSystems/IetfLanguageTag.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1230)
> Allow for empty uiLanguageTag in GetLocalizedLanguageName (BL-11247)

- CHANGELOG.md
- SIL.Core/Reporting/FontAnalytics.cs
- SIL.Core/SIL.Core.csproj
This has been developed and used by the Bloom project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1237)
> Add a simple font analytics class

- Palaso.sln.DotSettings
- SIL.Core/IO/PathHelper.cs
- SIL.Core/SIL.Core.csproj
to resolve a security concern.
Also clean something else up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1238)
> Update to Newtonsoft.Json 13.0.2

- SIL.Windows.Forms.Scripture/VerseControl.Designer.cs
- SIL.Windows.Forms.Scripture/VerseControl.cs
- SIL.Windows.Forms/Widgets/HorizontalSpinner.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1240)
> Add RTL Support to the BCV Control

- CHANGELOG.md
- SIL.Archiving/RampArchivingDlgViewModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1242)
> SP-2291: Set UseZip64WhenSaving to prevent crash with large archives

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1243)
> Updated Changelog to prepare for release of 11.0.0

- SIL.Windows.Forms/ImageToolbox/PalasoImage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1246)
> Make loading an image robustly retry on CorruptFileException

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1251)
> Update changelog to prepare for v12.0.1 release

- CHANGELOG.md
- SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs
- ImageChanged (image selected or cropped)
- MetadataChanged (copyright info loaded or edited)
- Required for https://jira.sil.org/browse/LT-21444
+semver:minor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1255)
> [API] Add events to ImageToolboxControl

- CHANGELOG.md
- SIL.Media/MediaInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1261)
> Changed the FrameRate reported in VideoInfo from FrameRate to AvgFrameRate

- CHANGELOG.md
- SIL.Scripture/VerseRef.cs
- SIL.Windows.Forms/ClearShare/ContributorsListControlViewModel.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/ContributorsListControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1259)
> Minor code cleanup. Made a few potentially useful static methods public.

- CHANGELOG.md
- SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1265)
> Update changelog to include Interop.WIA.dll for MSIL

- DistFiles/Palaso.en.xlf
- DistFiles/Palaso.es.xlf
- Palaso.sln.DotSettings
- SIL.Archiving/ArchivingDlgViewModel.cs
- SIL.Archiving/IMDI/IMDIArchivingDlgViewModel.cs
- SIL.Archiving/RampArchivingDlgViewModel.cs
- SIL.DblBundle/Bundle.cs
- SIL.DblBundle/Text/TextBundle.cs
- SIL.DictionaryServices/Processors/HomographMerger.cs
- SIL.Windows.Forms.DblBundle/SelectProjectDlgBase.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.cs
- SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs
- SIL.Windows.Forms/Miscellaneous/SILAboutBox.Designer.cs
- SIL.Windows.Forms/Miscellaneous/SILAboutBox.cs
- SIL.Windows.Forms/UniqueToken/UniqueToken.cs
This included fixing a few spelling errors in source strings.
Removed some strings from DistFiles/Palaso.en.xlf that are able to be detected when scanning with ExtractXliff
Also did a little Resharper-based code cleanup
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1267)
> Fixed some i18n problems

- TestApps/ClipboardTestApp/ClipboardTestApp.csproj
- TestApps/FastSplitterTest/FastSplitterTest.csproj
- TestApps/ReportingTest/Reporting.TestApp.csproj
- TestApps/SIL.Email.TestApp/SIL.Email.TestApp.csproj
- TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj
- TestApps/TestAppKeyboard/TestAppKeyboard.csproj
Resolves a recently-introduced crash loading System.Memory
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1274)
> Autogenerate Binding Redirects for Test Apps

- README.md
Replaces #1260.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1264)
> Update Linux build instructions

- SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs
- SIL.Windows.Forms/ImageToolbox/PalasoImage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1276)
> Don't change license if user clicks cancel

- CHANGELOG.md
- Palaso.sln.DotSettings
- SIL.Core.Tests/Data/StrLengthComparerTests.cs
- SIL.Core.Tests/Extensions/CollectionExtensionsTests.cs
- SIL.Core/Data/StrLengthComparer.cs
- SIL.Core/Extensions/CollectionExtensions.cs
- SIL.Windows.Forms/FileSystem/ConfirmFileOverwriteDlg.Designer.cs
- SIL.Windows.Forms/FileSystem/ConfirmFileOverwriteDlg.cs
- SIL.Windows.Forms/FileSystem/ConfirmFileOverwriteDlg.resx
- SIL.Windows.Forms/Miscellaneous/WaitCursor.cs
- TestApps/SIL.Windows.Forms.TestApp/TestAppForm.Designer.cs
- TestApps/SIL.Windows.Forms.TestApp/TestAppForm.cs
The only "change" (that probably only just barely warrants making a new major version) was to make the WaitCursor class (which previously only contained static methods and probably therefore should have been a static class) implement IDisposable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1281)
> Added some utility methods, ConfirmFileOverwriteDlg and new WaitCursor members

- CHANGELOG.md
- DistFiles/Palaso.en.xlf
- DistFiles/Palaso.es.xlf
- DistFiles/Palaso.fr.xlf
- Palaso.sln.DotSettings
- SIL.Windows.Forms.Tests/ClearShare/CreativeCommonsLicenseTests.cs
- SIL.Windows.Forms.Tests/ClearShare/MetadataEditorControlTests.cs
- SIL.Windows.Forms.Tests/ClearShare/MetadataTests.cs
- SIL.Windows.Forms/ClearShare/CreativeCommonsLicense.cs
- SIL.Windows.Forms/ClearShare/LicenseInfo.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorDialog.Designer.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorDialog.cs
- SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorDialog.resx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1278)
> Remove old CC IGO license option from UI

- .github/workflows/l10n-packaging.yml
- .github/workflows/l10n-source.yml
- README.md
- l10n/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1285)
> Update Localization Documentation

- .github/workflows/l10n-source.yml
- l10n/README.md
- l10n/crowdin.yml
- l10n/l10n.proj
* Download the existing Palaso.en.xlf and merge into it (preserves l10n of strings w/o i18n)
* Update to the latest ExtractXliff
* Update documentation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1290)
> Fix L10n Source Extraction

- CHANGELOG.md
- SIL.Core/Reporting/ErrorReport.cs
* include entire VersionString
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1292)
> BL-12665 Detect Win11 in error reports

- CHANGELOG.md
- SIL.Windows.Forms/ClearShare/Metadata.cs
- SIL.Windows.Forms/ImageToolbox/PalasoImage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1293)
> Fix 4 img metadata methods that could fail due to cloud or scanning interference

- SIL.Core.Tests/Code/RetryUtilityTests.cs
- SIL.Core/Code/RetryUtility.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1296)
> Add some tests for RetryUtility

- .github/workflows/l10n-packaging.yml
- .github/workflows/l10n-source.yml
- l10n/README.md
- l10n/crowdin.yml
- l10n/l10n.proj
- l10n/l10ns.nuspec
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1291)
> fix l10n.proj

- CHANGELOG.md
- README.md
- SIL.WritingSystems.Tests/LanguageLookupTests.cs
- SIL.WritingSystems/Readme.md
- SIL.WritingSystems/Resources/ianaSubtagRegistry.txt
Updated langtags.json and ianaSubtagRegistry.txt files
https://jira.sil.org/browse/LT-21618
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1300)
> Updated langtags.json and ianaSubtagRegistry.txt files

- CHANGELOG.md
- SIL.Windows.Forms/ClearShare/Metadata.cs
This fixes some weaknesses found by the Bloom team (BL-12823).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1302)
> Make metadata file I/O more robust with retries

- SIL.Windows.Forms/ImageToolbox/AcquireImageControl.Designer.cs
- SIL.Windows.Forms/ImageToolbox/AcquireImageControl.cs
- SIL.Windows.Forms/ImageToolbox/AcquireImageControl.resx
This reverts commit 7db35fd42ba48d0725f9998e64e8094e68f635b2.
(See conversation at https://github.com/sillsdev/libpalaso/pull/1301)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1303)
> Revert "LT-21652: polish picture dialog (#1301)"

- CHANGELOG.md
- SIL.Core/Extensions/StringExtensions.cs
Minor refactoring/cleanup in StringExtensions.cs and slight performance tweak to GetLongestUsefulCommonSubstring
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1308)
> Update changelog to prepare for v13.0.0 release

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1310)
> Added version 13.0.1 to CHANGELOG.md

- CHANGELOG.md
- SIL.Archiving/SIL.Archiving.csproj
- SIL.Windows.Forms.DblBundle/SIL.Windows.Forms.DblBundle.csproj
- SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj
- SIL.Windows.Forms.WritingSystems/SIL.Windows.Forms.WritingSystems.csproj
- SIL.Windows.Forms/SIL.Windows.Forms.csproj
- TestApps/SIL.Windows.Forms.TestApp/Program.cs
- TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1313)
> Upgraded to L10nSharp 7.0.0

- CHANGELOG.md
- Palaso.sln.DotSettings
- SIL.Core/CommandLineProcessing/CommandLineRunner.cs
- SIL.Core/IO/PathHelper.cs
- SIL.Windows.Forms.Tests/Progress/LogBox/LogBoxFormForTest.cs
- SIL.Windows.Forms.Tests/Progress/LogBox/LogBoxTests.cs
- SIL.Windows.Forms/Extensions/ControlExtensions.cs
- SIL.Windows.Forms/Progress/LogBox.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1314)
> Checked for disposed log box or caller-requested cancel in SafeInvoke

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1315)
> Prepare for version 14.0.0 release

- SIL.Core.Desktop/UsbDrive/UsbDriveInfo.cs
previously drive info was excluded from the netstandard package, however this is blocking us from upgrading a number of projects to dotnet 8. This adds usb drive info back in using the `DriveInfo.GetDrives()` API which is avalible on all dotnet platforms. 
One thing that's not clear to me is how I would go about testing this. I wouldn't be suprised if there were differences between the versions being used, but I'm not even sure where to start here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1316)
> add usb drive info to net standard

- CHANGELOG.md
- SIL.Windows.Forms/ImageToolbox/PalasoImage.cs
- SIL.Windows.Forms/Widgets/SilResources.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1319)
> Added static SilResources class with property SilLogo101x113.

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1321)
> Added version 14.1.0 to CHANGELOG.md

- SIL.Lift.Tests/Merging/SynchronicMergerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1322)
> Skip failing test on TeamCity

- CHANGELOG.md
- Palaso.sln.DotSettings
- SIL.Windows.Forms.DblBundle/ProjectsListBase.cs
- SIL.Windows.Forms.DblBundle/SIL.Windows.Forms.DblBundle.csproj
- TestApps/SIL.Windows.Forms.TestApp/ChooseProject.Designer.cs
- TestApps/SIL.Windows.Forms.TestApp/ChooseProject.cs
- TestApps/SIL.Windows.Forms.TestApp/ChooseProject.resx
- TestApps/SIL.Windows.Forms.TestApp/ExistingProjectsList.cs
- TestApps/SIL.Windows.Forms.TestApp/ExistingProjectsList.designer.cs
- TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj
- TestApps/SIL.Windows.Forms.TestApp/TestAppForm.Designer.cs
- TestApps/SIL.Windows.Forms.TestApp/TestAppForm.cs
Included a little bit of minor code cleanup.
Note: Caused crashing bug in HearThis, but also caused UX issue in Glyssen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1324)
> HT-475: Fix - Made it possible to select a project after double-clicking a column header

- SIL.Core.Desktop/SIL.Core.Desktop.csproj
- SIL.DictionaryServices/SIL.DictionaryServices.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1323)
> Added netstandard2.0 to SIL.DictionaryServices

- .github/workflows/build.yml
- ExtractCopyright.Tests/ExtractCopyright.Tests.csproj
- SIL.Archiving.Tests/SIL.Archiving.Tests.csproj
- SIL.Archiving/SIL.Archiving.csproj
- SIL.Core.Desktop.Tests/SIL.Core.Desktop.Tests.csproj
- SIL.Core.Tests/SIL.Core.Tests.csproj
- SIL.DblBundle.Tests/SIL.DblBundle.Tests.csproj
- SIL.DictionaryServices.Tests/SIL.DictionaryServices.Tests.csproj
- SIL.Lexicon.Tests/SIL.Lexicon.Tests.csproj
- SIL.Lift.Tests/SIL.Lift.Tests.csproj
- SIL.Linux.Logging.Tests/SIL.Linux.Logging.Tests.csproj
- SIL.Media.Tests/SIL.Media.Tests.csproj
- SIL.Media/SIL.Media.csproj
- SIL.Scripture.Tests/SIL.Scripture.Tests.csproj
- SIL.TestUtilities.Tests/SIL.TestUtilities.Tests.csproj
- SIL.Windows.Forms.Keyboarding.Tests/SIL.Windows.Forms.Keyboarding.Tests.csproj
- SIL.Windows.Forms.Scripture.Tests/SIL.Windows.Forms.Scripture.Tests.csproj
- SIL.Windows.Forms.Tests/SIL.Windows.Forms.Tests.csproj
- SIL.Windows.Forms.WritingSystems.Tests/SIL.Windows.Forms.WritingSystems.Tests.csproj
- SIL.Windows.Forms/SIL.Windows.Forms.csproj
- SIL.WritingSystems.Tests/SIL.WritingSystems.Tests.csproj
- SIL.WritingSystems/SIL.WritingSystems.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1334)
> Added GHA for build and test

- .github/workflows/build.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1343)
> Add binary logging and upload those logs on failure

- SIL.Core.Desktop.Tests/SIL.Core.Desktop.Tests.csproj
- SIL.Core.Desktop.Tests/UsbDrive/Linux/UDiskDeviceTests.cs
- SIL.Core.Desktop.Tests/UsbDrive/Linux/UDisksTests.cs
- SIL.Core.Desktop.Tests/UsbDrive/UsbDeviceInfoTests.cs
- SIL.Windows.Forms.Tests/Miscellaneous/PortableClipboardTests.cs
- SIL.WritingSystems.Tests/SldrTests.cs
This includes some fixes for flakiness I was seeing in other libraries.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1346)
> .NET8 SIL.Core.Desktop.Tests

- SIL.DblBundle.Tests/SIL.DblBundle.Tests.csproj
- SIL.DictionaryServices.Tests/SIL.DictionaryServices.Tests.csproj
- SIL.Lexicon.Tests/SIL.Lexicon.Tests.csproj
- SIL.Linux.Logging.Tests/SIL.Linux.Logging.Tests.csproj
- SIL.Linux.Logging.Tests/SyslogLoggerTests.cs
- SIL.TestUtilities.Tests/SIL.TestUtilities.Tests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1352)
> Added .NET8 for tests with no conflicts/failures

- SIL.Scripture.Tests/BCVRefTests.cs
- SIL.Scripture.Tests/SIL.Scripture.Tests.csproj
- SIL.Scripture.Tests/TestScrVers.cs
Also replaced RhinoMocks with Moq
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1353)
> .NET8 for SIL.Scripture.Tests

- CHANGELOG.md
- SIL.Archiving/IMDI/Lists/ItemListBase.cs
- SIL.Windows.Forms.Archiving/IMDI/IMDIArchivingDlg.cs
Also changed Cancel button to Close in IMDIArchivingDlg and improved layout of destination folder label.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1354)
> Fixed logic in ItemListBase.FindByValue to not rely on try-catch.

- SIL.WritingSystems/LanguageLookup.cs
- SIL.WritingSystems/StandardSubtags.cs
- SIL.WritingSystems/WritingSystemDefinition.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1368)
> Comment cleanup and minor code refactoring in WritingSystems

- CHANGELOG.md
- SIL.Windows.Forms.WritingSystems/LanguageLookupDialog.cs
- TestApps/SIL.Windows.Forms.TestApp/TestAppForm.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1369)
> Added Caption property to LanguageLookupDialog

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1372)
> Added version 15.0.0 to CHANGELOG.md

- SIL.Media/AlsaAudio/RecordingDevice.cs
- SIL.Windows.Forms/Progress/LogBox.cs
Fixes https://github.com/sillsdev/libpalaso/security/code-scanning/714
Fixes https://github.com/sillsdev/libpalaso/security/code-scanning/1935
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1381)
> Fix checks for null or empty array

- SIL.Archiving/IMDI/Schema/IMDI_3_0.cs
- SIL.Core/Reporting/AnalyticsEventSender.cs
- SIL.Core/Reporting/ConsoleErrorReporter.cs
- SIL.DictionaryServices/Processors/EntryMerger.cs
- SIL.Windows.Forms.GeckoBrowserAdapter/ReflectiveGeckoBrowser.cs
- SIL.Windows.Forms/Widgets/BitmapButton.cs
Fixes https://github.com/sillsdev/libpalaso/security/code-scanning/2710
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1385)
> Fix double-semicolons

- SIL.Windows.Forms.Archiving/Properties/AssemblyInfo.cs
Follow-up to #1360
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1390)
> [SIL.Windows.Forms.Archiving] Remove DotNetZip acknowledgement

- SIL.Archiving.Tests/IMDIArchivingDlgViewModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1391)
> [SIL.Archiving.Tests] Run IMDIArchivingDlgViewModelTests tests that failed on TeamCity

- CHANGELOG.md
- SIL.Core.Tests/Reporting/ConsoleErrorReporterTests.cs
- SIL.Core/Reporting/ConsoleErrorReporter.cs
- SIL.Core/Reporting/ExceptionHelper.cs
- SIL.Windows.Forms/Reporting/ExceptionReportingDialog.cs
This was in response to a tip from AI code review (though I don't know if it will actually make it 100% happy).
Also did a little minor refactoring and improved comments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1404)
> Made some methods static in ConsoleErrorReporter

- CHANGELOG.md
- SIL.Windows.Forms/SettingProtection/SettingsLauncherButton.Designer.cs
- SIL.Windows.Forms/SettingProtection/SettingsLauncherButton.cs
We need to change the color
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1405)
> Expose the link of the SettingsLauncherButton

- SIL.Windows.Forms.WritingSystems/WSTree/WritingSystemTreeModel.cs
- SIL.Windows.Forms/FileDialogExtender/HelperTypes.cs
- SIL.Windows.Forms/Widgets/BetterGrid/BetterGrid.cs
- SIL.WritingSystems/Migration/WritingSystemsLdmlV0To1Migration/FlexConformPrivateUseRfc5646TagInterpreter.cs
Fixes all of https://github.com/sillsdev/libpalaso/security/code-scanning?query=is%3Aopen+branch%3Amaster+rule%3Acs%2Fuseless-upcast%2Ccs%2Flinq%2Fuseless-select
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1412)
> Fix 'Redundant Select' & 'Useless upcast' warnings

- .github/workflows/build.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1416)
> Publish Nuget packages and symbols on a push to master

- SIL.Core.Tests/Data/IRepositoryTests.cs
- SIL.Scripture/BCVRef.cs
- SIL.Windows.Forms/ImageToolbox/ImageAcquisitionService.cs
Fixes https://github.com/sillsdev/libpalaso/security/code-scanning/1943
Fixes https://github.com/sillsdev/libpalaso/security/code-scanning/1945
Fixes https://github.com/sillsdev/libpalaso/security/code-scanning/3283
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1424)
> Fix empty conditional branch or loop body

- SIL.WritingSystems/IetfLanguageTag.cs
Judging by the branch name, you can surmise that this PR started off with much higher hopes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1426)
> Added logging for exceptions in GetNativeLanguageNameWithEnglishSubtitle

- SIL.Lift.Tests/Parsing/ParserTests.cs
- SIL.Media/AlsaAudio/AlsaAudioDevice.cs
Fixes https://github.com/sillsdev/libpalaso/security/code-scanning/37
Fixes https://github.com/sillsdev/libpalaso/security/code-scanning/38
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1423)
> Fix invalid string formatting

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1449)
> Added a couple sections to README

- SIL.Core.Tests/Extensions/DateTimeExtensionTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1455)
> Comment out a few failing DateTimeExtension tests for now

- .github/workflows/build.yml
- SIL.WritingSystems.Tests/IetfLanguageTagTests.cs
- SIL.WritingSystems/IetfLanguageTag.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1464)
> Work around Windows CultureInfo change for Dari (prs)

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/libpalaso/1467)
> Added v. 16.2.0 to CHANGELOG
